const editOceanFormControls = ({ editDetail = {}, shipping_line_id = '' }) => [
	{
		name        : 'location_id',
		type        : 'async_select',
		asyncKey    : 'list_locations',
		placeholder : 'Select Location',
		label       : 'Location',
		span        : 9,
		rules       : { required: 'This is required' },
	},

	{
		label          : 'Event Date',
		name           : 'event_date',
		type           : 'date_picker',
		withTimePicker : true,
		placeholder    : 'Event Date',
		span           : 4,
		rules          : { required: 'This is required' },
		value          : new Date(editDetail?.event_date),
	},
	{
		label          : 'Actual Date',
		name           : 'actual_date',
		type           : 'date_picker',
		withTimePicker : true,
		placeholder    : 'Actual Date',
		span           : 4,
		rules          : { required: 'This is required' },
		value          : new Date(editDetail?.actual_date),
	},

	{
		label       : 'Milestone',
		name        : 'milestone',
		type        : 'aync_create_select',
		value       : editDetail?.milestone,
		placeholder : 'Milestone',
		asyncKey    : 'list_shipping_line_events',
		params      : {
			shipping_line_id,
			source: 'tracking_job',
		},
		span  : 4,
		rules : { required: 'This is required' },
	},
	{
		label       : 'Transport Mode',
		name        : 'transport_mode',
		type        : 'text',
		placeholder : 'Transport Mode',
		span        : 4,
		rules       : { required: 'This is required' },
		value       : editDetail?.transport_mode,
	},
	{
		label       : 'Vessel Name',
		name        : 'vessel_name',
		type        : 'text',
		placeholder : 'Vessel Name',
		span        : 4,
		rules       : { required: 'This is required' },
		value       : editDetail?.vessel_name,
	},
	{
		label       : 'Voyage No',
		name        : 'voyage_no',
		type        : 'text',
		placeholder : 'Voyage no',
		span        : 4,
		rules       : { required: 'This is required' },
		value       : editDetail?.voyage_no,
	},
];

export default editOceanFormControls;
