export const EXCLUDE_CATEGORIES = [
	'INPUT_IGST_REVERSAL',
	'INPUT_SGST_REVERSAL',
	'INPUT_CGST_REVERSAL',
	'REVERSE_CHARGE_INPUT_CGST',
	'REVERSE_CHARGE_INPUT_SGST',
	'REVERSE_CHARGE_INPUT_IGST',
	'REVERSE_CHARGE_OUTPUT_CGST',
	'REVERSE_CHARGE_OUTPUT_SGST',
	'REVERSE_CHARGE_OUTPUT_IGST',
];
