export const amountControls = [
	{
		name         : 'loading_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Loading Amount',
		showOptional : false,
	},
	{
		name         : 'loading_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Loading Description',
		showOptional : false,
	},
	{
		name         : 'loading_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Loading Amount Tax',
		showOptional : false,
	},
	{
		name         : 'unloading_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Unloading Amount',
		showOptional : false,
	},
	{
		name         : 'unloading_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Unloading Description',
		showOptional : false,
	},
	{
		name         : 'unloading_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Unloading Amount Tax',
		showOptional : false,
	},
	{
		name         : 'loading_detention_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Loading Detention Amount',
		showOptional : false,
	},
	{
		name         : 'loading_detention_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Loading Detention Description',
		showOptional : false,
	},
	{
		name         : 'loading_detention_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Loading Detention Amount Tax',
		showOptional : false,
	},
	{
		name         : 'unloading_detention_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Unloading Detention Amount',
		showOptional : false,
	},
	{
		name         : 'unloading_detention_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Unloading Detention Description',
		showOptional : false,
	},
	{
		name         : 'unloading_detention_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Unloading Detention Amount Tax',
		showOptional : false,
	},
	{
		name         : 'incentive_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Incentive Amount',
		showOptional : false,
	},
	{
		name         : 'incentive_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Incentive Description',
		showOptional : false,
	},
	{
		name         : 'incentive_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Incentive Amount Tax',
		showOptional : false,
	},
	{
		name         : 'other_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Other Amount',
		showOptional : false,
	},
	{
		name         : 'other_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Other Description',
		showOptional : false,
	},
	{
		name         : 'other_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Other Amount Tax',
		showOptional : false,
	},
	{
		name         : 'damage_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Damage Amount',
		showOptional : false,
	},
	{
		name         : 'damage_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Damage Description',
		showOptional : false,
	},
	{
		name         : 'damage_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Damage Amount Tax',
		showOptional : false,
	},
	{
		name         : 'shortage_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Shortage Amount',
		showOptional : false,
	},
	{
		name         : 'shortage_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Shortage Description',
		showOptional : false,
	},
	{
		name         : 'shortage_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Shortage Amount Tax',
		showOptional : false,
	},
	{
		name         : 'penalty_amount',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Penalty Amount',
		showOptional : false,
	},
	{
		name         : 'penalty_description',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Penalty Description',
		showOptional : false,
	},
	{
		name         : 'penalty_amount_tax',
		placeholder  : 'Type here...',
		type         : 'text',
		span         : 4,
		label        : 'Penalty Amount Tax',
		showOptional : false,
	},
];
