export const deliveryControls = [
	{
		name         : 'grn_number',
		placeholder  : 'Type here...',
		label        : 'GRN Number',
		type         : 'text',
		span         : 4,
		showOptional : false,
	},
	{
		label          : 'GRN Date',
		name           : 'grn_date',
		type           : 'datepicker',
		withTimePicker : true,
		span           : 4,
		showOptional   : false,
	},
	{
		name         : 'po_number',
		placeholder  : 'Type here...',
		label        : 'PO Number',
		type         : 'text',
		span         : 4,
		showOptional : false,
	},
	{
		name         : 'po_date',
		label        : 'PO Date',
		type         : 'datepicker',
		span         : 4,
		showOptional : false,
	},
	{
		name         : 'delivery_qty',
		placeholder  : 'Type here...',
		label        : 'Delivery Qty',
		type         : 'number',
		span         : 4,
		showOptional : false,
	},
	{
		name         : 'outward_delivery_no',
		placeholder  : 'Type here...',
		label        : 'Outward Delivery No',
		type         : 'text',
		span         : 4,
		showOptional : false,
	},
	{
		name           : 'outward_delivery_date',
		label          : 'Outward Delivery Date',
		type           : 'datepicker',
		withTimePicker : true,
		usePortal      : true,
		span           : 4,
		showOptional   : false,
	},
	{
		name         : 'inward_delivery_number',
		placeholder  : 'Type here...',
		label        : 'Inward Delivery No',
		type         : 'text',
		span         : 4,
		showOptional : false,
	},
	{
		name           : 'inward_delivery_date',
		label          : 'Inward Delivery Date',
		type           : 'datepicker',
		withTimePicker : true,
		usePortal      : true,
		span           : 4,
		showOptional   : false,
	},
	{
		name           : 'delivery_date',
		label          : 'Delivery Date',
		type           : 'datepicker',
		withTimePicker : true,
		span           : 4,
		showOptional   : false,
	},
	{
		name           : 'loading_time',
		label          : 'Loading Time',
		type           : 'datepicker',
		withTimePicker : true,
		usePortal      : true,
		span           : 4,
		showOptional   : false,
	},
	{
		name         : 'repo_date',
		label        : 'Repo. Date',
		type         : 'datepicker',
		span         : 4,
		showOptional : false,
	},
	{
		name         : 'unloading_date',
		label        : 'Unloading Date',
		type         : 'datepicker',
		span         : 4,
		showOptional : false,
	},
	{
		name         : 'invoice_date',
		label        : 'Invoice Date',
		type         : 'datepicker',
		span         : 4,
		showOptional : false,
	},
	{
		name         : 'detention_days',
		placeholder  : 'Type here...',
		type         : 'number',
		span         : 4,
		label        : 'Detention Days',
		showOptional : false,
	},
	{
		name         : 'detention_at_factory',
		placeholder  : 'Type here...',
		type         : 'number',
		span         : 4,
		label        : 'Detention At Factory',
		showOptional : false,
	},
];
