import Label from '../Label';
import { commodityOptions } from '../utils/commodityOptions';
import { indentDhalaType } from '../utils/indentDhalaTypeOptions';
import { indentTruckType } from '../utils/indentTruckTypeOptions';
import { truckLengthOptions } from '../utils/truckLengthOptions';
import { truckType } from '../utils/truckTypeOptions';

import { amountControls } from './amountControls';
import { customerControls } from './customerControls';
import { deliveryControls } from './deliveryControls';
import { fleetOwnerDriverDetailControls } from './fleetOwnerDriverDetailControls';

export const formControls = {
	mainControls: [
		...customerControls,
		{
			name        : 'business_mode',
			placeholder : 'Type here...',
			type        : 'select',
			span        : 4,
			label       : <Label>Business Mode</Label>,
			options     : [
				{ label: 'FCM', value: 'fcm' },
				{ label: 'RCM', value: 'rcm' },
			],
		},
		{
			name        : 'cogo_entity_id',
			placeholder : 'Choose Entity',
			type        : 'select',
			span        : 4,
			label       : <Label required>Cogoport Entity</Label>,
			options     : [],
			rules       : {
				required: 'This is required',
			},
		},
		{
			name        : 'cogo_entity_address_id',
			placeholder : 'Choose Entity Address',
			type        : 'select',
			span        : 4,
			label       : <Label required>Cogoport Entity Address</Label>,
			options     : [],
			rules       : {
				required: 'This is required',
			},
		},
		{
			name        : 'truck_type',
			placeholder : 'Select',
			label       : <Label>Truck Type</Label>,
			type        : 'select',
			options     : truckType,
			span        : 4,
		},
		{
			name         : 'item_value',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			showOptional : false,
			label        : 'Item Value',
		},
		{
			name        : 'indent_truck_type',
			placeholder : 'Select',
			label       : <Label>Indent Truck Type</Label>,
			type        : 'select',
			options     : indentTruckType,
			span        : 4,
		},
		{
			name        : 'indent_dhala_type',
			placeholder : 'Select',
			label       : <Label>Indent Dhala Type</Label>,
			type        : 'select',
			options     : indentDhalaType,
			span        : 4,
		},
		{
			name        : 'indent_truck_length',
			placeholder : 'Select',
			label       : <Label>Indent Truck Length</Label>,
			type        : 'select',
			options     : truckLengthOptions,
			span        : 4,
		},
		{
			name         : 'consignor_name',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignor Name',
			showOptional : false,
		},
		{
			name         : 'consignor_address',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignor Address',
			showOptional : false,
		},
		{
			name         : 'consignor_gstin',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignor GSTIN',
			showOptional : false,
		},
		{
			name         : 'consignee_name',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignee Name',
			showOptional : false,
		},
		{
			name         : 'consignee_address',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignee Address',
			showOptional : false,
		},
		{
			name         : 'consignee_gstin',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignee GSTIN',
			showOptional : false,
		},
		{
			name           : 'from_town',
			placeholder    : 'Enter',
			label          : <Label>From Town</Label>,
			type           : 'text',
			optionsListKey : 'fortigo_locations',
			span           : 4,
		},
		{
			name           : 'to_town',
			placeholder    : 'Enter',
			label          : <Label>To Town</Label>,
			type           : 'text',
			optionsListKey : 'fortigo_locations',
			span           : 4,
		},
		{
			name         : 'place_of_supply',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Place of Supply',
			showOptional : false,
		},
		{
			name        : 'rate_type',
			placeholder : 'Select',
			label       : <Label required>Rate Type</Label>,
			type        : 'select',
			options     : [
				{ label: 'Fixed', value: 'Fixed' },
				{ label: 'RPT', value: 'RPT' },
			],
			span  : 4,
			rules : {
				required: {
					value   : true,
					message : 'This is required',
				},
			},
		},
		{
			name           : 'from_state',
			placeholder    : 'Enter',
			label          : <Label>From State</Label>,
			type           : 'text',
			optionsListKey : 'fortigo_locations',
			span           : 4,
		},
		{
			name           : 'to_state',
			placeholder    : 'Enter',
			label          : <Label>To State</Label>,
			type           : 'text',
			optionsListKey : 'fortigo_locations',
			span           : 4,
		},
		{
			name        : 'truck_no',
			placeholder : 'Type here...',
			type        : 'text',
			span        : 4,
			label       : <Label>Truck No</Label>,
		},
		{
			name        : 'actual_weight',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label required>Actual Weight</Label>,
			rules       : {
				required: {
					value   : true,
					message : 'This is required',
				},
			},
		},
		{
			name         : 'charged_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Charged Weight',
			showOptional : false,
		},
		{
			name        : 'tax_percent',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label required>Tax Percent</Label>,
			rules       : {
				required : 'This is required',
				min      : 0,
				max      : 100,
			},
		},
		{
			name        : 'rate',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label required>Rate</Label>,
			rules       : {
				required: {
					value   : true,
					message : 'This is required',
				},
			},
		},
		{
			name        : 'gcn_no',
			placeholder : 'Type here...',
			type        : 'text',
			span        : 4,
			label       : <Label>GCN No</Label>,
		},
		{
			name                  : 'gcn_date',
			label                 : <Label>GCN Date</Label>,
			type                  : 'datepicker',
			isPreviousDaysAllowed : true,
			span                  : 4,
		},
		{
			name        : 'value_of_goods',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label>Value of Goods</Label>,
		},
		{
			name         : 'kind_attention',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Kind Attention',
			showOptional : false,
		},
		{
			name         : 'invoice_no',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Invoice No',
			showOptional : false,
		},
		...amountControls,
		{
			name        : 'sac_code',
			placeholder : 'Select',
			label       : <Label required>SAC Code</Label>,
			type        : 'creatable-select',
			options     : [
				{ label: '996791 - Freight Transportation', value: 996791 },
				{ label: '996513 - Rental Invoice', value: 996513 },
			],
			span  : 4,
			rules : {
				required: {
					value   : true,
					message : 'This is required',
				},
			},
		},
		{
			name         : 'item_discount',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Item Discount',
			showOptional : false,
		},
		...fleetOwnerDriverDetailControls,
		{
			name                  : 'pickup_date_time',
			label                 : <Label>Pickup Date Time</Label>,
			type                  : 'datepicker',
			withTimePicker        : true,
			isPreviousDaysAllowed : true,
			span                  : 4,
		},
		{
			name        : 'eway_bill_no',
			placeholder : 'Type here...',
			label       : <Label>Eway Bill No</Label>,
			type        : 'text',
			span        : 4,
		},
		{
			name        : 'commodity_type',
			placeholder : 'Select',
			label       : <Label>Commodity Type</Label>,
			type        : 'select',
			options     : commodityOptions,
			span        : 4,
		},
		...deliveryControls,
		{
			name         : 'vendor_code',
			placeholder  : 'Type here...',
			label        : 'Vendor Code',
			type         : 'text',
			span         : 4,
			showOptional : false,
		},
		{
			name        : 'sale_price',
			placeholder : 'Type here...',
			label       : <Label>Sale Price</Label>,
			type        : 'number',
			span        : 4,
		},
		{
			name         : 'excess_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Excess Weight',
			showOptional : false,
		},
		{
			name         : 'short_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Short Weight',
			showOptional : false,
		},
		{
			name         : 'package_count',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'No. of Pkgs',
			showOptional : false,
		},
		{
			name         : 'sc_number',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'S.C. No.',
			showOptional : false,
		},
		{
			name         : 'loading_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Loading Weight',
			showOptional : false,
		},
		{
			name         : 'grade',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Grade',
			showOptional : false,
		},
		{
			name         : 'converted_case',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Converted Case',
			showOptional : false,
		},
		{
			name         : 'empty_quantity',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Empty Quantity',
			showOptional : false,
		},
		{
			name         : 'permit_no',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Permit No.',
			showOptional : false,
		},
	],
};
