/* eslint-disable max-lines-per-function */
import GLOBAL_CONSTANTS from '@cogoport/globalization/constants/globals';

const MIN_CARGO_WEIGHT = 18;
const fclControls = ({
	data,
	containerSizes,
	containerTypes,
	chargeCodeOptions,
	listShippingLineOptions,
	fclCommodityOptions,
	mainPortOptions1,
	mainPortOptions2,
	originLocationOptions,
	destinationLocationOptions,
	serviceProviders,
	organizationUsers,
	rateTypeOptions,
	currencyOptions,
}) => [
	{
		name    : 'service_provicer_details',
		heading : 'Service Provider Details',
		span    : 12,
	},
	{
		name        : 'service_provider_id',
		heading     : 'Service Provider',
		type        : 'select',
		placeholder : 'Service Provider',
		className   : 'primary lg',
		...serviceProviders,
		span        : 4,
		value       : data?.service_provider_id,
		rules       : { required: 'service provider is required' },
	},
	{
		name        : 'sourced_by_id',
		heading     : 'Rate Provided by user',
		type        : 'select',
		placeholder : 'Rate Provided by user',
		className   : 'primary lg',
		...organizationUsers,
		span        : 4,
		rules       : { required: 'rate provided by user is required' },
	},
	{
		name        : 'shipping_line_id',
		heading     : 'Shipping Line',
		type        : 'select',
		placeholder : 'Shipping Line',
		span        : 4,
		className   : 'primary lg',
		...listShippingLineOptions,
		rules       : { required: 'shipping line is required' },
	},
	{
		heading : 'Location Details',
		name    : 'location_details',
		span    : 12,
	},
	{
		name        : 'origin_location_id',
		heading     : 'Origin Location',
		type        : 'select',
		placeholder : 'Origin Location',
		span        : 4,
		value       : data?.origin_port?.id,
		disabled	   : data?.origin_port?.id,
		className   : 'primary lg',
		...originLocationOptions,
		rules       : { required: 'origin location is required' },
	},
	{
		name        : 'origin_main_port_id',
		type        : 'select',
		heading     : 'Origin Main port',
		placeholder : 'Origin Main port',
		span        : 4,
		...mainPortOptions1,
		className   : 'primary lg',
		rules       : { required: 'origin main port is required' },
	},
	{
		name        : 'destination_location_id',
		type        : 'select',
		heading     : 'Destination Location',
		span        : 4,
		value       : data?.destination_port?.id,
		disabled    : data?.destination_port?.id,
		className   : 'primary lg',
		...destinationLocationOptions,
		placeholder : 'Destination Location',
		rules       : { required: 'destination location is required' },
	},
	{
		name        : 'destination_main_port_id',
		type        : 'select',
		heading     : 'Destination main port',
		span        : 4,
		className   : 'primary lg',
		...mainPortOptions2,
		placeholder : 'Destination main port',
		rules       : { required: 'destination main port is required' },
	},
	{
		heading       : 'Container Details',
		name          : 'container_details',
		span          : 12,
		showOnlyLabel : true,
	},
	{
		name        : 'container_type',
		heading     : 'Container Type',
		type        : 'select',
		placeholder : 'Container Type',
		span        : 3,
		className   : 'primary lg',
		value       : data?.container_type || 'standard',
		disabled    : data?.container_type,
		options     : containerTypes,
		rules       : { required: 'container type is required' },
	},
	{
		name        : 'container_size',
		heading     : 'Container Size',
		type        : 'select',
		placeholder : 'Container Size',
		span        : 3,
		value       : data?.container_size || '20',
		disabled    : data?.container_size,
		className   : 'primary lg',
		options     : containerSizes,
		rules       : { required: 'container size is required' },
	},
	{
		name        : 'commodity',
		heading     : 'Commodity',
		type        : 'select',
		placeholder : 'Commodity',
		span        : 3,
		value       : data?.commodity,
		className   : 'primary lg',
		options     : fclCommodityOptions,
		rules       : { required: 'commodity is required' },
	},
	{
		name        : 'rate_type',
		type        : 'select',
		heading     : 'Rate Type',
		span        : 3,
		placeholder : 'Rate Type',
		className   : 'primary lg',
		options     : rateTypeOptions,
		rules       : {
			required: 'rate type is required',
		},
	},
	{
		heading : 'Other Details',
		name    : 'other_details',
		span    : 12,
	},
	{
		name        : 'validity_start',
		heading     : 'Validty Start',
		type        : 'date_picker',
		placeholder : 'Validity Start',
		span        : 3,
		minDate     : new Date(),
		rules       : {
			required: 'validity start date is required',
		},
	},
	{
		name        : 'validity_end',
		heading     : 'Validity End',
		type        : 'date_picker',
		placeholder : 'Validity End',
		span        : 3,
		minDate     : new Date(),
		rules       : {
			required: 'validity end date is required',
		},
	},
	{
		name        : 'detention_free_days',
		heading     : 'Detention Free Days',
		type        : 'number',
		placeholder : 'Detention Free Days',
		span        : 3,
		className   : 'primary lg',
		min         : 0,
		rules       : { required: 'detention free days is required' },
	},
	{
		name        : 'payment_term',
		heading     : 'Payment Term',
		type        : 'select',
		placeholder : 'Payment Term',
		value       : 'prepaid',
		span        : 3,
		className   : 'primary lg',
		options     : [
			{ label: 'Collect', value: 'collect' },
			{ label: 'Prepaid', value: 'prepaid' },
		],
	},
	{
		name        : 'free_weight',
		heading     : 'Free Weight Limit',
		type        : 'number',
		span        : 3,
		className   : 'primary lg',
		placeholder : 'Free Weight Limit',
		value:
			data?.cargo_weight_per_container <= MIN_CARGO_WEIGHT
				? data?.cargo_weight_per_container
				: MIN_CARGO_WEIGHT,
		rules: { required: 'free weight is required' },
	},
	{
		name        : 'schedule_type',
		heading     : 'Shipment Type',
		type        : 'select',
		span        : 3,
		className   : 'primary lg',
		placeholder : 'Select Shipment Type',
		options     : [
			{ label: 'Direct', value: 'direct' },
			{
				label : 'Transhipment',
				value : 'transhipment',
			},
		],
		rules: { required: 'shipment type is required' },
	},
	{
		name               : 'weight_slabs',
		heading            : 'Weight Slabs',
		type               : 'fieldArray',
		showButtons        : false,
		buttonText         : 'Add Weight Slabs',
		noDeleteButtonTill : 0,
		value:
			data?.cargo_weight_per_container > MIN_CARGO_WEIGHT
				? [
					{
						lower_limit : 18.1,
						upper_limit : data?.cargo_weight_per_container,
						currency    : GLOBAL_CONSTANTS.currency_code.USD,
						price       : 0,
					},
				]
				: undefined,
		controls: [
			{
				name        : 'lower_limit',
				type        : 'number',
				disabled    : true,
				span        : 4,
				placeholder : 'Lower Limit (in MT)',
				className   : 'primary lg',
				rules       : { required: 'lower limit is required' },
			},
			{
				name        : 'upper_limit',
				type        : 'number',
				span        : 4,
				className   : 'primary lg',
				placeholder : 'Upper Limit (in MT)',
				rules       : { required: 'upper limit is required' },
			},
			{
				name        : 'currency',
				type        : 'select',
				options     : currencyOptions,
				span        : 1.5,
				className   : 'primary lg',
				placeholder : 'Curr...',
				rules       : { required: 'currency is required' },
			},
			{
				name        : 'price',
				type        : 'number',
				span        : 1.5,
				className   : 'primary lg',
				placeholder : 'Price',
				rules       : { required: 'price is required' },
			},
		],
	},
	{
		heading       : 'Line Items',
		name          : 'line_item',
		span          : 12,
		showOnlyLabel : true,

	},
	{
		type               : 'fieldArray',
		showButtons        : true,
		name               : 'line_items',
		buttonText         : 'Add Line Items',
		noDeleteButtonTill : 1,
		controls           : [
			{
				name        : 'code',
				type        : 'select',
				span        : 3,
				placeholder : 'Charge Name',
				className   : 'primary lg',
				options     : chargeCodeOptions,
				rules       : { required: 'code is required' },
			},
			{
				name      : 'unit',
				span      : 3,
				type      : 'select',
				className : 'primary lg',
				value     : 'per_container',
				options   : [{
					label : 'Per Container',
					value : 'per_container',
				}],
				placeholder: 'Unit',
			},
			{
				name        : 'currency',
				span        : 2,
				type        : 'select',
				placeholder : 'Curr...',
				className   : 'primary lg',
				value       : 'USD',
				options     : currencyOptions,
			},
			{
				name        : 'price',
				span        : 3,
				type        : 'number',
				className   : 'primary lg',
				placeholder : 'Amount',
			},
			{
				name        : 'market_price',
				span        : 3,
				type        : 'number',
				className   : 'primary lg',
				placeholder : 'Market Price',
			},
			{
				name        : 'remarks',
				span        : 3,
				type        : 'text',
				className   : 'primary lg',
				placeholder : 'Add remarks here',
			},
		],
	},
	{
		name          : 'container_slabs',
		heading       : 'Container Slabs',
		span          : 12,
		showOnlyLabel : true,
	},
	{
		name               : 'container_slabs',
		type               : 'fieldArray',
		showButtons        : true,
		buttonText         : 'Add Container Count Wise BAS Slabs',
		noDeleteButtonTill : 0,
		controls           : [
			{
				name        : 'lower_limit',
				type        : 'number',
				placeholder : 'Lower Limit',
				span        : 3,
				className   : 'primary lg',
			},
			{
				name        : 'upper_limit',
				type        : 'number',
				span        : 3,
				placeholder : 'Upper Limit',
				className   : 'primary lg',
			},
			{
				name        : 'currency',
				placeholder : 'Currency',
				type        : 'select',
				options     : currencyOptions,
				span        : 3,
				className   : 'primary lg',
			},
			{
				name        : 'price',
				placeholder : 'Enter Price',
				type        : 'number',
				span        : 2,
				className   : 'primary lg',
			},
		],
	},
];
export default fclControls;
