/* eslint-disable max-lines-per-function */
import GLOBAL_CONSTANTS from '@cogoport/globalization/constants/globals';

const MIN_CARGO_WEIGHT = 18;
const fclControls = ({ data, containerSizes, containerTypes, options, listShippingLineOptions }) => [
	{
		label         : 'Service Provider Details',
		span          : 12,
		showOptional  : false,
		showOnlyLabel : true,
	},
	{
		name           : 'service_provider_id',
		placeholder    : 'Service Provider',
		type           : 'select',
		className      : 'primary lg',
		optionsListKey : 'verified-service-providers',
		defaultOptions : true,
		isClearable    : true,
		span           : 4,
		value          : data?.service_provider_id,
		showForScope   : ['partner'],
		showIfMissing  : true,
		rules          : { required: 'This is required' },
	},
	{
		name           : 'sourced_by_id',
		placeholder    : 'Rate Provided by user',
		type           : 'select',
		className      : 'primary lg',
		optionsListKey : 'organization-user',
		defaultOptions : true,
		isClearable    : true,
		span           : 4,
		showForScope   : ['partner'],
		valueKey       : 'user_id',
		showIfMissing  : true,
		params         : {
			filters: {},
		},
	},
	{
		name         : 'shipping_line_id',
		type         : 'select',
		span         : 4,
		className    : 'primary lg',
		...listShippingLineOptions,
		placeholder  : 'Shipping Line',
		showOptional : false,
	},
	{
		label         : 'Location Details',
		name          : 'location_details',
		showOptional  : false,
		span          : 12,
		showOnlyLabel : true,
	},
	{
		name           : 'origin_location_id',
		type           : 'select',
		span           : 4,
		value          : data?.origin_port?.id,
		disabled   	   : data?.origin_port?.id,
		className      : 'primary lg',
		optionsListKey : 'locations',
		placeholder    : 'Origin Location',
		params         : { filters: { type: ['seaport'] } },
		rules          : { required: 'This is required' },
	},
	{
		name           : 'destination_location_id',
		type           : 'location-select',
		span           : 4,
		value          : data?.destination_port?.id,
		disabled       : data?.destination_port?.id,
		className      : 'primary lg',
		optionsListKey : 'locations',
		params         : { filters: { type: ['seaport'] } },
		placeholder    : 'Destination Location',
		rules          : { required: 'This is required' },
	},
	{
		label         : 'Container Details',
		name          : 'container_details',
		span          : 12,
		showOptional  : false,
		showOnlyLabel : true,
	},
	{
		name        : 'container_type',
		type        : 'select',
		span        : 3,
		className   : 'primary lg',
		value       : data?.container_type || 'standard',
		disabled    : data?.container_type,
		placeholder : 'Container Type',
		rules       : { required: 'This is required' },
		options     : containerTypes,
	},
	{
		name        : 'container_size',
		type        : 'select',
		span        : 3,
		value       : data?.container_size || '20',
		disabled    : data?.container_size,
		className   : 'primary lg',
		placeholder : 'Container Size',
		options     : containerSizes,
		rules       : { required: 'This is required' },
	},
	{
		name          : 'commodity',
		type          : 'select',
		span          : 3,
		value         : data?.commodity || 'general',
		placeholder   : 'Commodity',
		className     : 'primary lg',
		commodityType : 'freight',
		rules         : { required: 'This is required' },
		style         : {
			menu: {
				width: '264px',
			},
		},
	},
	{
		name        : 'rate_type',
		type        : 'select',
		span        : 3,
		placeholder : 'Rate Type',
		className   : 'primary lg',
		style       : {
			menu: {
				width: '264px',
			},
		},
		options: [
			{
				label : 'Market place',
				value : 'market_place',
			},
			{
				label : 'Promotional',
				value : 'promotional',
			},
			{
				label : 'Spot booking',
				value : 'spot_booking',
			},
		],
		rules: {
			required: 'Rate Type is required',
		},
	},
	{
		label         : 'Other Details',
		name          : 'other_details',
		showOptional  : false,
		span          : 12,
		showOnlyLabel : true,
	},
	{
		name           : 'validity_start',
		type           : 'datepicker',
		withTimePicker : true,
		span           : 3,
		placeholder    : 'Validity Start',
		minDate        : new Date(),
		rules          : {
			required: 'Validity End date is required',
		},
	},
	{
		name           : 'validity_end',
		type           : 'datepicker',
		withTimePicker : true,
		span           : 3,
		placeholder    : 'Validity End',
		minDate        : new Date(),
		rules          : {
			required: 'Validity End date is required',
		},
	},
	{
		name         : 'detention_free_days',
		type         : 'number',
		span         : 3,
		placeholder  : 'Detention Free Days',
		showOptional : false,
		className    : 'primary lg',
		min          : 0,
		rules        : { required: 'This is required' },
	},
	{
		name        : 'payment_term',
		type        : 'select',
		placeholder : 'Payment Term',
		value       : 'prepaid',
		span        : 3,
		className   : 'primary lg',
		options     : [
			{ label: 'Collect', value: 'collect' },
			{
				label : 'Prepaid',
				value : 'prepaid',
			},
		],
	},
	{
		name         : 'free_weight',
		type         : 'number',
		lowerlabel   : 'In Metricton (MT)',
		span         : 3,
		className    : 'primary lg',
		showOptional : false,
		placeholder  : 'Free Weight Limit',
		value:
			data?.cargo_weight_per_container <= MIN_CARGO_WEIGHT
				? data?.cargo_weight_per_container
				: MIN_CARGO_WEIGHT,
		rules: { required: 'This is required' },
	},
	{
		name         : 'schedule_type',
		type         : 'select',
		span         : 3,
		className    : 'primary lg',
		showOptional : false,
		placeholder  : 'Select Shipment Type',
		options      : [
			{ label: 'Direct', value: 'direct' },
			{
				label : 'Transhipment',
				value : 'transhipment',
			},
		],
		rules: { required: 'This is required' },
	},
	{
		name               : 'weight_slabs',
		type               : 'fieldArray',
		showButtons        : false,
		buttonText         : 'Add Weight Slabs',
		noDeleteButtonTill : 0,
		value:
			data?.cargo_weight_per_container > MIN_CARGO_WEIGHT
				? [
					{
						lower_limit : 18.1,
						upper_limit : data?.cargo_weight_per_container,
						currency    : GLOBAL_CONSTANTS.currency_code.USD,
						price       : 0,
					},
				]
				: undefined,
		controls: [
			{
				name         : 'lower_limit',
				type         : 'number',
				disabled     : true,
				span         : 4,
				showOptional : false,
				placeholder  : 'Lower Limit (in MT)',
				className    : 'primary lg',
				rules        : { required: 'This is required' },
			},
			{
				name         : 'upper_limit',
				type         : 'number',
				span         : 4,
				showOptional : false,
				className    : 'primary lg',
				placeholder  : 'Upper Limit (in MT)',
				rules        : { required: 'This is required' },
			},
			{
				name           : 'currency',
				type           : 'select',
				optionsListKey : 'currencies',
				span           : 1.5,
				showOptional   : false,
				className      : 'primary lg',
				placeholder    : 'Curr...',
				rules          : { required: 'This is required' },
			},
			{
				name         : 'price',
				type         : 'number',
				span         : 1.5,
				showOptional : false,
				className    : 'primary lg',
				placeholder  : 'Price',
				rules        : { required: 'This is required' },
			},
		],
	},
	{
		label         : 'Line Items',
		name          : 'line_item',
		showOptional  : false,
		span          : 12,
		showOnlyLabel : true,
	},
	{
		type               : 'fieldArray',
		showButtons        : true,
		name               : 'line_items',
		buttonText         : 'Add Line Items',
		noDeleteButtonTill : 1,
		// value              : [
		// 	{
		// 		code  : 'BAS',
		// 		unit  : 'per_container',
		// 		// currency : GLOBAL_CONSTANTS.currency_code.USD,
		// 		price : null,
		// 	},
		// ],
		controls           : [
			{
				name        : 'code',
				type        : 'select',
				span        : 2,
				placeholder : 'Charge Name',
				className   : 'primary lg',
				disabled    : false,
				options,
				rules       : { required: 'This is required' },
			},
			{
				name      : 'unit',
				span      : 2,
				type      : 'select',
				className : 'primary lg',
				value     : 'per_container',
				options   : [{
					label : 'Per Container',
					value : 'per_container',
				}],
				placeholder: 'Unit',
			},
			{
				name           : 'currency',
				span           : 1.5,
				type           : 'select',
				placeholder    : 'Curr...',
				className      : 'primary lg',
				value          : 'USD',
				optionsListKey : 'currencies',
				showOptional   : false,
			},
			{
				name         : 'price',
				span         : 2,
				type         : 'number',
				showOptional : false,
				className    : 'primary lg',
				placeholder  : 'Amount',
			},
			{
				name         : 'market_price',
				span         : 2,
				type         : 'number',
				showOptional : false,
				className    : 'primary lg',
				placeholder  : 'Market Price',
			},
			{
				name        : 'remarks',
				span        : 2,
				type        : 'text',
				className   : 'primary lg',
				placeholder : 'Add remarks here',
			},
		],
	},
	{
		name          : 'Container Slabs',
		label         : 'Container Slabs',
		span          : 12,
		showOptional  : false,
		showOnlyLabel : true,
	},
	{
		name               : 'container_slabs',
		type               : 'fieldArray',
		showButtons        : true,
		buttonText         : 'Add Container Count Wise BAS Slabs',
		noDeleteButtonTill : 0,
		controls           : [
			{
				name         : 'lower_limit',
				type         : 'number',
				placeholder  : 'Lower Limit',
				span         : 3,
				showOptional : false,
				className    : 'primary lg',
			},
			{
				name         : 'upper_limit',
				type         : 'number',
				span         : 3,
				placeholder  : 'Upper Limit',
				showOptional : false,
				className    : 'primary lg',
			},
			{
				name           : 'currency',
				placeholder    : 'Currency',
				type           : 'select',
				optionsListKey : 'currencies',
				span           : 3,
				showOptional   : false,
				className      : 'primary lg',
			},
			{
				name         : 'price',
				placeholder  : 'Enter Price',
				type         : 'number',
				span         : 2,
				showOptional : false,
				className    : 'primary lg',
			},
		],
	},
];
export default fclControls;
