const dummyData = {
    list: [
        {
        name: "ABC Private limited..", 
        invoiceNumber: "INV/22/2000",
        category: "Office Maintainence",
        createdOn: "28 May 2023",
        expensePeriod: "28 May 2023 - 28 November 2023",
        recurringAmount: "INR 200,000",
        approvedBy: "Zubin Khanna",
        },
        {
            name: "ABC Private limited..", 
            invoiceNumber: "INV/22/2000",
            category: "Office Maintainence",
            createdOn: "28 May 2023",
            expensePeriod: "28 May 2023 - 28 November 2023",
            recurringAmount: "INR 200,000",
            approvedBy: "Zubin Khanna",
        },
        {
            name: "ABC Private limited..", 
            invoiceNumber: "INV/22/2000",
            category: "Office Maintainence",
            createdOn: "28 May 2023",
            expensePeriod: "28 May 2023 - 28 November 2023",
            recurringAmount: "INR 200,000",
            approvedBy: "Zubin Khanna",
            },
            {
                name: "ABC Private limited..", 
                invoiceNumber: "INV/22/2000",
                category: "Office Maintainence",
                createdOn: "28 May 2023",
                expensePeriod: "28 May 2023 - 28 November 2023",
                recurringAmount: "INR 200,000",
                approvedBy: "Zubin Khanna",
            },
            {
                name: "ABC Private limited..", 
                invoiceNumber: "INV/22/2000",
                category: "Office Maintainence",
                createdOn: "28 May 2023",
                expensePeriod: "28 May 2023 - 28 November 2023",
                recurringAmount: "INR 200,000",
                approvedBy: "Zubin Khanna",
                },
                {
                    name: "ABC Private limited..", 
                    invoiceNumber: "INV/22/2000",
                    category: "Office Maintainence",
                    createdOn: "28 May 2023",
                    expensePeriod: "28 May 2023 - 28 November 2023",
                    recurringAmount: "INR 200,000",
                    approvedBy: "Zubin Khanna",
                },
                {
                    name: "ABC Private limited..", 
                    invoiceNumber: "INV/22/2000",
                    category: "Office Maintainence",
                    createdOn: "28 May 2023",
                    expensePeriod: "28 May 2023 - 28 November 2023",
                    recurringAmount: "INR 200,000",
                    approvedBy: "Zubin Khanna",
                    },
                    {
                        name: "ABC Private limited..", 
                        invoiceNumber: "INV/22/2000",
                        category: "Office Maintainence",
                        createdOn: "28 May 2023",
                        expensePeriod: "28 May 2023 - 28 November 2023",
                        recurringAmount: "INR 200,000",
                        approvedBy: "Zubin Khanna",
                    },
                    {
                        name: "ABC Private limited..", 
                        invoiceNumber: "INV/22/2000",
                        category: "Office Maintainence",
                        createdOn: "28 May 2023",
                        expensePeriod: "28 May 2023 - 28 November 2023",
                        recurringAmount: "INR 200,000",
                        approvedBy: "Zubin Khanna",
                        },
                        {
                            name: "ABC Private limited..", 
                            invoiceNumber: "INV/22/2000",
                            category: "Office Maintainence",
                            createdOn: "28 May 2023",
                            expensePeriod: "28 May 2023 - 28 November 2023",
                            recurringAmount: "INR 200,000",
                            approvedBy: "Zubin Khanna",
                        },
                        {
                            name: "ABC Private limited..", 
                            invoiceNumber: "INV/22/2000",
                            category: "Office Maintainence",
                            createdOn: "28 May 2023",
                            expensePeriod: "28 May 2023 - 28 November 2023",
                            recurringAmount: "INR 200,000",
                            approvedBy: "Zubin Khanna",
                            },
                            {
                                name: "ABC Private limited..", 
                                invoiceNumber: "INV/22/2000",
                                category: "Office Maintainence",
                                createdOn: "28 May 2023",
                                expensePeriod: "28 May 2023 - 28 November 2023",
                                recurringAmount: "INR 200,000",
                                approvedBy: "Zubin Khanna",
                            },
                            {
                                name: "ABC Private limited..", 
                                invoiceNumber: "INV/22/2000",
                                category: "Office Maintainence",
                                createdOn: "28 May 2023",
                                expensePeriod: "28 May 2023 - 28 November 2023",
                                recurringAmount: "INR 200,000",
                                approvedBy: "Zubin Khanna",
                                },
],
pageIndex: 1,
totalPage: 2,
totalRecords: 14
}

export default dummyData