/* eslint-disable max-lines-per-function */
import containerSizes from '@cogoport/constants/container-sizes.json';

import { currencyOptions, rateTypeOptions } from '../../../../../configurations/helpers/constants';

const fclCustomsControls = ({
	data,
	fclCommodityOptions,
	originLocationOptions,
}) => [
	{
		name    : 'service_provicer_details',
		heading : 'Service Provider Details',
		span    : 12,
	},
	{
		name        : 'service_provider_id',
		heading     : 'Service Provider',
		type        : 'select',
		placeholder : 'Service Provider',
		span        : 4,
		value       : data?.service_provider_id,
		rules       : { required: 'service provider is required' },
	},
	{
		name        : 'sourced_by_id',
		heading     : 'Rate Provided by user',
		type        : 'select',
		placeholder : 'Rate Provided by user',
		value       : data?.sourced_by_id,
		span        : 4,
		rules       : { required: 'rate provided by user is required' },
	},

	{
		name         : 'location_details',
		label        : 'Location Details',
		span         : 12,
		showOptional : false,
	},
	{
		name        : 'origin_location_id',
		heading     : 'Origin Location',
		type        : 'select',
		placeholder : 'Origin Location',
		span        : 4,
		value       : data?.origin_port?.id,
		disabled	   : data?.origin_port?.id,
		...originLocationOptions,
		rules       : { required: 'origin location is required' },
	},
	{
		name           : 'trade_type',
		placeholder    : 'Select Trade Type',
		value          : data?.trade_type,
		disabled       : data?.trade_type,
		optionsListKey : 'trade-types',
		type           : 'select',
		span           : 4,
		className      : 'primary lg',
		caret          : true,
		rules          : { required: 'This is required' },
	},
	{
		name         : 'container_details',
		label        : 'Container Details',
		span         : 12,
		showOptional : false,
	},
	{
		name        : 'container_size',
		heading     : 'Container Size',
		type        : 'select',
		placeholder : 'Container Size',
		span        : 3,
		value       : data?.container_size || '20',
		disabled    : data?.container_size,
		options     : containerSizes,
		rules       : { required: 'container size is required' },
	},
	{
		name        : 'commodity',
		heading     : 'Commodity',
		type        : 'select',
		placeholder : 'Commodity',
		span        : 3,
		value       : data?.commodity,
		disabled    : data?.commodity,
		options     : fclCommodityOptions,
		rules       : { required: 'commodity is required' },
	},

	{
		name        : 'commodity',
		heading     : 'Commodity',
		type        : 'select',
		placeholder : 'Commodity',
		span        : 3,
		value       : data?.commodity,
		disabled    : data?.commodity,
		options     : fclCommodityOptions,
		rules       : { required: 'commodity is required' },
	},
	{
		name        : 'rate_type',
		type        : 'select',
		heading     : 'Rate Type',
		span        : 3,
		placeholder : 'Rate Type',
		options     : rateTypeOptions,
		rules       : {
			required: 'rate type is required',
		},
	},
	{
		label        : 'Line Items',
		name         : 'line_item',
		showOptional : false,
		span         : 12,
	},
	{
		label      : 'Add Custom Line Items',
		type       : 'fieldArray',
		heading    : 'Line Items',
		name       : 'line_items',
		buttonText : 'Add Line Items',
		controls   : [
			{
				name        : 'code',
				type        : 'select',
				span        : 1.5,
				placeholder : 'Charge Name',
				rules       : { required: 'code is required' },
			},
			{
				name        : 'unit',
				span        : 2,
				type        : 'select',
				className   : 'primary lg',
				placeholder : 'Unit',
			},
			{
				name        : 'currency',
				span        : 1.5,
				type        : 'select',
				placeholder : 'Curr...',
				options     : currencyOptions,
			},
			{
				name        : 'price',
				span        : 2,
				type        : 'number',
				placeholder : 'Amount',
			},
			{
				name        : 'remarks',
				span        : 2,
				type        : 'text',
				placeholder : 'Add remarks here',
			},
		],
	},

	{
		name         : 'cfs_items',
		label        : 'CFS Items',
		span         : 12,
		showOptional : false,
	},
	{
		label              : 'Add CFS Line Items',
		name               : 'fcl_customs_cfs_line_items',
		type               : 'fieldArray',
		showButtons        : true,
		buttonText         : 'Add Custom CFS Items',
		noDeleteButtonTill : 0,
		controls           : [
			{
				name           : 'code',
				caret          : true,
				type           : 'select',
				showToolTip    : true,
				valueKey       : 'code',
				placeholder    : 'Select Charge',
				className      : 'primary lg',
				span           : 2,
				defaultOptions : true,
				rules          : { required: 'This is required' },
			},
			{
				name        : 'currency',
				span        : 1.5,
				type        : 'select',
				placeholder : 'Curr...',
				options     : currencyOptions,
			},
			{
				name        : 'price',
				span        : 2,
				type        : 'number',
				placeholder : 'Enter amount',
				className   : 'primary lg',
				rules       : { required: 'This is required' },
			},
			{
				name        : 'unit',
				placeholder : 'Unit',
				type        : 'select',
				span        : 2,
				className   : 'primary lg',
				rules       : { required: 'This is required' },
			},
			{
				name        : 'remarks',
				placeholder : 'Remarks',
				type        : 'text',
				className   : 'primary lg',
				span        : 3,
			},
		],
	},
];

export default fclCustomsControls;
