export const DUMMY_DATA = [
	{
		sid               : 123456,
		service_type      : 'fcl_freight',
		importer_exporter : {
			short_name    : 'Test_Business30606',
			business_name : 'voltas',
		},
		shipment_type              : 'fcl_freight',
		commodity                  : 'general',
		inco_term                  : 'cif',
		payment_term               : 'prepaid',
		volume                     : 1.58,
		weight                     : 265,
		packages_count             : 11,
		cargo_weight_per_container : 18,
		container_size             : '20',
		container_type             : 'standard',
		containers_count           : 1,
		hs_code                    : null,
		service_provider           : {
			short_name    : 'Test_Business30606',
			business_name : 'Cosco Shipping',
		},
		origin_port: {
			name         : 'Jawaharlal Nehru (Nhava Sheva)',
			port_code    : 'INNSA',
			display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
		},
		origin_country: {
			name         : 'India',
			display_name : 'India, Asia',
		},
		destination_country: {
			name         : 'United Arab Emirates',
			display_name : 'United Arab Emirates, Meg',
		},
		destination_port: {
			display_name : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			name         : 'Jebel Ali',
		},
	},
	{
		sid                        : 912346,
		service_type               : 'fcl_freight',
		shipment_type              : 'fcl_freight',
		commodity                  : 'general',
		inco_term                  : 'cif',
		payment_term               : 'prepaid',
		volume                     : 1.58,
		weight                     : 265,
		packages_count             : 11,
		cargo_weight_per_container : 18,
		container_size             : '20',
		container_type             : 'standard',
		containers_count           : 1,
		hs_code                    : null,
		importer_exporter          : {
			short_name    : 'Test_Business30606',
			business_name : 'voltas',
		},
		service_provider: {
			short_name    : 'Test_Business30606',
			business_name : 'Cosco Shipping',
		},
		origin_port: {
			name         : 'Jawaharlal Nehru (Nhava Sheva)',
			port_code    : 'INNSA',
			display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
		},
		origin_country: {
			name         : 'India',
			display_name : 'India, Asia',
		},
		destination_country: {
			name         : 'United Arab Emirates',
			display_name : 'United Arab Emirates, Meg',
		},
		destination_port: {
			display_name : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			name         : 'Jebel Ali',
		},
	},
	{
		sid                        : 712346,
		service_type               : 'fcl_freight',
		shipment_type              : 'fcl_freight',
		commodity                  : 'general',
		inco_term                  : 'cif',
		payment_term               : 'prepaid',
		volume                     : 1.58,
		weight                     : 265,
		packages_count             : 11,
		cargo_weight_per_container : 18,
		container_size             : '20',
		container_type             : 'standard',
		containers_count           : 1,
		hs_code                    : null,
		importer_exporter          : {
			short_name    : 'Test_Business30606',
			business_name : 'voltas',
		},
		service_provider: {
			short_name    : 'Test_Business30606',
			business_name : 'Cosco Shipping',
		},
		origin_port: {
			name         : 'Jawaharlal Nehru (Nhava Sheva)',
			port_code    : 'INNSA',
			display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
		},
		origin_country: {
			name         : 'India',
			display_name : 'India, Asia',
		},
		destination_country: {
			name         : 'United Arab Emirates',
			display_name : 'United Arab Emirates, Meg',
		},
		destination_port: {
			display_name : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			name         : 'Jebel Ali',
		},
	},
	{
		sid                        : 512346,
		service_type               : 'fcl_freight',
		shipment_type              : 'fcl_freight',
		commodity                  : 'general',
		inco_term                  : 'cif',
		payment_term               : 'prepaid',
		volume                     : 1.58,
		weight                     : 265,
		packages_count             : 11,
		cargo_weight_per_container : 18,
		container_size             : '20',
		container_type             : 'standard',
		containers_count           : 1,
		hs_code                    : null,
		importer_exporter          : {
			short_name    : 'Test_Business30606',
			business_name : 'voltas',
		},
		service_provider: {
			short_name    : 'Test_Business30606',
			business_name : 'Cosco Shipping',
		},
		origin_port: {
			name         : 'Jawaharlal Nehru (Nhava Sheva)',
			port_code    : 'INNSA',
			display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
		},
		origin_country: {
			name         : 'India',
			display_name : 'India, Asia',
		},
		destination_country: {
			name         : 'United Arab Emirates',
			display_name : 'United Arab Emirates, Meg',
		},
		destination_port: {
			display_name : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			name         : 'Jebel Ali',
		},
	},
	{
		sid                        : 312346,
		service_type               : 'fcl_freight',
		shipment_type              : 'fcl_freight',
		commodity                  : 'general',
		inco_term                  : 'cif',
		payment_term               : 'prepaid',
		volume                     : 1.58,
		weight                     : 265,
		packages_count             : 11,
		cargo_weight_per_container : 18,
		container_size             : '20',
		container_type             : 'standard',
		containers_count           : 1,
		hs_code                    : null,
		importer_exporter          : {
			short_name    : 'Test_Business30606',
			business_name : 'voltas',
		},
		service_provider: {
			short_name    : 'Test_Business30606',
			business_name : 'Cosco Shipping',
		},
		origin_port: {
			name         : 'Jawaharlal Nehru (Nhava Sheva)',
			port_code    : 'INNSA',
			display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
		},
		origin_country: {
			name         : 'India',
			display_name : 'India, Asia',
		},
		destination_country: {
			name         : 'United Arab Emirates',
			display_name : 'United Arab Emirates, Meg',
		},
		destination_port: {
			display_name : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			name         : 'Jebel Ali',
		},
	},
];
