export const getControls = ({ countryOptions = {}, cityOptions = {} }) => [
	{
		...countryOptions,
		name        : 'country_id',
		label       : 'Country of Registration',
		type        : 'select',
		placeholder : 'Select a Country',
		style       : { flexBasis: '44%' },
		condition   : { type: ['country'] },
		rules       : { required: 'Country is required' },
	},
	{
		name        : 'business_name',
		label       : 'Name of the Organization',
		type        : 'text',
		style       : { flexBasis: '44%' },
		placeholder : 'Type here',
		rules       : { required: 'Name of the Organization is required' },
	},
	{
		name            : 'registration_proof_url',
		showLabel       : false,
		label           : 'Upload Tax Document Proof (PAN)',
		style           : { flexBasis: '100%' },
		type            : 'file',
		themeType       : 'secondary',
		draggable       : true,
		onlyURLOnChange : true,
		accept          : 'image/*',
		uploadType      : 'aws',
		rules           : { required: 'Tax Document is required' },
	},
	{
		name        : 'company_type',
		label       : 'Type of Company',
		type        : 'select',
		placeholder : 'Select an Organization Type',
		style       : { flexBasis: '44%' },
		rules       : { required: 'Company Type is required' },
	},
	{
		...cityOptions,
		name        : 'city_id',
		label       : 'Branch',
		type        : 'select',
		style       : { flexBasis: '44%' },
		placeholder : 'Select a city',
		condition   : { type: ['city'] },
		rules       : { required: 'City is Required' },
	},
];
