/* eslint-disable max-len */
import { IcCYelloCircle } from '@cogoport/icons-react';

import { agentAvatar } from '../page-components/CogoOneDashboard/constants';

export const busyAgentsData = [

	{
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	},
	{
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	}, {
		circle_icon : <IcCYelloCircle />,
		picture     : <img src={agentAvatar} alt="AA" />,
		name        : 'Mahima Khilji',
		call_status : 'on call',
		contact_nos : '240',
		duration    : '2h 30min',
	},
];
