const getControls = ({ item }) => [
	{
		name         : 'extension_name',
		label        : 'Extension Name',
		type         : 'text',
		span         : 4,
		value        : item?.extension_name,
		showOptional : false,
		className    : 'primary lg',
		placeholder  : 'Type Extension Name',
	},
	{
		name    : 'trade_type',
		label   : 'Trade Type',
		type    : 'select',
		span    : 4,
		options : [
			{
				value : 'export',
				label : 'Export',
			},
			{
				value : 'import',
				label : 'Import',
			},
		],
		value        : item?.trade_type,
		className    : 'primary lg',
		showOptional : false,
		isClearable  : true,
		placeholder  : 'Select Trade Type',
	},
	{
		name         : 'cluster_type',
		label        : 'Cluster Type',
		type         : 'select',
		span         : 4,
		value        : item?.cluster_type,
		showOptional : false,
		options      : [
			{ label: 'Location', value: 'location' },
			{ label: 'Commodity', value: 'commodity' },
			{ label: 'Container', value: 'container' },
		],
		defaultOptions : true,
		className      : 'primary lg',
		placeholder    : 'Cluster Type',
		rules          : { required: 'This is required' },
	},
	{
		name           : 'cluster_reference_name',
		label          : 'Cluster Reference Name',
		type           : 'select',
		value          : item?.cluster_reference_name,
		span           : 4,
		defaultOptions : true,
		showOptional   : false,
		className      : 'primary lg',
		placeholder    : 'Cluster Reference Name',
	},
	{
		name           : 'cluster_id',
		label          : 'Cluster',
		type           : 'select',
		value          : item?.cluster_id,
		span           : 4,
		showOptional   : false,
		defaultOptions : true,
		className      : 'primary lg',
		placeholder    : 'Cluster',
	},

	{
		name           : 'service_provider_id',
		placeholder    : 'Service Provider',
		label          : 'Service Provider',
		type           : 'select',
		value          : item?.service_provider_id,
		className      : 'primary lg',
		optionsListKey : 'verified-service-providers',
		defaultOptions : true,
		isClearable    : true,
		span           : 4,
		showForScope   : ['partner'],
		showIfMissing  : true,
		showOptional   : false,
		params         : {
			filters: {
				exclude_ids: [
					'6cc6b696-60f6-480b-bcbe-92cc8e642531',
					'5dc403b3-c1bd-4871-b8bd-35543aaadb36',
				],
			},
		},
	},
	{
		name           : 'shipping_line_id',
		label          : 'Shipping Line',
		type           : 'select',
		span           : 4,
		showOptional   : false,
		value          : item?.shipping_line_id,
		className      : 'primary lg',
		isClearable    : true,
		optionsListKey : 'shipping-lines',
		placeholder    : 'Shipping Line',
		defaultOptions : true,
	},

	{
		name           : 'line_item_charge_code',
		label          : 'Line Item Charge Code',
		type           : 'select',
		span           : 4,
		valueKey       : 'code',
		labelKey       : 'label',
		value          : item?.line_item_charge_code,
		showOptional   : false,
		defaultOptions : true,
		className      : 'primary lg',
		placeholder    : 'Line Item Charge code',
	},
	{
		name           : 'gri_currency',
		label          : 'Markup Currency',
		type           : 'select',
		span           : 4,
		value          : item?.gri_currency,
		optionsListKey : 'currencies',
		defaultOptions : true,
		showOptional   : false,
		className      : 'primary lg',
		placeholder    : 'Markup Currency',
	},
	{
		name         : 'gri_rate',
		label        : 'Markup Rate',
		type         : 'number',
		span         : 4,
		value        : item?.gri_rate,
		priceKey     : 'price',
		showOptional : false,
		placeholder  : 'Markup Rate',
		className    : 'primary lg',
	},
];
export default getControls;
