const controls = [
	{
		name        : 'locations',
		type        : 'nestedFieldArray',
		showButtons : true,
		buttonText  : 'Add Location',
		value       : {},
		controls    : [
			{
				name           : 'location_id',
				type           : 'aysnc_select',
				placeholder    : 'Select Location',
				label          : 'Location',
				optionsListKey : 'locations',
				asyncKey       : 'locations',
				params         : { filters: { type: ['airport'] } },
				span           : 5,
				className      : 'primary md',
				rules          : { required: 'This is required' },
			},
			{
				name        : 'milestones',
				type        : 'fieldArray',
				showButtons : true,
				buttonText  : 'Add Milestones',
				value       : {},
				controls    : [
					{
						label          : 'Expected Date',
						name           : 'expected_date',
						type           : 'date_picker',
						withTimePicker : true,
						placeholder    : 'Expected Date',
						span           : 4,
						className      : 'primary md',
						rules          : { required: 'This is required' },
					},
					{
						label          : 'Actual Date',
						name           : 'actual_date',
						type           : 'date_picker',
						withTimePicker : true,
						placeholder    : 'Actual Date',
						span           : 4,
						className      : 'primary md',
						rules          : { required: 'This is required' },
					},

					{
						label       : 'Milestone',
						name        : 'milestone',
						type        : 'text',
						placeholder : 'Milestone',
						span        : 4,
						className   : 'primary md',
						rules       : { required: 'This is required' },
					},
					{
						label       : 'Piece',
						name        : 'piece',
						type        : 'number',
						placeholder : 'Number of piece',
						span        : 4,
						className   : 'primary md',
						rules       : { required: 'This is required' },
					},
					{
						label       : 'Status',
						name        : 'status',
						type        : 'text',
						placeholder : 'Status',
						span        : 4,
						className   : 'primary md',
						rules       : { required: 'This is required' },
					},
					{
						label       : 'Flight Number',
						name        : 'flight_number',
						type        : 'text',
						placeholder : 'Flight Number',
						span        : 4,
						className   : 'primary md',
						rules       : { required: 'This is required' },
					},
				],
			},
		],
	},
];

export default controls;
