const oceanControls = ({ isDisabled, shipping_line_id }) => [
	{
		name        : 'containers',
		type        : 'fieldArray',
		showButtons : true,
		buttonText  : 'Add Container',
		value       : {},
		controls    : [
			{
				name        : 'container_no',
				type        : 'text',
				placeholder : 'Enter Container No',
				label       : 'Container No',
				span        : 5,
				className   : 'primary md',
				value       : [{ container_no: '' }],
				rules       : { required: 'This is required' },
				disabled    : isDisabled,
			},
			{
				name        : 'locations',
				type        : 'fieldArray',
				showButtons : true,
				buttonText  : 'Add Location',
				controls    : [
					{
						name           : 'location_id',
						type           : 'location-select',
						placeholder    : 'Select Location',
						label          : 'Location',
						optionsListKey : 'locations',
						span           : 5,
						className      : 'primary md',
						rules          : { required: 'This is required' },
					},
					{
						name        : 'milestones',
						type        : 'fieldArray',
						showButtons : true,
						buttonText  : 'Add Milestones',
						controls    : [
							{
								label          : 'Event Date',
								name           : 'event_date',
								type           : 'datepicker',
								withTimePicker : true,
								placeholder    : 'Event Date',
								span           : 4,
								className      : 'primary md',
								rules          : { required: 'This is required' },
							},
							{
								label          : 'Actual Date',
								name           : 'actual_date',
								type           : 'datepicker',
								withTimePicker : true,
								placeholder    : 'Actual Date',
								span           : 4,
								className      : 'primary md',
								rules          : { required: 'This is required' },
							},

							{
								label          : 'Milestone',
								name           : 'milestone',
								type           : 'creatable-select',
								placeholder    : 'Milestone',
								optionsListKey : 'milestone_select',
								params         : {
									shipping_line_id,
								},
								span      : 4,
								className : 'primary md',
								rules     : { required: 'This is required' },
							},
							{
								label       : 'Transport Mode',
								name        : 'transport_mode',
								type        : 'text',
								placeholder : 'Transport Mode',
								span        : 4,
								className   : 'primary md',
								rules       : { required: 'This is required' },
							},
							{
								label       : 'Vessel Name',
								name        : 'vessel_name',
								type        : 'text',
								placeholder : 'Vessel Name',
								span        : 4,
								className   : 'primary md',
								rules       : { required: 'This is required' },
							},
							{
								label       : 'Voyage No',
								name        : 'voyage_no',
								type        : 'text',
								placeholder : 'Voyage no',
								span        : 4,
								className   : 'primary md',
								rules       : { required: 'This is required' },
							},
						],
					},
				],
			},
		],
	},
];

export default oceanControls;
