export const addTruckConfigs = [
	{
		name             : 'truck_config',
		type             : 'fieldArray',
		value            : [{ truck_type: '' }],
		showButtons      : false,
		showDeleteButton : false,
		controls         : [
			{
				name      : 'truck_type',
				type      : 'text',
				label     : 'Truck Type',
				className : 'primary lg',
				span      : 4,
				disabled  : true,
				rules     : { required: 'Truck Type is required' },
			},
			{
				name      : 'truck_number',
				type      : 'text',
				label     : 'Truck Number',
				className : 'primary lg',
				span      : 4,
				disabled  : true,
				rules     : { required: 'Truck Number is required' },
			},
			{
				name      : 'driver_name',
				type      : 'text',
				label     : 'Driver Name',
				className : 'primary lg',
				span      : 4,
				disabled  : true,
				rules     : { required: 'Driver Name is required' },
			},
			{
				name      : 'contact_number',
				type      : 'text',
				label     : 'Contact Number',
				className : 'primary lg',
				span      : 3,
				disabled  : true,
				rules     : { required: 'Contact Number is required' },
			},
			{
				name      : 'estimated_departure',
				type      : 'datepicker',
				label     : 'ETD',
				className : 'primary',
				span      : 3,
				disabled  : true,
				rules     : { required: 'Estimated Departure is required' },
			},
			{
				name      : 'estimated_arrival',
				type      : 'datepicker',
				label     : 'ETA',
				className : 'primary',
				span      : 3,
				disabled  : true,
				rules     : { required: 'Estimated Arrival is required' },
			},
			{
				name      : 'weight',
				type      : 'text',
				label     : 'Weight',
				className : 'primary lg',
				span      : 3,
				disabled  : true,
			},
		],
	},
];
