const controls = () => ([
	{
		name        : 'name',
		label       : 'Name',
		type        : 'input',
		placeholder : 'First Name',
		rules       : { required: 'This is required' },
	},
	// {
	// 	name        : 'middle_name',
	// 	label       : 'Middle Name',
	// 	type        : 'input',
	// 	placeholder : 'Middle Name',
	// },
	// {
	// 	name        : 'last_name',
	// 	label       : 'Last Name',
	// 	type        : 'input',
	// 	placeholder : 'Last Name',
	// },
	{
		name                  : 'date_of_birth',
		label                 : 'Date of Birth',
		type                  : 'date-select',
		placeholder           : 'DD/MM/YYYY',
		isPreviousDaysAllowed : true,
		rules                 : { required: 'This is required' },
	},
	{
		name                  : 'date_of_joining',
		label                 : 'Date of Joining',
		type                  : 'date-select',
		placeholder           : 'DD/MM/YYYY',
		isPreviousDaysAllowed : true,
		rules                 : { required: 'This is required' },
	},
	{
		name                  : 'created_at',
		label                 : 'Date of Creation',
		type                  : 'date-select',
		placeholder           : 'DD/MM/YYYY',
		isPreviousDaysAllowed : true,
		rules                 : { required: 'This is required' },
	},
	{
		name                  : 'updated_at',
		label                 : 'Last Updated',
		type                  : 'date-select',
		placeholder           : 'DD/MM/YYYY',
		isPreviousDaysAllowed : true,
		rules                 : { required: 'This is required' },
	},
	{
		name        : 'employee_code',
		label       : 'Employee Code',
		type        : 'input',
		placeholder : 'Employee Code',
		rules       : { required: 'This is required' },
	},
	{
		name        : 'designation',
		label       : 'Employee Designation',
		type        : 'input',
		placeholder : 'Employee Designation',
		rules       : { required: 'This is required' },
	},
	{
		name        : 'gender',
		label       : 'Gender',
		type        : 'select',
		placeholder : 'Select Gender',
		rules       : { required: 'This is required' },
		options     : [
			{ label: 'Male', value: 'male' },
			{ label: 'Female', value: 'female' },
		],
	},
	{
		name        : 'mobile_number',
		label       : 'Phone Number',
		type        : 'mobilenumber',
		placeholder : 'Mobile',
		rules       : { required: 'This is required' },
	},
	{
		name        : 'personal_email',
		label       : 'Personal Email Id',
		type        : 'email',
		placeholder : 'Email',
		rules       : { required: 'This is required' },
	},
	{
		name  : 'photo',
		label : 'Passport Size Photograph',
		type  : 'fileUpload',
		// rules : { required: 'This is required' },
	},
	{
		name        : 'emergency_num',
		label       : 'Emergency Contact Number',
		type        : 'mobilenumber',
		placeholder : 'Emergency Contact Number',
		// rules       : { required: 'This is required' },
	},
	{
		name        : 'address',
		label       : 'Address',
		type        : 'textarea',
		placeholder : 'Address',
		// rules       : { required: 'This is required' },
	},
	{
		name        : 'cogoport_email',
		label       : 'Cogoport Email',
		type        : 'email',
		placeholder : 'Cogoport Email Id',
		// rules       : { required: 'This is required' },
	},
	{
		name        : 'hiring_manager',
		label       : 'Hiring Manager',
		type        : 'input',
		placeholder : 'Hiring Manager Name',
		// rules       : { required: 'This is required' },
	},
	{
		name        : 'hiring_manager_email',
		label       : 'Hiring Manager Email',
		type        : 'email',
		placeholder : 'Hiring Manager Email Id',
		// rules       : { required: 'This is required' },
	},
]);

export default controls;
