export const footerValues = [
	'COPY 12(FOR CUSTOMS)',
	'COPY 11(EXTRA COPY FOR CARRIER)',
	'COPY 10(EXTRA COPY FOR CARRIER)',
	'COPY 9(FOR AGENT)',
	'COPY 8(FOR FIRST CARRIER)',
	'COPY 7(FOR SECOND CARRIER)',
	'COPY 6(FOR THIRD CARRIER)',
	'COPY 5(FOR AIRPORT OF DESTINATION)',
	'COPY 4(DELIVERY RECEIPT)',
	'ORIGINAL 3 (FOR SHIPPER)',
	'ORIGINAL 2 (FOR CONSIGNEE)',
	'ORIGINAL 1 (FOR ISSUING CARRIER)',
];
