const getAirCustomscontrols = () => [
	{
		name        : 'airport_id',
		type        : 'async_select',
		label       : 'Airport',
		asyncKey    : 'list_locations',
		style       : { width: 350 },
		placeholder : 'Select Airport',
		params      : { filters: { type: ['airport'] } },
		span        : 12,
		isClearable : true,
		size        : 'sm',
	},
	{
		name        : 'country_id',
		label       : 'Country',
		type        : 'async_select',
		asyncKey    : 'list_locations',
		placeholder : 'Select country',
		style       : { width: 350 },
		params      : { filters: { type: ['country'], status: 'active' } },
		span        : 12,
		isClearable : true,
		size        : 'sm',
	},

	{
		name        : 'service_provider_id',
		type        : 'async_select',
		label       : 'Service Provider',
		placeholder : 'Select Service Provider',
		asyncKey    : 'organizations',
		span        : 12,
		style       : { width: 350 },
		isClearable : true,
		size        : 'sm',
	},
	{
		name        : 'trade_type',
		label       : 'Trade type',
		type        : 'select',
		placeholder : 'Select Trade type',
		options     : [{ value: 'import', label: 'IMPORT' }, { value: 'export', label: 'EXPORT' }],
		span        : 12,
		style       : { width: 350 },
		isClearable : true,
		size        : 'sm',
	},
	{
		name        : 'rate_type',
		label       : 'Rate Type',
		type        : 'select',
		placeholder : 'Select Rate type',
		options     : [{ value: 'general', label: 'General Rate' },
			{ value: 'promotinal', label: 'Promotinal Rate' }, { value: 'consolidated', label: 'Consolidation Rate' }],
		span        : 12,
		isClearable : true,
		style       : { width: 350 },
		size        : 'sm',
	},
];

export default getAirCustomscontrols;
