import {
	where,
} from 'firebase/firestore';

function getSupplySessionQuery({ sessionType, isContactsSelected = false }) {
	return isContactsSelected
		? [where('session_type', 'in', ['bot', 'admin'])] : [where('session_type', '==', sessionType)];
}

export const VIEW_TYPE_GLOBAL_MAPPING = {
	sales: {
		all_chats_base_query      : ({ agentId }) => [where('support_agent_id', '==', agentId)],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		session_type_query        : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access      : ['all', 'observer'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : false,
			bot_message_toggle          : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : true,
			has_group_access            : false,
			can_message_on_bot_session  : false,
			has_permission_to_edit      : false,
		},
	},
	sales_admin: {
		all_chats_base_query   : () => [where('agent_type', '==', 'sales')],
		group_chats_query      : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		session_type_query     : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access   : ['all', 'teams'],
		accesible_filters      : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : false,
			bot_message_toggle          : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : false,
			has_group_access            : false,
			can_message_on_bot_session  : false,
			has_permission_to_edit      : true,
		},
	},
	support: {
		all_chats_base_query      : ({ agentId }) => [where('support_agent_id', '==', agentId)],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		contacts_base_query       : () => [where('user_details.account_type', '==', 'service_provider')],
		session_type_query        : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access      : ['all', 'observer'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : false,
			bot_message_toggle          : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : true,
			toggle_agent_status         : false,
			toggle_self_status          : true,
			has_group_access            : false,
			can_message_on_bot_session  : false,
			has_permission_to_edit      : false,
		},
	},
	support_admin: {
		all_chats_base_query   : () => [where('agent_type', '==', 'support')],
		group_chats_query      : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		session_type_query     : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access   : ['all', 'teams'],
		accesible_filters      : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : false,
			bot_message_toggle          : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : true,
			toggle_agent_status         : false,
			toggle_self_status          : false,
			has_group_access            : false,
			can_message_on_bot_session  : false,
			has_permission_to_edit      : true,
		},
	},
	supply: {
		all_chats_base_query      : ({ agentId }) => [where('support_agent_id', '==', agentId)],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		contacts_base_query       : () => [where('user_details.account_type', '==', 'service_provider')],
		session_type_query        : getSupplySessionQuery,
		chat_sub_tabs_access      : ['all', 'groups', 'teams', 'observer', 'contacts'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
			contacts : ['chat_tags'],
		},
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : false,
			bot_message_toggle          : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : true,
			toggle_agent_status         : false,
			toggle_self_status          : true,
			has_group_access            : true,
			can_message_on_bot_session  : false,
			has_permission_to_edit      : false,
		},
	},
	supply_admin: {
		all_chats_base_query   : () => [where('agent_type', '==', 'supply')],
		group_chats_query      : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		contacts_base_query    : () => [where('user_details.account_type', '==', 'service_provider')],
		session_type_query     : getSupplySessionQuery,
		chat_sub_tabs_access   : ['all', 'groups', 'teams', 'contacts'],
		accesible_filters      : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
			contacts : ['chat_tags'],
		},
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : false,
			bot_message_toggle          : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : false,
			has_group_access            : true,
			can_message_on_bot_session  : false,
			has_permission_to_edit      : true,
		},
	},
	shipment_view: {
		all_chats_base_query       : ({ agentId }) => [where('booking_agent_ids', 'array-contains', agentId)],
		session_type_query         : () => [where('session_type', 'in', ['bot', 'admin'])],
		chat_sub_tabs_access       : ['all'],
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : false,
			bot_message_toggle          : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : true,
			has_group_access            : true,
			can_message_on_bot_session  : true,
			has_permission_to_edit      : true,
		},
	},
	cogoone_admin: {
		group_chats_query      : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		session_type_query     : getSupplySessionQuery,
		chat_sub_tabs_access   : ['all', 'groups', 'contacts'],
		accesible_filters      : {
			all      : ['15_min_filter', 'assigned_to', 'assigned_agent', 'chat_tags'],
			contacts : ['chat_tags'],
		},
		extra_side_bar_navs_access : [],
		permissions                : {
			auto_assign                 : true,
			bot_message_toggle          : true,
			organization_users_contacts : true,
			bulk_auto_assign            : true,
			claim_chats                 : true,
			toggle_agent_status         : true,
			toggle_self_status          : false,
			has_group_access            : true,
			can_message_on_bot_session  : false,
			has_permission_to_edit      : true,
		},
	},
};
