declare module '@cogoport/request';
declare module '@cogoport/store';
declare module '@cogoport/layout';
declare module '@cogoport/utils';
declare module '@cogoport/components';
declare module '@cogoport/next';
declare module '@cogoport/forms';
declare module '@cogoport/business-finance/page-components/TranslateAr';
declare module '@cogoport/business-finance/page-components/IncidentManagement'
declare module '@cogoport/business-finance/page-components/Reports';
