export const controls = [
	{
		name        : 'account_holder_name',
		label       : 'Account Holder Name',
		type        : 'text',
		style       : { flexBasis: '30%', width: '360px' },
		placeholder : 'Enter Account Holder Name',
		rules       : { required: 'Account Holder Name is required' },
	},
	{
		name        : 'account_number',
		label       : 'Account Number',
		type        : 'text',
		style       : { flexBasis: '30%', width: '360px' },
		placeholder : 'Enter Account Number',
		rules       : { required: 'Tax Number is Required' },
	},
	{
		name    : 'account_type',
		label   : 'Account Type',
		type    : 'select',
		style   : { flexBasis: '30%', width: '360px' },
		options : [
			{ label: 'Savings', value: 'savings' },
			{ label: 'Current', value: 'current' }],
		placeholder : 'Select Account Type',
		rules       : { required: 'Account Type is required' },
	},
	{
		name        : 'ifsc_code',
		label       : 'IFSC Code',
		type        : 'text',
		style       : { flexBasis: '30%', width: '360px' },
		maxLength   : 11,
		placeholder : 'Select Organization Type',
		rules       : { required: 'Organization Type is required' },
	},
	{
		name        : 'bank_name',
		label       : 'Bank Name',
		disabled    : true,
		style       : { flexBasis: '30%', width: '360px' },
		placeholder : 'Name of the Bank',
		rules       : { required: 'Bank Name is required' },

	},
	{
		name        : 'branch_name',
		label       : 'Branch Name',
		disabled    : true,
		style       : { flexBasis: '30%', width: '360px' },
		placeholder : 'Type here to search',
		rules       : { required: 'Branch Name is required' },

	},
	{
		name            : 'bank_document_url',
		showLabel       : false,
		label           : 'Upload Cancelled Cheque or Passbook front page',
		type            : 'file',
		style           : { flexBasis: '100%', marginBottom: '36px' },
		themeType       : 'secondary',
		drag            : true,
		uploadIcon      : 'ic-upload',
		onlyURLOnChange : true,
		accept          : 'image/*',
		uploadType      : 'aws',
		rules           : { required: 'Bank document is required' },
	},
	{
		name        : 'name',
		label       : 'Billing Party Name',
		type        : 'text',
		style       : { flexBasis: '40%', width: '360px' },
		placeholder : 'Enter Billing Party Name',
		rules       : { required: 'Billing Party Name is required' },
	},
	{
		name        : 'pincode_id',
		label       : 'Pincode',
		type        : 'select',
		style       : { flexBasis: '40%', width: '360px' },
		placeholder : 'Select options',
		rules       : { required: 'Pincode is Required' },
	},
	{
		name        : 'address',
		label       : 'Address',
		type        : 'text',
		style       : { flexBasis: '40%', width: '360px' },
		placeholder : 'Enter Address',
		rules       : { required: 'Address is Required' },
	},
];
