export const controls = [
	{
		name        : 'account_holder_name',
		label       : 'Account Holder Name',
		type        : 'text',
		placeholder : 'Enter Account Holder Name',
		span        : '30%',
		rules       : { required: 'Account Holder Name is required' },
	},
	{
		name        : 'account_number',
		label       : 'Account Number',
		type        : 'text',
		placeholder : 'Enter Account Number',
		span        : '30%',
		rules       : { required: 'Tax Number is Required' },
	},
	{
		name    : 'account_type',
		label   : 'Account Type',
		type    : 'select',
		span    : '35%',
		options : [
			{ label: 'Savings', value: 'savings' },
			{ label: 'Current', value: 'current' }],
		placeholder : 'Select Account Type',
		rules       : { required: 'Account Type is required' },
	},
	{
		name        : 'ifsc_code',
		label       : 'IFSC Code',
		type        : 'text',
		span        : '30%',
		maxLength   : 11,
		placeholder : 'Select Organization Type',
		rules       : { required: 'Organization Type is required' },
	},
	{
		name        : 'branch_name',
		label       : 'Branch Name',
		span        : '30%',
		placeholder : 'Type here to search',
		rules       : { required: 'Branch Name is required' },

	},
	{
		name            : 'bank_document_url',
		showLabel       : false,
		label           : 'Upload Cancelled Cheque or Passbook front page',
		span            : '100%',
		type            : 'file',
		themeType       : 'secondary',
		drag            : true,
		uploadIcon      : 'ic-upload',
		onlyURLOnChange : true,
		accept          : 'image/*',
		uploadType      : 'aws',
	},
	{
		name        : 'name',
		label       : 'Billing Party Name',
		type        : 'text',
		placeholder : 'Enter Billing Party Name',
		span        : '40%',
		rules       : { required: 'Billing Party Name is required' },
	},
	{
		name        : 'pincode_id',
		label       : 'Pincode',
		type        : 'select',
		span        : '40%',
		placeholder : 'Select options',
		rules       : { message: 'Pincode is Required' },
	},
	{
		name        : 'address',
		label       : 'Address',
		type        : 'text',
		span        : '40%',
		placeholder : 'Enter Address',
		rules       : { message: 'Address is Required' },
	},
];
