const LINE_PARAMS = ({ status, operator_type }) => ({
	filters    : { operator_type, status },
	page_limit : 100,
	sort_by    : 'short_name',
	sort_type  : 'asc',
});

const createContracts = () => [
	{
		name        : 'contract_name',
		label       : 'Contract Name',
		type        : 'text',
		placeholder : 'Name of Contract',
		rules       : { required: 'Contract name is required' },
		span        : 10,
		showIn      : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
	},
	{
		name           : 'validity_start',
		label          : 'Validity starts at',
		type           : 'datepicker',
		withTimePicker : false,
		rules          : { required: 'Start date required' },
		placeholder    : 'Start Date ',
		span           : 5,
		showIn         : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
	},
	{
		name           : 'validity_end',
		label          : 'Validity ends at',
		type           : 'datepicker',
		withTimePicker : false,
		rules          : { required: 'End date required' },
		placeholder    : ' End Date',
		span           : 5,
		showIn         : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
	},
	{
		name        : 'max_containers_count',
		label       : 'Container Count',
		type        : 'number',
		placeholder : 'Count',
		rules       : {
			required : 'Container count is required',
			min      : 50,
		},
		span   : 4,
		showIn : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
	},
	{
		name      : 'max_volume',
		label     : 'Maximum Volume',
		type      : 'number',
		className : 'primary lg',
		rules     : { required: 'Maximum volume is required', min: 50 },
		span      : 4,
		showIn    : ['air_frieght', 'lcl_frieght'],
	},
	{
		name      : 'max_weight',
		label     : 'Maximum Weight',
		type      : 'number',
		className : 'primary lg',
		rules     : { required: 'Maximum weight is required', min: 50 },
		span      : 4,
		showIn    : ['air_frieght', 'lcl_frieght'],
	},
	{
		name        : 'preferred_shipping_line_ids',
		label       : 'Preferred Shipping Line (Optional)',
		type        : 'async-select',
		asyncKey    : 'list_operators',
		initialCall : true,
		params      : LINE_PARAMS({
			status        : 'active',
			operator_type : 'shipping_line',
		}),
		defaultOptions : true,
		className      : 'primary lg',
		labelKey       : 'short_name',
		isClearable    : true,
		caret          : false,
		multiple       : true,
		span           : 4,
		showIn         : ['fcl_freight'],
	},
	{
		name        : 'preferred_airline_line_ids',
		label       : 'Prefered Airline line',
		type        : 'async-select',
		asyncKey    : 'list_operators',
		initialCall : true,
		params      : LINE_PARAMS({
			status        : 'active',
			operator_type : 'airline',
		}),
		defaultOptions : true,
		className      : 'primary lg',
		labelKey       : 'short_name',
		isClearable    : true,
		caret          : false,
		multiple       : true,
		theme          : 'admin',
		span           : 4,
		showIn         : ['air_frieght'],
	},
	{
		name           : 'exclude_airline_ids',
		label          : 'Unprefered Airline line',
		type           : 'async-select',
		asyncKey       : 'list_operators',
		initialCall    : true,
		labelKey       : 'short_name',
		defaultOptions : false,
		params         : LINE_PARAMS({
			status        : 'inactive',
			operator_type : 'shipping_line',
		}),
		isClearable : true,
		multiple    : true,
		theme       : 'admin',
		span        : 4,
		showIn      : ['air_freight'],
	},
	{
		name           : 'exclude_shipping_line_ids',
		label          : 'Exclude Shipping Line (Optional)',
		type           : 'async-select',
		asyncKey       : 'list_operators',
		initialCall    : true,
		className      : 'primary lg shipping-line',
		labelKey       : 'short_name',
		defaultOptions : false,
		params         : LINE_PARAMS({
			status        : 'inactive',
			operator_type : 'shipping_line',
		}),
		isClearable : true,
		multiple    : true,
		theme       : 'admin',
		span        : 4,
		showIn      : ['fcl_freight'],
	},
];

export default createContracts;
