const LINE_PARAMS = ({ status, operator_type }) => ({
	filters    : { operator_type, status },
	page_limit : 100,
	sort_by    : 'short_name',
	sort_type  : 'asc',
});

const createContracts = () => [
	{
		name        : 'contract_name',
		label       : 'Contract Name',
		type        : 'text',
		placeholder : 'Name of Contract',
		span        : 10,
		showIn      : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
		rules       : { required: 'Contract name is required' },
	},
	{
		name        : 'validity_start',
		label       : 'Validity starts at',
		type        : 'datepicker',
		placeholder : 'Start Date ',
		span        : 5,
		showIn      : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
		rules       : { required: 'Start date required' },
	},
	{
		name                  : 'validity_end',
		label                 : 'Validity ends at',
		type                  : 'datepicker',
		placeholder           : ' End Date',
		isPreviousDaysAllowed : true,
		span                  : 5,
		showIn                : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
		rules                 : { required: 'End date required' },
	},
	{
		name        : 'max_containers_count',
		label       : 'Container Count',
		type        : 'number',
		placeholder : 'Count',
		span        : 4,
		showIn      : ['fcl_freight', 'air_frieght', 'lcl_frieght'],
		rules       : { required: 'Container count is required', min: 50 },
	},
	{
		name   : 'max_volume',
		label  : 'Maximum Volume',
		type   : 'number',
		span   : 4,
		showIn : ['air_frieght', 'lcl_frieght'],
		rules  : { required: 'Maximum volume is required', min: 50 },
	},
	{
		name   : 'max_weight',
		label  : 'Maximum Weight',
		type   : 'number',
		span   : 4,
		showIn : ['air_frieght', 'lcl_frieght'],
		rules  : { required: 'Maximum weight is required', min: 50 },
	},
	{
		name        : 'preferred_shipping_line_ids',
		label       : 'Preferred Shipping Line (Optional)',
		type        : 'async-select',
		asyncKey    : 'list_operators',
		initialCall : true,
		params      : LINE_PARAMS({
			status        : 'active',
			operator_type : 'shipping_line',
		}),
		defaultOptions : true,
		labelKey       : 'short_name',
		isClearable    : true,
		caret          : false,
		multiple       : true,
		span           : 4,
		showIn         : ['fcl_freight'],
	},
	{
		name        : 'preferred_airline_line_ids',
		label       : 'Prefered Airline line',
		type        : 'async-select',
		asyncKey    : 'list_operators',
		initialCall : true,
		params      : LINE_PARAMS({
			status        : 'active',
			operator_type : 'airline',
		}),
		defaultOptions : true,
		labelKey       : 'short_name',
		isClearable    : true,
		caret          : false,
		multiple       : true,
		theme          : 'admin',
		span           : 4,
		showIn         : ['air_frieght'],
	},
	{
		name           : 'exclude_airline_ids',
		label          : 'Unprefered Airline line',
		type           : 'async-select',
		asyncKey       : 'list_operators',
		initialCall    : true,
		labelKey       : 'short_name',
		defaultOptions : false,
		params         : LINE_PARAMS({
			status        : 'inactive',
			operator_type : 'shipping_line',
		}),
		isClearable : true,
		multiple    : true,
		span        : 4,
		showIn      : ['air_freight'],
	},
	{
		name           : 'exclude_shipping_line_ids',
		label          : 'Exclude Shipping Line (Optional)',
		type           : 'async-select',
		asyncKey       : 'list_operators',
		initialCall    : true,
		className      : 'primary lg shipping-line',
		labelKey       : 'short_name',
		defaultOptions : false,
		params         : LINE_PARAMS({
			status        : 'inactive',
			operator_type : 'shipping_line',
		}),
		isClearable : true,
		multiple    : true,
		span        : 4,
		showIn      : ['fcl_freight'],
	},
];

export default createContracts;
