const globalViewKeys = {
	spot_booking             : 'performed_by_id',
	spot_searches            : 'performed_by_id',
	enquiries                : 'performed_by_id',
	quotations               : 'performed_by_id',
	sales_organizations      : 'agent_id',
	supply_organizations     : 'agent_id',
	sales_shipments          : 'agent_id',
	margins                  : 'agent_id',
	supply_enquiries         : 'supply_agent_ids',
	supply_shipments         : 'supply_agent_id',
	services                 : 'service_ops_id',
	overdue                  : 'booking_agent_id',
	documents                : 'booking_agent_id',
	upcoming_shipments       : 'booking_agent_id',
	okam_booking             : 'booking_agent_id',
	okam_booking_procurement : 'booking_agent_id',
};

const globalTimeKeys = {
	spot_booking: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	spot_searches: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	enquiries: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	quotations: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	sales_organizations: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	supply_organizations: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	sales_shipments: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	margins: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	supply_enquiries: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	supply_shipments: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	services: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	overdue: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	documents: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	upcoming_shipments: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	okam_booking: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
	okam_booking_procurement: {
		endDate   : 'created_at_less_than',
		startDate : 'created_at_greater_than',
	},
};

const globalServiceKeys = {
	spot_booking             : 'primary_service',
	spot_searches            : 'search_type',
	enquiries                : 'search_type',
	quotations               : 'primary_service',
	sales_shipments          : 'shipment_type',
	supply_enquiries         : 'service',
	supply_shipments         : 'shipment_type',
	upcoming_shipments       : 'shipment_type',
	okam_booking             : 'shipment_type',
	okam_booking_procurement : 'shipment_type',
	margins                  : 'service',
};

const serviceTypeLocationKeys = {
	seaport : { origin: 'origin_port_id', destination: 'destination_port_id' },
	airport : {
		origin      : 'origin_airport_id',
		destination : 'destination_airport_id',
	},
	trade   : { origin: 'origin_trade_id', destination: 'destination_trade_id' },
	country : {
		origin      : 'origin_country_id',
		destination : 'destination_country_id',
	},
	continent: {
		origin      : 'origin_continent_id',
		destination : 'destination_continent_id',
	},
};

const serviceTypeKeys = {
	fcl_freight : ['seaport', 'trade', 'continent', 'country'],
	lcl_freight : ['seaport', 'trade', 'continent', 'country'],
	air_freight : ['airport', 'trade', 'continent', 'country'],
};

const MANDATORY_TASK_LIST = [
	'update_contact_status_with_shipper',
	'update_bl_type',
	'update_commodity_name_hs_code_description',
	'update_origin_cargo_handling_type',
	'update_destination_cargo_handling_type',
	'update_cargo_readiness_date',
	'upload_msds_certificate',
	'upload_iip_certificate',
	'update_payment_term',
	'update_preferred_container_pickup_location',
	'update_preferred_container_handover_location',
	'mark_confirmed',
	'upload_invoice',
	'upload_si',
	'update_ftl_origin_pickup_details',
	'mark_completed',
	'upload_packing_list',
	'update_ftl_origin_pickup_date_and_time',
	'upload_booking_proof',
	'get_mypacco_origin_details',
	'get_mypacco_destination_details',
	'get_quicargo_origin_details',
	'get_quicargo_destination_details',
	'update_ltl_origin_volume',
	'update_ltl_destination_volume',
	'update_ltl_origin_pickup_details',
	'update_ftl_destination_pickup_details',
	'update_ltl_destination_pickup_details',
	'upload_commercial_invoice',
	'update_airway_bill_type',
	'upload_dangerous_cargo_declaration',
	'update_cargo_picked_up_date',
	'update_cargo_clearance_date',
	'upload_airway_bill_instruction',
	'update_cargo_pickup_date_and_time',
	'mark_in_progress',
	'update_ftl_pickup_drop_details',
	'get_mypacco_details',
	'get_quicargo_details',
	'update_ltl_pickup_drop_details',
	'upload_t1_document',
	'upload_import_safety_and_security_declaration',
	'update_destination_transport_poc_details',
	'upload_booking_note',
	'update_shipping_bill_number',
	'mark_container_stuffed',
	'update_si_filed_at',
	'upload_shipping_bill',
	'upload_loading_report',
	'upload_draft_bill_of_lading',
	'update_container_details',
	'mark_container_picked_up',
	'mark_container_gated_in',
	'mark_vessel_departed',
	'upload_bill_of_lading',
	'upload_container_arrival_notice',
	'release_bill_of_lading',
	'upload_igm_document',
	'mark_vessel_arrived',
	'upload_delivery_order_noc',
	'upload_delivery_order',
	'mark_container_gated_out',
	'mark_containers_on_the_way_to_cfs',
	'update_container_destuffed_at_cfs',
	'mark_cargo_picked_up',
	'mark_cargo_dropped',
	'upload_checklist',
	'upload_boe_checklist',
	'upload_bill_of_entry',
	'mark_customs_cleared',
	'update_billing_address',
	'mark_container_reached_factory',
	'mark_container_arrived_at_port',
	'mark_container_delivered_at_destination',
	'update_empty_container_returned_at',
	'mark_container_arrived',
	'mark_container_arrived_at_destination_icd',
	'update_console_points',
	'update_carrier_booking_reference_number',
	'upload_carting_order',
	'update_cargo_picked_up_at',
	'update_cargo_arrived_at_origin_cfs',
	'mark_cargo_carted_in',
	'upload_measurement_slip',
	'mark_cargo_stuffed',
	'mark_vessel_departure_status',
	'mark_vessel_arrival_status',
	'mark_cargo_handed_over',
	'update_export_billing_address',
	'update_import_billing_address',
	'upload_draft_airway_bill',
	'mark_cargo_handed_over_at_origin',
	'upload_airway_bill',
	'update_airway_bill_filed_at',
	'upload_manifest_copy',
	'mark_flight_departed',
	'update_manifest_filed_at',
	'update_ams_filed_at',
	'mark_flight_arrived',
	'update_delivery_order_posted_at',
	'mark_cargo_handed_over_at_destination',
	'review_proforma_invoices',
];

const AIR_STANDARD_VOLUMETRIC_WEIGHT_CONVERSION_RATIO = 166.67;

export {
	globalViewKeys,
	globalTimeKeys,
	globalServiceKeys,
	serviceTypeLocationKeys,
	serviceTypeKeys,
	MANDATORY_TASK_LIST,
	AIR_STANDARD_VOLUMETRIC_WEIGHT_CONVERSION_RATIO,
};
