export { default as ControlCenter } from './page-components/ControlCenter';
export { default as FAQs } from './page-components/FAQs';
export { default as ConfigurationEngine } from './page-components/ControlCenter/ConfigurationEngine';
export { default as Upload } from './page-components/ControlCenter/Upload';
export { default as Question } from './page-components/ControlCenter/Question';
export { default as AnswerPage } from './page-components/FAQs/page-components/AnswerPage';
export { default as Announcements } from './page-components/Announcements';
export { default as UserDashboard } from './page-components/UserDashboard';
export { default as CreateCourse } from './page-components/CreateCourse';
