export const amountCollectionFilters = ({ accMode }) => [
	{
		name        : 'accMode',
		type        : 'select',
		placeholder : 'Account Mode',
		size        : 'sm',
		value       : accMode,
		options     : [
			{ label: 'AR', value: 'AR' },
			{ label: 'AP', value: 'AP' },
			{ label: 'CSD', value: 'CSD' },
			{ label: 'PDA', value: 'PDA' },
			{ label: 'LA', value: 'LA' },
			{ label: 'SUSA', value: 'SUSA' },
			{ label: 'SUSS', value: 'SUSS' },
			{ label: 'PC', value: 'PC' },
			{ label: 'EMD', value: 'EMD' },
			{ label: 'EMP', value: 'EMP' },
		],
		selectWidth: '150px',
	},
	{
		name                  : 'date',
		type                  : 'singleDateRange',
		placeholder           : 'Date',
		isPreviousDaysAllowed : true,
		maxDate               : new Date(),
		span                  : 3,
	},
];
