export const truckType = [
	{
		value         : 'open_body_pickup_1ton',
		type          : 'open',
		label         : 'Pickup (1 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_tata_ace_750_800kgs',
		type          : 'open',
		label         : 'Tata Ace (750-800 kgs)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_tata_407_2.5ton',
		type          : 'open',
		label         : 'Tata 407 (2.5 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_LCV_14ft_4ton',
		type          : 'open',
		label         : 'LCV (14ft) (4 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_LCV_17ft_5ton',
		type          : 'open',
		label         : 'LCV (17 ft) (5 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_LCV_19ft_7ton',
		type          : 'open',
		label         : 'LCV (19ft) (7 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_6tyre_19_24ft_9ton',
		type          : 'open',
		label         : '6 tyre (19-24 ft) (9 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_6tyre_12ton',
		type          : 'open',
		label         : '6 tyre (12 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_10tyre_taurus_22ft_16ton',
		type          : 'open',
		label         : '10 tyre Taurus 22ft (16 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_10tyre_18ton',
		type          : 'open',
		label         : '10 tyre (18 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_12tyre_taurus_22ft_22ton',
		type          : 'open',
		label         : '12 tyre Taurus 22 ft (22 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_12tyre_24ton',
		type          : 'open',
		label         : '12 tyre (24 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_12tyre_taurus_24ft_25ton',
		type          : 'open',
		label         : '12 tyre Taurus 24 ft (25 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_14tyre_taurus_22ft_26ton',
		type          : 'open',
		label         : '14 tyre Taurus 22ft (26 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_16tyre_32ton',
		type          : 'open',
		label         : '16 tyre (32 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_16tyre_35ton',
		type          : 'open',
		label         : '16 tyre (35 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_14tyre_taurus_25ft_26ton',
		type          : 'open',
		label         : '14 tyre Taurus 25ft (26 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_14tyre_30ton',
		type          : 'open',
		label         : '14 tyre (30 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_18tyre_28ton',
		type          : 'open',
		label         : '18 tyre (28 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_18tyre_42ton',
		type          : 'open',
		label         : '18 tyre (42 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_18tyre_34ton',
		type          : 'open',
		label         : '18 tyre (34 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_22tyre_35ton',
		type          : 'open',
		label         : '22 tyre (35 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_7.5ton',
		type          : 'open',
		label         : 'Truck (7.5 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_15ton',
		type          : 'open',
		label         : 'Truck (15 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_18.5ton',
		type          : 'open',
		label         : 'Truck (18.5 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_20ton',
		type          : 'open',
		label         : 'Truck (20 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_21ton',
		type          : 'open',
		label         : 'Truck (21 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_27ton',
		type          : 'open',
		label         : 'Truck (27 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_29ton',
		type          : 'open',
		label         : 'Truck (29 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_body_33ton',
		type          : 'open',
		label         : 'Truck (33 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_40ft_flat_bed_trailor_20_25ton',
		type          : 'open',
		label         : '40ft Flat Bed Trailor (20-25 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_40ft_semi_low_bed_trailor_20_25ton',
		type          : 'open',
		label         : '40ft Semi Low Bed Trailor (20-25 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'open_40ft_low_bed_trailor_20_25_30ton',
		type          : 'open',
		label         : '40ft Low Bed Trailor (20-25-30 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_7.5ton',
		type          : 'closed',
		label         : 'Truck (7.5 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_9ton',
		type          : 'closed',
		label         : 'Truck (9 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_25ton',
		type          : 'closed',
		label         : 'Truck (25 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_30ton',
		type          : 'closed',
		label         : 'Truck (30 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_LCV_14ft_3.5ton',
		type          : 'closed',
		label         : 'LCV (14ft) (3.5 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_LCV_17ft_5ton',
		type          : 'closed',
		label         : 'LCV (17 ft) (5 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_LCV_19ft_7ton',
		type          : 'closed',
		label         : 'LCV (19ft) (7 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_32ft_single_axle_7ton',
		type          : 'closed',
		label         : '32ft single axle (7 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_32ft_single_axle_HQ_7ton',
		type          : 'closed',
		label         : '32 ft single axle HQ (7 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_19_22ft_single_axle_7ton',
		type          : 'closed',
		label         : '19-22 ft single axle (7 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_24ft_single_axle_7ton',
		type          : 'closed',
		label         : '24 ft single axle (7 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_24ft_multi_axle_14_15_ton',
		type          : 'closed',
		label         : '24 ft single axle (7 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_32ft_multi_axle_HQ_14_15_ton',
		type          : 'closed',
		label         : '32 ft multi axle HQ (14-15 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_32ft_multi_axle_14_15_ton',
		type          : 'closed',
		label         : '32ft multi axle (14-15 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_32ft_triple_axle_20_21_ton',
		type          : 'closed',
		label         : '32ft triple axle (20-21 ton)',
		country_codes : ['IN', 'ALL'],
	},
	{
		value         : 'closed_body_32ft_triple_axle_HQ_20_21_ton',
		type          : 'closed',
		label         : '32 ft triple axle HQ (20-21 ton)',
		country_codes : ['IN', 'ALL'],
	},

	{
		value         : 'open_body_1_ton',
		type          : 'open',
		label         : '1 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_1.5_ton',
		type          : 'open',
		label         : '1.5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_2_ton',
		type          : 'open',
		label         : '2 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_2.5_ton',
		type          : 'open',
		label         : '2.5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_3.5_ton',
		type          : 'open',
		label         : '3.5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_5_ton',
		type          : 'open',
		label         : '5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_7_ton',
		type          : 'open',
		label         : '7 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_9_ton',
		type          : 'open',
		label         : '9 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_11_ton',
		type          : 'open',
		label         : '11 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_15_ton',
		type          : 'open',
		label         : '15 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'open_body_18_ton',
		type          : 'open',
		label         : '18 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},

	{
		value         : 'close_body_1_ton',
		type          : 'closed',
		label         : '1 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_1.5_ton',
		type          : 'closed',
		label         : '1.5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_2_ton',
		type          : 'closed',
		label         : '2 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_2.5_ton',
		type          : 'closed',
		label         : '2.5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_3.5_ton',
		type          : 'closed',
		label         : '3.5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_5_ton',
		type          : 'closed',
		label         : '5 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_7_ton',
		type          : 'closed',
		label         : '7 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_9_ton',
		type          : 'closed',
		label         : '9 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_11_ton',
		type          : 'closed',
		label         : '11 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_15_ton',
		type          : 'closed',
		label         : '15 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
	{
		value         : 'close_body_18_ton',
		type          : 'closed',
		label         : '18 Ton (Vietnam)',
		country_codes : ['VN', 'ALL'],
	},
];
