export const rawControls = ({ handleChange = () => {}, charge = {}, shipment_id = '' }) => ({
	type             : 'edit_service_charges',
	name             : charge.id,
	service_name     : charge.service_type,
	shipment_id,
	showHeader       : true,
	showButtons      : !['subsidiary_service'].includes(charge.service_type),
	showDeleteButton : true,
	value            : [
		{
			code     : '',
			currency : '',
			price    : '',
			quantity : '',
			unit     : '',
			total    : '',
		},
	],
	controls: [
		{
			label : `Truck Number ${charge.truck_number}`,
			type  : 'select',
			name  : 'code',
			span  : 3,
			handleChange,
		},
		{
			label          : 'Currency',
			name           : 'currency',
			type           : 'select',
			optionsListKey : 'currencies',
			span           : 1,
		},
		{
			label : 'Rate',
			name  : 'price',
			type  : 'number',
			span  : 2,
		},
		{
			label : 'Quantity',
			name  : 'quantity',
			type  : 'number',
			span  : 1,
		},
		{
			label   : 'Unit',
			type    : 'select',
			name    : 'unit',
			options : [
				{ label: 'Per container', value: 'per_container' },
				{ label: 'Per shipment', value: 'per_shipment' },
				{ label: 'Per BL', value: 'per_bl' },
				{ label: 'Per Kg', value: 'per_kg' },
				{ label: 'Per Km', value: 'per_km' },
				{ label: 'Per Truck', value: 'per_truck' },
				{ label: 'Per Awb', value: 'per_awb' },
				{ label: 'Percentage of Freight', value: 'percentage_of_freight' },
				{ label: 'Per Ton', value: 'per_ton' },
			],
			span: 2,
		},
		{
			label  : 'Amount',
			type   : 'static',
			name   : 'total',
			span   : 2,
			render : (item) => <p>{item?.total}</p>,
		},
	],
});
