const POC_PROCESS_MAPPING = {
	export: {
		order_placement                            : 'Order Placement',
		additional_information_for_booking         : 'Additional information for booking',
		approval_for_change_in_quoted_price        : 'Approval for change in Quoted Price',
		approval_for_change_in_shipping_line       : 'Approval for change in Shipping Line',
		booking_confirmation                       : 'Booking Confirmation',
		ci_pl_submission                           : 'CI & PL submission',
		factory_stuffing                           : 'Factory Stuffing',
		dock_or_icd_stuffing                       : 'Dock or ICD Stuffing',
		preferred_cha                              : 'Preferred CHA',
		checklist_amendment                        : 'Checklist amendment',
		checklist_approval                         : 'Checklist Approval',
		preferred_transporter                      : 'Preferred Transporter',
		location_information_and_time_confirmation : 'location_information_and_time_confirmation',
		e_waybill_filling                          : 'e_waybill_filling',
		cargo_pickup_handling                      : 'cargo_pickup_handling',
		vgm_declaration                            : 'vgm_declaration',
		si_filing                                  : 'si_filing',
		bl_draft_amendment                         : 'bl_draft_amendment',
		bl_draft_approval                          : 'bl_draft_approval',
		bl_do_release                              : 'BL Do Release',
		payment_method                             : 'Payment Method',
		payment_outstanding                        : 'Payment Outstanding',
		payment_done                               : 'Payment Done',
		origin_trailer_transportation              : 'Origin Trailer Transportation',
		origin_ftl_transportation                  : 'Origin FTL Transportation',
		origin_cfs                                 : 'Origin CFS',
		origin_custom_clearance                    : 'Origin Custom Clearance',
		destination_custom_clearance               : 'Destination Custom Clearance',
		destination_cfs                            : 'Destination CFS',
		destination_ftl_transportation             : 'Destination FTL Transportation',
		destination_trailer_transportation         : 'Destination Trailer Transportation',
	},

	import: {
		order_placement                        : 'Order Placement',
		additional_information                 : 'Additional information',
		approval_for_change_in_quoted_price    : 'Approval for change in Quoted Price',
		approval_for_change_in_shipping_line   : 'Approval for change in Shipping Line',
		booking_confirmation                   : 'Booking Confirmation',
		ci_pl_submission                       : 'CI & PL submission',
		draft_bl_approval                      : 'Draft BL Approval',
		dpd_non_dpd                            : 'DPD non DPD',
		preferred_cha                          : 'Preferred CHA',
		cfs_movement_type_dpd_non_dpd          : 'CFS Movement type - DPD / Non-DPD',
		cargo_arrival_notice                   : 'Cargo arrival notice',
		preferred_transporter                  : 'Preferred Transporter',
		preferred_cfs                          : 'Preferred CFS',
		specifications_for_freight_certificate : 'Specifications for Freight certificate',
		pre_alerts                             : 'Pre-alerts',
		payment_method                         : 'Payment Method',
		payment_outstanding                    : 'Payment Outstanding',
		origin_ftl_transportation              : 'Origin FTL Transportation',
		origin_ltl_transportation              : 'Origin LTL Transportation',
		origin_custom_clearance                : 'Origin Custom Clearance',
		destination_custom_clearance           : 'Destination Custom Clearance',
		destination_ftl_transportation         : 'Destination FTL Transportation',
		destination_ltl_transportation         : 'Destination LTL Transportation',
	},
};

export default POC_PROCESS_MAPPING;
