const DEFAULT_NORTHEAST_LAT = 90;
const DEFAULT_NORTHEAST_LNG = 200;
const DEFAULT_SOUTHWEST_LAT = -90;
const DEFAULT_SOUTHWEST_LNG = -200;

export {
	DEFAULT_NORTHEAST_LAT,
	DEFAULT_NORTHEAST_LNG,
	DEFAULT_SOUTHWEST_LAT,
	DEFAULT_SOUTHWEST_LNG,
};
