const getControls = ({ disabledButton = '' }) => [
	{
		name             : 'container_details',
		type             : 'fieldArray',
		showButtons      : false,
		showDeleteButton : false,
		value            : [],
		controls         : [
			{
				name : 'id',
				span : 0,
			},
			{
				name         : 'container_number',
				label        : 'Container Number',
				type         : 'text',
				span         : 2,
				showOptional : false,
				placeholder  : 'Container Number',
				disabled     : disabledButton,
			},
			{
				name         : 'consignment_number',
				label        : 'Consignment No.',
				type         : 'text',
				span         : 1.5,
				showOptional : false,
				placeholder  : 'Enter Number',
				disabled     : disabledButton,
			},
			{
				name         : 'consignment_date',
				label        : 'Consignment Date',
				type         : 'datepicker',
				span         : 1.5,
				showOptional : false,
				placeholder  : 'Select',
				disabled     : disabledButton,
			},
			{
				name         : 'commercial_invoice_number',
				label        : 'Commercial Invoice No.',
				type         : 'text',
				span         : 2,
				showOptional : false,
				placeholder  : 'Enter Invoice Number',
				disabled     : disabledButton,
			},
			{
				name         : 'packages_count',
				label        : 'Packages Count',
				type         : 'text',
				span         : 1.5,
				showOptional : false,
				placeholder  : 'Enter',
				disabled     : disabledButton,
			},
			{
				name         : 'eway_bill_number',
				label        : 'Eway Bill No.',
				type         : 'text',
				span         : 1.5,
				showOptional : false,
				placeholder  : 'Enter',
				disabled     : disabledButton,
			},
			{
				name           : 'ewb_validity',
				label          : 'Eway Bill Validity',
				type           : 'datepicker',
				withTimePicker : true,
				span           : 2,
				className      : 'primary lg validity',
				showOptional   : false,
				placeholder    : 'Enter',
				showTimeSelect : true,
				disabled       : disabledButton,
			},
			{
				name         : 'picked_up_at',
				label        : 'Picked Up At',
				type         : 'datepicker',
				span         : 2,
				className    : 'primary lg validity',
				showOptional : false,
				placeholder  : 'Select',
				disabled     : disabledButton,
			},
			{
				name         : 'gated_in_at',
				type         : 'datepicker',
				label        : 'Gated In',
				span         : 2,
				className    : 'primary lg validity',
				showOptional : false,
				placeholder  : 'Select',
				disabled     : disabledButton,
			},
			{
				name         : 'vessel_departed_at',
				label        : 'Container Departed',
				type         : 'datepicker',
				span         : 2,
				className    : 'primary lg validity',
				showOptional : false,
				placeholder  : 'Select',
				disabled     : disabledButton,
			},
			{
				name         : 'vessel_arrived_at',
				label        : 'Container Arrived',
				type         : 'datepicker',
				span         : 2,
				className    : 'primary lg validity',
				showOptional : false,
				placeholder  : 'Select',
				disabled     : disabledButton,
			},
			{
				name         : 'gated_out_at',
				label        : 'Gated Out',
				type         : 'datepicker',
				span         : 2,
				className    : 'primary lg validity',
				showOptional : false,
				placeholder  : 'Select',
				disabled     : disabledButton,
			},
			{
				name         : 'empty_container_returned_at',
				label        : 'Empty Container Returned',
				type         : 'datepicker',
				span         : 2,
				className    : 'primary lg validity',
				showOptional : false,
				placeholder  : 'Select',
				disabled     : disabledButton,
			},
		],
	},
];

export default getControls;
