/* eslint-disable max-lines-per-function */
// import { useRequest } from '@cogoport/request';
// import axios from 'axios';
// import { useEffect, useCallback } from 'react';

// const apiName = {
// 	fcl_freight : 'get_fcl_freight_rate_coverage_stats',
// 	ltl_freight : 'get_ltl_freight_rate_stats',
// 	lcl_freight : 'get_lcl_freight_rate_stats',
// 	air_freight : 'get_air_freight_rate_dashboard_stats',
// };

const useGetMostPredictedSpotRate = () => {
	// console.log('hit');
	// eslint-disable-next-line max-len
	// const res = axios.get('https://d754-103-143-39-118.ngrok.io/fcl_freight_rate/get_most_predicted_spot_search_rates?service=fcl_freight', { });
	// const dataPromise = res.then((promiseResult) => promiseResult.data);
	// console.log(res, 'dataPromise');

	// const [{ loading, data }, trigger] = useRequest({
	// 	url    : '/fcl_freight_rate/get_fcl_freight_rate_coverage_stats',
	// 	method : 'GET',
	// }, { manual: true });

	// const getStats = useCallback(async (filter = {}) => {
	// 	const finalFilter = Object.fromEntries(
	// 		Object.entries(filter).filter(([, value]) => value !== ''),
	// 	);
	// 	try {
	// 		await trigger({
	// 			params: { filters: { ...finalFilter }, service },
	// 		});
	// 	} catch (err) {
	// 		console.log(err);
	// 	}
	// }, [service, trigger]);

	// useEffect(() => {
	// 	getStats();
	// }, [getStats, service]);

	const spotsearchData = {
		list: [
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Sahnewal (GRFL) (INSGF), Ludhiana, India',
				destination_port : 'Sherman (US), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kaohsiung (TWKHH), Kaohsiung, Taiwan',
				destination_port : 'Savannah (US), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kaohsiung (TWKHH), Kaohsiung, Taiwan',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'London gateway port (GBLGP), London, United Kingdom',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bandar Abbas (IRBND), Bandar-e-Abbas, Iran',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bandar Abbas (IRBND), Bandar-e-Abbas, Iran',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bandar Abbas (IRBND), Bandar-e-Abbas, Iran',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bahrain (BHBAH), Bahrain, Meg',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Venice (Venezia) (ITVCE), Venice, Italy',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Penang (Georgetown) (MYPEN), George Town, Malaysia',
				destination_port : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Cochin (INCOK), Kochi, India',
				destination_port : 'HOUSTON (USHOU), Texas City, United States of America',
			},
			{
				container_size   : '40HC',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Cochin (INCOK), Kochi, India',
				destination_port : 'Caucedo (DOCAU), Santo Domingo, Dominican Republic',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Cochin (INCOK), Kochi, India',
				destination_port : 'Montreal-Dorval Apt (CA), Canada, North America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Aliaga (TRALI), Izmir, Turkey',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Ludhiana (INLUH), Ludhiana, India',
				destination_port : 'Jacksonville (USJAX), Jacksonville, United States of America',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD UDAIPUR (INUDA), Udaipur, India',
				destination_port : 'Savannah, Georgia (USSAV), Savannah, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				destination_port : 'Callao (PECLL), Callao, Peru',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Wuhu (CNWHI), Wuhu, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kandla (INIXY), Bhuj, India',
				destination_port : 'Monte Negro (BR), Brazil, Sam',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bangkok (PAT Terminal/Khlong Toei Terminal) (THBKK), Bangkok, Thailand',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bangkok (PAT Terminal/Khlong Toei Terminal) (THBKK), Bangkok, Thailand',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bangkok (PAT Terminal/Khlong Toei Terminal) (THBKK), Bangkok, Thailand',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'flat_rack',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Shanghai (CNSGH), Shanghai, China',
				destination_port : 'ICD Ludhiana (INLUH), Ludhiana, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shanghai (CNSGH), Shanghai, China',
				destination_port : 'ICD Jajpur, Jajpur, Jajapur',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shanghai (CNSGH), Shanghai, China',
				destination_port : 'ICD Jajpur, Jajpur, Jajapur',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shanghai (CNSGH), Shanghai, China',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shanghai (CNSGH), Shanghai, China',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shanghai (CNSGH), Shanghai, China',
				destination_port : 'Vizag (INVIZ), Vishakhapatnam, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Semarang (IDSRG), Semarang, Indonesia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'flammable_solids-4.1',
				origin_port      : 'Tuticorin (INTUT), Tuticorin, India',
				destination_port : 'Port Sudan (SDPZU), Port Sudan, Sudan',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tuticorin (INTUT), Tuticorin, India',
				destination_port : 'Port Sudan (SDPZU), Port Sudan, Sudan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tuticorin (INTUT), Tuticorin, India',
				destination_port : 'Gdynia (PLGDY), Gdynia, Poland',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'flammable_solids-4.1',
				origin_port      : 'Tuticorin (INTUT), Tuticorin, India',
				destination_port : 'Chittagong (BDCGP), Chittagong, Bangladesh',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vancouver (CAVAN), Vancouver, Canada',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vancouver (CAVAN), Vancouver, Canada',
				destination_port : 'Cat Lai (VNCLI), Ho Chi Minh City, Vietnam',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Casablanca (MACAS), Casablanca, Morocco',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Algiers (DZALG), Algiers, Algeria',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Liverpool (GBLIV), Liverpool, United Kingdom',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Port Chicago , Illinois (USPZH), Chicago, United States of America',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Port Chicago , Illinois (USPZH), Chicago, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Alexandria (EGALY), Alexandria, Egypt',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Mombasa (KEMBA), Mombasa, Kenya',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Novorossiysk (RUNVS), Novorossiysk, Russia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Aqaba (JOAQJ), Al Aqabah, Jordan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'sugar_rice',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Port Louis (MUPLU), Port Louis, Mauritius',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Barcelona (ESBCN), Barcelona, Spain',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Toronto (CATOR), Toronto, Canada',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Zanzibar (TZZNZ), Zanzibar, Tanzania',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Rotterdam (NLRTM), Rotterdam, Netherlands',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Benghazi (LYBEN), Libya, Med',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Apapa (Lagos) (NGAPP), Lagos, Nigeria',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Apapa (Lagos) (NGAPP), Lagos, Nigeria',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Valencia (ESVLC), Valencia, Spain',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Tanjung Pelepas (MYTPP), Malaysia, Asia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Nanjing (CNNJG), Nanjing, China',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chennai (INMAA), Chennai, India',
				destination_port : 'Misurata (LYMRA), Misratah, Libya',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagoya (JPNGO), Nagoya, Japan',
				destination_port : 'ICD Tihi, Indore, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagoya (JPNGO), Nagoya, Japan',
				destination_port : 'Kathuwas, Rajasthan (INCML), Alwar, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagoya (JPNGO), Nagoya, Japan',
				destination_port : 'ICD Panki (JRY) (INKNU), Kanpur, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagoya (JPNGO), Nagoya, Japan',
				destination_port : 'Pipavav (Victor) Port (INPAV), Bhavnagar, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagoya (JPNGO), Nagoya, Japan',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Cebu (PHCEB), Cebu, Philippines',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Lianyungang (CNLYG), Lianyungang, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'HOUSTON (USHOU), Texas City, United States of America',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dammam (SADMM), Ad Dammam, Saudi Arabia',
				destination_port : 'Hodeidah (YEHOD), Al Hudaydah, Yemen',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dammam (SADMM), Ad Dammam, Saudi Arabia',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jakarta(Tanjung Priok) (IDJKT), Jakarta, Indonesia',
				destination_port : 'Beirut (LBBEY), Beirut, Lebanon',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jakarta(Tanjung Priok) (IDJKT), Jakarta, Indonesia',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jakarta(Tanjung Priok) (IDJKT), Jakarta, Indonesia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Sepang, Selangor (MY), Malaysia, Asia',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagpur (ICD|CFS|SEZ) (INNAG), Nagpur, Maharashtra',
				destination_port : 'Ashdod (ILASH), Ashdod, Israel',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagpur (ICD|CFS|SEZ) (INNAG), Nagpur, Maharashtra',
				destination_port : 'Cotonou (BJCOO), Cotonou, Benin',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nagpur (ICD|CFS|SEZ) (INNAG), Nagpur, Maharashtra',
				destination_port : 'Novorossiysk (RUNVS), Novorossiysk, Russia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Beijiao (CNBIJ), Foshan, China',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mersin (TRMER), Turkey, Med',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Xingang (CNXGA), Tianjin, China',
				destination_port : 'ICD Whitefield Terminal , Bangalore (Bengaluru) (INBLR), Banglore, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Xingang (CNXGA), Tianjin, China',
				destination_port : 'Vizag (INVIZ), Vishakhapatnam, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Xingang (CNXGA), Tianjin, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan New Port (KRBNP), Busan, South Korea',
				destination_port : 'TUMB (INTMB), Valsad, Gujarat, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Taichung (TWTXG), Taichung, Taiwan',
				destination_port : 'ICD Sahnewal (GRFL) (INSGF), Ludhiana, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shenzhen (CNSNZ), Shenzhen, China',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'miscellaneous_dangerous_goods-9',
				origin_port      : 'Shenzhen (CNSNZ), Shenzhen, China',
				destination_port : 'ICD Dadri (INDER), Delhi, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bintulu (MYBTU), Bintulu, Malaysia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Raipur (ICD|CFS|SEZ) (INRPR), Raipur, India',
				destination_port : 'Doha (QADOH), Doha, Qatar',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang North ( Northport) (MYLPK), Malaysia, Asia',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang North ( Northport) (MYLPK), Malaysia, Asia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Bremerhaven (DEBRV), Bremerhaven, Germany',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Pithampur (ICD|CFS|SEZ|Dhannad) (INPIR), Indore, India',
				destination_port : 'Cincinnati (USCVG), United States of America, usa',
			},
			{
				container_size   : '40',
				container_type   : 'open_top',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Ningbo Pt (CNNBG), Ningbo, China',
				destination_port : 'Jaipur (ICD|CFS|SEZ) (INJAI), Jaipur, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'open_top',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Ningbo Pt (CNNBG), Ningbo, China',
				destination_port : 'Jaipur (ICD|CFS|SEZ) (INJAI), Jaipur, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ningbo Pt (CNNBG), Ningbo, China',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ningbo Pt (CNNBG), Ningbo, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hai Phong, Haiphong, Vietnam',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hai Phong, Haiphong, Vietnam',
				destination_port : 'Rotterdam (NLRTM), Rotterdam, Netherlands',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hai Phong, Haiphong, Vietnam',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Hai Phong, Haiphong, Vietnam',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vancouver, US (USVAN), United States of America, usa',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Sokhna(Al Sokhna) (EGSOK), Suez, Egypt',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Sokhna(Al Sokhna) (EGSOK), Suez, Egypt',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Qingdao (CNQIN), Qingdao, China',
				destination_port : 'ICD Whitefield Terminal , Bangalore (Bengaluru) (INBLR), Banglore, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Qingdao (CNQIN), Qingdao, China',
				destination_port : 'Mombasa (KEMBA), Mombasa, Kenya',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Qingdao (CNQIN), Qingdao, China',
				destination_port : 'ICD Jajpur, Jajpur, Jajapur',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Qingdao (CNQIN), Qingdao, China',
				destination_port : 'Vizag (INVIZ), Vishakhapatnam, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Qingdao (CNQIN), Qingdao, China',
				destination_port : 'Vizag (INVIZ), Vishakhapatnam, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Pipavav (Victor) Port (INPAV), Bhavnagar, India',
				destination_port : 'Lisbon (PTLIS), Lisbon, Portugal',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Pipavav (Victor) Port (INPAV), Bhavnagar, India',
				destination_port : 'New York (USNYC), New York, United States of America',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Pipavav (Victor) Port (INPAV), Bhavnagar, India',
				destination_port : 'New York (USNYC), New York, United States of America',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Pipavav (Victor) Port (INPAV), Bhavnagar, India',
				destination_port : 'Santos (BRSSZ), Santos, Brazil',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Pipavav (Victor) Port (INPAV), Bhavnagar, India',
				destination_port : 'Chittagong (BDCGP), Chittagong, Bangladesh',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Bandar Abbas (IRBND), Bandar-e-Abbas, Iran',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Port Sudan (SDPZU), Port Sudan, Sudan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Casablanca (MACAS), Casablanca, Morocco',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Banjul (GMBJL), Banjul, Gambia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Tunis (TNTUN), Tunis, Tunisia',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'New York (USNYC), New York, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Cotonou (BJCOO), Cotonou, Benin',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Mombasa (KEMBA), Mombasa, Kenya',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Aqaba (JOAQJ), Al Aqabah, Jordan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Hai Phong, Haiphong, Vietnam',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Miami (USMIA), Miami, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Djibouti (DJJIB), Djibouti, Djibouti',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Balikpapan (IDBPN), Indonesia, Asia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Dakar (SNDKR), Senegal, Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kolkata (INCCU), Kolkata, India',
				destination_port : 'Jeddah (SAJED), Jeddah, Saudi Arabia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Yangon (MMRGN), Rangoon, Myanmar [Burma]',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Yangon (MMRGN), Rangoon, Myanmar [Burma]',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Wijchen (NLWCH), Netherlands, Europe',
				destination_port : 'ICD DASHRATH (Baroda) (INBRC), vadodara, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dalian (CNDLC), China, Asia',
				destination_port : 'Tuticorin (INTUT), Tuticorin, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dalian (CNDLC), China, Asia',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dalian (CNDLC), China, Asia',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dalian (CNDLC), China, Asia',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Dalian (CNDLC), China, Asia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ennore (INENR), India, Asia',
				destination_port : 'Valencia (ESVLC), Valencia, Spain',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ennore (INENR), India, Asia',
				destination_port : 'Valparaiso (CLVAP), Valparaiso, Chile',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ennore (INENR), India, Asia',
				destination_port : 'Jeddah (SAJED), Jeddah, Saudi Arabia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ennore (INENR), India, Asia',
				destination_port : 'Misurata (LYMRA), Misratah, Libya',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jiujiang (CNJUJ), Jiujiang, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Xiamen (CNXMN), Xiamen, China',
				destination_port : 'Cochin (INCOK), Kochi, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Xiamen (CNXMN), Xiamen, China',
				destination_port : 'Cochin (INCOK), Kochi, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Baltimore , Maryland (USBAL), Baltimore, United States of America',
				destination_port : 'Port au Prince (HTPAP), Port-au-Prince, Haiti',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Ahmedabad/Khodiyar (INAMD), Ahmedabad, India',
				destination_port : 'Georgetown (GYGEO), Georgetown, Guyana',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Ahmedabad/Khodiyar (INAMD), Ahmedabad, India',
				destination_port : 'Sydney (AUSYD), Sydney, Australia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
				destination_port : 'ICD Garhi Harsaru (INGHR), Delhi, India',
			},
			{
				container_size   : '20',
				container_type   : 'flat_rack',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Guangzhou (CNCAN), China, Asia',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'ICD Nashik (INNSK), Nashik, Maharashtra, India',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '40HC',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'ICD Nashik (INNSK), Nashik, Maharashtra, India',
				destination_port : 'Genoa (ITGOA), Genoa, Italy',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Chongqing (CNCQI), Chongqing, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Rotterdam (NLRTM), Rotterdam, Netherlands',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Singapore (SGSIN), Singapore, Singapore',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Singapore (SGSIN), Singapore, Singapore',
				destination_port : 'Umm Qasr North (IQUQR), Umm Qasr, Iraq',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Singapore (SGSIN), Singapore, Singapore',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Minneapolis , Minnesota (USMES), United States of America, usa',
				destination_port : 'ICD SONIPAT (PANCHI GUJARAN)(DICT) (INBDM), Sonipat, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Lome (TGLFW), Lome, Togo',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Venice (Venezia) (ITVCE), Venice, Italy',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Port Sudan (SDPZU), Port Sudan, Sudan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Casablanca (MACAS), Casablanca, Morocco',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Latakia (SYLTK), Idlib, Syria',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Banjul (GMBJL), Banjul, Gambia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Tamatave (Toamasina) (MGTMM), Toamasina, Madagascar',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Cotonou (BJCOO), Cotonou, Benin',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Mombasa (KEMBA), Mombasa, Kenya',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Dammam (SADMM), Ad Dammam, Saudi Arabia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Hai Phong, Haiphong, Vietnam',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Djibouti (DJJIB), Djibouti, Djibouti',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Conakry (GNCKY), Conakry, Guinea',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Tema (GHTEM), Tema, Ghana',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Douala (CMDLA), Douala, Cameroon',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Manzanillo, MX (MXZLO), Manzanillo, Mexico',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Vizag (INVIZ), Vishakhapatnam, India',
				destination_port : 'Cat Lai (VNCLI), Ho Chi Minh City, Vietnam',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ho Chi Minh City (VNSGN), Ho Chi Minh City, Vietnam',
				destination_port : 'ICD Whitefield Terminal , Bangalore (Bengaluru) (INBLR), Banglore, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ho Chi Minh City (VNSGN), Ho Chi Minh City, Vietnam',
				destination_port : 'Columbia , South Carolina (USCAE), Columbia, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ho Chi Minh City (VNSGN), Ho Chi Minh City, Vietnam',
				destination_port : 'ICD Garhi Harsaru (INGHR), Delhi, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Ho Chi Minh City (VNSGN), Ho Chi Minh City, Vietnam',
				destination_port : 'ICD Dadri (INDER), Delhi, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Oakland (USOAK), Oakland, United States of America',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Durgapur (ICD|CFS|SEZ) (INDUR), Kolkata, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Durgapur (ICD|CFS|SEZ) (INDUR), Kolkata, India',
				destination_port : 'Djibouti (DJJIB), Djibouti, Djibouti',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Xiangang (CN), China, Asia',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Surabaya (IDSUB), Surabaya, Indonesia',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Wenzhou (CNWNZ), Wenzhou, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Durban (ZADUR), Durban, South Africa',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Bandar Abbas (IRBND), Bandar-e-Abbas, Iran',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Santos (BRSSZ), Santos, Brazil',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'toxic_substances-6.1',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Santos (BRSSZ), Santos, Brazil',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Port Louis (MUPLU), Port Louis, Mauritius',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Singapore (SGSIN), Singapore, Singapore',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Mogadishu (SOMGQ), Mogadishu, Somalia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Durban (ZADUR), Durban, South Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hazira (INHZA), Surat, India',
				destination_port : 'Tema (GHTEM), Tema, Ghana',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Keelung (TWKEL), Keelung, Taiwan',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Itajai (BRITJ), Itajai, Brazil',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Sydney (AUSYD), Sydney, Australia',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'HOUSTON (USHOU), Texas City, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Beirut (LBBEY), Beirut, Lebanon',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Doha (QADOH), Doha, Qatar',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Baltimore , Maryland (USBAL), Baltimore, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'McAllen (US), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Sfax (TNSFA), Tunisia, Med',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Brazzaville (CGBRZ), Brazzaville, Republic of Congo',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Tughlakabad (ICD|CFS|SEZ) (INTKD), New Delhi, India',
				destination_port : 'Bishkek (KGFRU), Bishkek, Kyrgyzstan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Dublin-Dublin Ferryport Terminals (IEDFT), Dublin, Ireland',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Port Elizabeth (ZAPLZ), Port Elizabeth, South Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Matadi (CDMAT), Matadi, Democratic Republic of theКCongo',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Casablanca (MACAS), Casablanca, Morocco',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Sydney (AUSYD), Sydney, Australia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Mazatlan (MXMZT), Mazatlan, Mexico',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Port Chicago , Illinois (USPZH), Chicago, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Melbourne (AUMEL), Melbourne, Australia',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Melbourne (AUMEL), Melbourne, Australia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Lisbon (PTLIS), Lisbon, Portugal',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Gdansk (PLGDN), Gdansk, Poland',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Alger (US), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Banjul (GMBJL), Banjul, Gambia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Tianjin Xingang (CNTXG), Tianjin, China',
			},
			{
				container_size   : '40',
				container_type   : 'refer',
				commodity        : 'frozen',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Tianjin Xingang (CNTXG), Tianjin, China',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Mariel (CUMAR), Mariel, Cuba',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Khalifa Bin Salman (BHKBS), Bahrain, Meg',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Khalifa Bin Salman (BHKBS), Bahrain, Meg',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Nassau (BSNAS), Nassau, Bahamas',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Kuwait (KWKWI), Kuwait, Kuwait',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Manila South Harbour (PHMNS), Manila, Philippines',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Benapole (BD), Bangladesh, Asia',
			},
			{
				container_size   : '40',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Sohar (OMSOH), Sohar, Oman',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Moscow (RUMOW), Moscow, Russia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'NAVOI (UZNVI), Navoi, Uzbekistan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Hodeidah (YEHOD), Al Hudaydah, Yemen',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Novorossiysk (RU), Russia, Europe',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'HOUSTON (USHOU), Texas City, United States of America',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'HOUSTON (USHOU), Texas City, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'refer',
				commodity        : 'frozen',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Dammam (SADMM), Ad Dammam, Saudi Arabia',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Livorno (Leghorn) (ITLIV), Livorno, Italy',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Salalah (OMSLL), Salalah, Oman',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Freetown (SLFNA), Freetown, Sierra Leone',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Larvik (NOLAR), Norway, Europe',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Houston (US), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Beirut (LBBEY), Beirut, Lebanon',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Seattle (USSEA), Seattle, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Doha (QADOH), Doha, Qatar',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Toronto (CATOR), Toronto, Canada',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Rades (TNRDS), Tunisia, Med',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Penang (MY), Malaysia, Asia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'EMBAKASI (Nairobi) (KEEMB), Nairobi, Kenya',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Berbera (SOBBO), Berbera, Somalia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'San Juan (PRSJU), San Juan, Puerto Rico',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Cape Town (ZACPT), Cape Town, South Africa',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Apapa (Lagos) (NGAPP), Lagos, Nigeria',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Alger (US), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'open_top',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Valencia (ESVLC), Valencia, Spain',
			},
			{
				container_size   : '40HC',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Ho Chi Minh City (VNSGN), Ho Chi Minh City, Vietnam',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Kribi (CMKBI), Cameroon, Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Baku (AZBAK), Baku, Azerbaijan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Indonesia Bulk Terminal (ID), Indonesia, Asia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Caucedo (DOCAU), Santo Domingo, Dominican Republic',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Barranquilla (COBAQ), Barranquilla, Colombia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Boston (USBOS), Boston, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Incheon (KRINC), Incheon, South Korea',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Brisbane (AUBNE), Brisbane, Australia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Tripoli (LYTIP), Libya, Med',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Tanger Med (MAPTM), Morocco, Med',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Rijeka (HRRJK), Rijeka, Croatia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'St Johns (AGSJO), Antigua and Barbuda, LatAm',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Haikou (Hainan) (CNHAI), China, Asia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Mahe (SCMAW), Seychelles, Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Mundra (INMUN), Bhuj, India',
				destination_port : 'Calgary (CAYYC), Calgary, Canada',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kakinada (INKAK), Kakinada, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Kakinada (INKAK), Kakinada, India',
				destination_port : 'Douala (CMDLA), Douala, Cameroon',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shekou Pt (CNSHK), Shenzhen, China',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Shekou Pt (CNSHK), Shenzhen, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nanjing (CNNJG), Nanjing, China',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nanjing (CNNJG), Nanjing, China',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Lome (TGLFW), Lome, Togo',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Port Sudan (SDPZU), Port Sudan, Sudan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Casablanca (MACAS), Casablanca, Morocco',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Shuwaikh (KWSWK), Kuwait, Kuwait',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Cotonou (BJCOO), Cotonou, Benin',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Aqaba (JOAQJ), Al Aqabah, Jordan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Nacala (MZMNC), Nacala, Mozambique',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Doha (QADOH), Doha, Qatar',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Johannesburg (ZAJNB), Johannesburg, South Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Djibouti (DJJIB), Djibouti, Djibouti',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Mogadishu (SOMGQ), Mogadishu, Somalia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Incheon (KRINC), Incheon, South Korea',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Incheon (KRINC), Incheon, South Korea',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Haldia Port (INHAL), Kolkata, India',
				destination_port : 'Jeddah (SAJED), Jeddah, Saudi Arabia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Krishnapatnam (INKRI), Nellore, India',
				destination_port : 'Casablanca (MACAS), Casablanca, Morocco',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Krishnapatnam (INKRI), Nellore, India',
				destination_port : 'Cotonou (BJCOO), Cotonou, Benin',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Krishnapatnam (INKRI), Nellore, India',
				destination_port : 'Novorossiysk (RUNVS), Novorossiysk, Russia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'ICD Valsad, Valsad, Valsad',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Nagpur (ICD|CFS|SEZ) (INNAG), Nagpur, Maharashtra',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'pta',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'TUMB (INTMB), Valsad, Gujarat, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Mihan, Nagpur, Maharashtra',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Borkhedi (INBRD), Nagpur, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Busan (KRPUS), Busan, South Korea',
				destination_port : 'Jhattipur (INJTT), Panipat, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'flammable_solids-4.1',
				origin_port      : 'Le Havre (FRLEH), Le Havre, France',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Qinzhou Pt (CNQZH), Qinzhou, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Dadri (INDER), Delhi, India',
				destination_port : 'Tianjin Xingang (CNTXG), Tianjin, China',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Dadri (INDER), Delhi, India',
				destination_port : 'Puerto Cortes (HNPCR), Honduras, LatAm',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Dadri (INDER), Delhi, India',
				destination_port : 'Derince (TRDRC), Turkey, Med',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'ICD Dadri (INDER), Delhi, India',
				destination_port : 'HARARE (ZWHRE), Harare, Zimbabwe',
			},
			{
				container_size   : '40',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Bandar Abbas (IRBND), Bandar-e-Abbas, Iran',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Mutsamudu (KMMUT), Comoros, Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Sydney (AUSYD), Sydney, Australia',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Latakia (SYLTK), Idlib, Syria',
			},
			{
				container_size   : '20',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '20',
				container_type   : 'refer',
				commodity        : 'frozen',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '40',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Melbourne (AUMEL), Melbourne, Australia',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Melbourne (AUMEL), Melbourne, Australia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Port Moresby (PGPOM), Port Moresby, Papua New Guinea',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Callao (PECLL), Callao, Peru',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Atlanta (USATL), United States of America, usa',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Atlanta (USATL), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Mariel (CUMAR), Mariel, Cuba',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Memphis (TN) (USMEM), Memphis, United States of America',
			},
			{
				container_size   : '40',
				container_type   : 'flat_rack',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '40HC',
				container_type   : 'flat_rack',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Dar es Salaam (TZDAR), Dar es Salaam, Tanzania',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Ashdod (ILASH), Ashdod, Israel',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Charleston (US), United States of America, usa',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Nouakchott (MRNKC), Nouakchott, Mauritania',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Kuwait (KWKWI), Kuwait, Kuwait',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Oita (JPOIT), Oita, Japan',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Haydarpasa (TRHAY), Turkey, Med',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Tamatave (Toamasina) (MGTMM), Toamasina, Madagascar',
			},
			{
				container_size   : '40HC',
				container_type   : 'open_top',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Sohar (OMSOH), Sohar, Oman',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Elizabeth, New Jersey (USZIP), United States of America, usa',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Novorossiysk (RUNVS), Novorossiysk, Russia',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'HOUSTON (USHOU), Texas City, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Beira (MZBEW), Beira, Mozambique',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Newark (NJ) (USEWR), Newark, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Houston (US), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Jabel (DE), Germany, Europe',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Jabel (DE), Germany, Europe',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Muscat (OMMCT), Muscat, Oman',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Houston, MS (USHOG), United States of America, usa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Monte Negro (BR), Brazil, Sam',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Santos (BRSSZ), Santos, Brazil',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Santos (BRSSZ), Santos, Brazil',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Accra, Accra, Ghana',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Doha (QADOH), Doha, Qatar',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Doha (QADOH), Doha, Qatar',
			},
			{
				container_size   : '20',
				container_type   : 'open_top',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Hamad (QAHMD), Qatar, Meg',
			},
			{
				container_size   : '20',
				container_type   : 'refer',
				commodity        : 'frozen',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Hamad (QAHMD), Qatar, Meg',
			},
			{
				container_size   : '40',
				container_type   : 'open_top',
				commodity        : 'in_gauge_cargo',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Hamad (QAHMD), Qatar, Meg',
			},
			{
				container_size   : '40',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Hamad (QAHMD), Qatar, Meg',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Auckland (NZAKL), Auckland, New Zealand',
			},
			{
				container_size   : '20',
				container_type   : 'open_side',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Colombo (LKCMB), Colombo, Sri Lanka',
			},
			{
				container_size   : '40',
				container_type   : 'open_side',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Colombo (LKCMB), Colombo, Sri Lanka',
			},
			{
				container_size   : '40HC',
				container_type   : 'open_side',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Colombo (LKCMB), Colombo, Sri Lanka',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Penang (MY), Malaysia, Asia',
			},
			{
				container_size   : '40',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Penang (MY), Malaysia, Asia',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Penang (MY), Malaysia, Asia',
			},
			{
				container_size   : '40HC',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Penang (MY), Malaysia, Asia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'EMBAKASI (Nairobi) (KEEMB), Nairobi, Kenya',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Miami (USMIA), Miami, United States of America',
			},
			{
				container_size   : '40',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Port Klang West (Pelabuhan Klang) (MYPKG), Kelang, Malaysia',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'corrosives-8',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Buenaventura (COBUN), Buenaventura, Colombia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Iquique (CLIQQ), Iquique, Chile',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Tripoli (LBKYE), Lebanon, Med',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Kribi (CMKBI), Cameroon, Africa',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Kribi (CMKBI), Cameroon, Africa',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Dubai World Central Apt (AE), United Arab Emirates, Meg',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Turkey (US), United States of America, usa',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Incheon Intl Apt/Seoul (KR), South Korea, Asia',
			},
			{
				container_size   : '40HC',
				container_type   : 'refer',
				commodity        : 'chilled',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Jeddah (SAJED), Jeddah, Saudi Arabia',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'HARARE (ZWHRE), Harare, Zimbabwe',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Copenhagen (DKCPH), KГёbenhavn, Denmark',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Calgary (CAYYC), Calgary, Canada',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				destination_port : 'Calgary (CAYYC), Calgary, Canada',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Laem Chabang (THLCH), Thailand, Asia',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Laem Chabang (THLCH), Thailand, Asia',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Laem Chabang (THLCH), Thailand, Asia',
				destination_port : 'Kattupalli (INKAT), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Laem Chabang (THLCH), Thailand, Asia',
				destination_port : 'Pipavav (Victor) Port (INPAV), Bhavnagar, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Laem Chabang (THLCH), Thailand, Asia',
				destination_port : 'Hazira (INHZA), Surat, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Felixstowe (GBFXT), United Kingdom, Europe',
				destination_port : 'ICD Panki (JRY) (INKNU), Kanpur, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Felixstowe (GBFXT), United Kingdom, Europe',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Genoa (ITGOA), Genoa, Italy',
				destination_port : 'Savannah, Georgia (USSAV), Savannah, United States of America',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Antwerp (BEANR), Antwerpen, Belgium',
				destination_port : 'Kolkata (INCCU), Kolkata, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nansha Pt (CNNSA), Guangzhou, China',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nansha Pt (CNNSA), Guangzhou, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Nansha Pt (CNNSA), Guangzhou, China',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hamburg (DEHAM), Hamburg, Germany',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '40HC',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hamburg (DEHAM), Hamburg, Germany',
				destination_port : 'Chennai (INMAA), Chennai, India',
			},
			{
				container_size   : '20',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Hamburg (DEHAM), Hamburg, Germany',
				destination_port : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
			},
			{
				container_size   : '40',
				container_type   : 'standard',
				commodity        : 'general',
				origin_port      : 'Yokohama (JPYOK), Yokohama, Japan',
				destination_port : 'Mundra (INMUN), Bhuj, India',
			},
		],
		// eslint-disable-next-line max-len
		csv_link : 'https://new-rpa-test.s3.ap-south-1.amazonaws.com/rate_sheets/most_search_spot_data_6f5d47cc551f437e86073569ad4e8eef.csv',
		count    : 407,
	};

	return spotsearchData;
};
export default useGetMostPredictedSpotRate;
