import ORGANISATION_SUB_TYPE_MAPPING from '../../../../configs/ORGANISATION_SUB_TYPE_MAPPING.json';
import ORGANISATION_TYPE_MAPPING from '../../../../configs/ORGANISATION_TYPE_MAPPING.json';
import RATE_SOURCE_MAPPING from '../../../../configs/RATE_SOURCE_MAPPING.json';
import RULE_TYPE_MAPPING from '../../../../configs/RULE_TYPE_MAPPING.json';
import TRADE_TYPE_MAPPING from '../../../../configs/TRADE_TYPE_MAPPING.json';

const controls = () => [
	{
		name        : 'cogo_entity',
		label       : 'Cogo Entity',
		type        : 'async_select',
		placeholder : 'Select Cogo Entity',
		asyncKey    : 'list_cogo_entity',
		initialCall : true,
		labelKey    : 'business_name',
		valueKey    : 'entity_code',
		span        : 2,
		rules       : { required: 'Cogo Entity is required' },
		size        : 'sm',
	},
	{
		label       : 'Scope',
		name        : 'scope',
		type        : 'select',
		placeholder : 'Select Rule Type',
		size        : 'sm',
		options     : RULE_TYPE_MAPPING,
		span        : 2,
		rules       : { required: 'Scope is required' },
	},
	{
		label       : 'Category',
		size        : 'sm',
		name        : 'category',
		type        : 'select',
		placeholder : 'Business',
		disabled    : true,
		span        : 2,
	},
	{
		label       : 'For Service',
		name        : 'for_service',
		type        : 'select',
		placeholder : 'FCL Customs',
		disabled    : true,
		size        : 'sm',
		span        : 2,
	},
	{
		label       : 'Trade Type',
		name        : 'trade_type',
		type        : 'select',
		placeholder : 'Select Trade Type',
		options     : TRADE_TYPE_MAPPING,
		size        : 'sm',
		span        : 2,
		rules       : { required: 'Trade Type is required' },
	},
	{
		label       : 'Rate Source',
		name        : 'rate_source',
		type        : 'select',
		placeholder : 'Select Rate Source',
		options     : RATE_SOURCE_MAPPING,
		span        : 2,
		size        : 'sm',
		rules       : { required: 'Rate Source is required' },
	},
	{
		label       : 'For Organisation',
		name        : 'for_organisation',
		type        : 'async_select',
		placeholder : 'Organisation Name',
		asyncKey    : 'organizations',
		initialCall : true,
		labelKey    : 'business_name',
		valueKey    : 'id',
		renderLabel : (item) => item?.trade_name,
		span        : 2,
		rules       : { required: 'For Organisation is required' },
		size        : 'sm',
	},
	{
		label       : 'Organisation Type',
		name        : 'organisation_type',
		type        : 'select',
		placeholder : 'Select Org Type',
		options     : ORGANISATION_TYPE_MAPPING,
		span        : 2,
		size        : 'sm',
	},
	{
		label       : 'Organisation Sub-Type',
		name        : 'organisation_sub_type',
		type        : 'select',
		placeholder : 'Select Org Sub Type',
		options     : ORGANISATION_SUB_TYPE_MAPPING,
		span        : 2,
		size        : 'sm',
	},
];

export default controls;
