import {
	where,
} from 'firebase/firestore';

function getSupplySessionQuery({ sessionType, isContactsSelected = false }) {
	return isContactsSelected
		? [where('session_type', 'in', ['bot', 'admin'])] : [where('session_type', '==', sessionType)];
}

export const VIEW_TYPE_GLOBAL_MAPPING = {
	sales: {
		all_chats_base_query      : ({ agentId }) => [where('support_agent_id', '==', agentId)],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		session_type_query        : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access      : ['all', 'observer'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		permissions: {
			auto_assign                 : false,
			assign_to_me                : false,
			observe_chat                : false,
			all_chats                   : false,
			team_view_chats             : false,
			trasnfer_chats              : false,
			request_to_join_group       : false,
			add_members_to_group        : false,
			accept_group_requests       : false,
			bot_message_toggle          : false,
			observer_chat_filter        : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : true,
		},
	},
	sales_admin: {
		all_chats_base_query      : () => [where('agent_type', '==', 'sales')],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		session_type_query        : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access      : ['all', 'observer', 'teams'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		permissions: {
			auto_assign                 : false,
			assign_to_me                : false,
			observe_chat                : false,
			all_chats                   : false,
			team_view_chats             : false,
			trasnfer_chats              : false,
			request_to_join_group       : false,
			add_members_to_group        : false,
			accept_group_requests       : false,
			bot_message_toggle          : false,
			observer_chat_filter        : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : false,
		},
	},
	support: {
		all_chats_base_query      : ({ agentId }) => [where('support_agent_id', '==', agentId)],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		contacts_base_query       : () => [where('user_details.account_type', '==', 'service_provider')],
		session_type_query        : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access      : ['all', 'observer'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		permissions: {
			auto_assign                 : false,
			assign_to_me                : false,
			observe_chat                : false,
			all_chats                   : false,
			team_view_chats             : false,
			trasnfer_chats              : false,
			request_to_join_group       : false,
			add_members_to_group        : false,
			accept_group_requests       : false,
			bot_message_toggle          : false,
			observer_chat_filter        : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : true,
			toggle_agent_status         : false,
			toggle_self_status          : true,
		},
	},
	support_admin: {
		all_chats_base_query      : () => [where('agent_type', '==', 'support')],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		session_type_query        : ({ sessionType }) => [where('session_type', '==', sessionType)],
		chat_sub_tabs_access      : ['all', 'observer', 'teams'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
		},
		permissions: {
			auto_assign                 : false,
			assign_to_me                : false,
			observe_chat                : false,
			all_chats                   : false,
			team_view_chats             : false,
			trasnfer_chats              : false,
			request_to_join_group       : false,
			add_members_to_group        : false,
			accept_group_requests       : false,
			bot_message_toggle          : false,
			observer_chat_filter        : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : true,
			toggle_agent_status         : false,
			toggle_self_status          : false,
		},
	},
	supply: {
		all_chats_base_query      : ({ agentId }) => [where('support_agent_id', '==', agentId)],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		contacts_base_query       : () => [where('user_details.account_type', '==', 'service_provider')],
		session_type_query        : getSupplySessionQuery,
		chat_sub_tabs_access      : ['all', 'groups', 'teams', 'observer', 'contacts'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
			contacts : ['chat_tags'],
		},
		permissions: {
			auto_assign                 : false,
			assign_to_me                : false,
			observe_chat                : false,
			all_chats                   : false,
			team_view_chats             : false,
			trasnfer_chats              : false,
			request_to_join_group       : false,
			add_members_to_group        : false,
			accept_group_requests       : false,
			bot_message_toggle          : false,
			observer_chat_filter        : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : true,
			toggle_agent_status         : false,
			toggle_self_status          : true,
		},
	},
	supply_admin: {
		all_chats_base_query      : () => [where('agent_type', '==', 'supply')],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		contacts_base_query       : () => [where('user_details.account_type', '==', 'service_provider')],
		session_type_query        : getSupplySessionQuery,
		chat_sub_tabs_access      : ['all', 'groups', 'teams', 'observer', 'contacts'],
		accesible_filters         : {
			observer : ['closed_session'],
			all      : ['chat_tags'],
			contacts : ['chat_tags'],
		},
		permissions: {
			auto_assign                 : false,
			assign_to_me                : false,
			observe_chat                : false,
			all_chats                   : false,
			team_view_chats             : false,
			trasnfer_chats              : false,
			request_to_join_group       : false,
			add_members_to_group        : false,
			accept_group_requests       : false,
			bot_message_toggle          : false,
			observer_chat_filter        : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : false,
		},
	},
	shipment_view: {
		all_chats_base_query      : ({ agentId }) => [where('booking_agent_ids', 'array-contains', agentId)],
		observer_chats_base_query : ({ agentId }) => [where('spectators_ids', 'array-contains', agentId)],
		group_chats_query         : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query    : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		session_type_query        : () => [where('session_type', 'in', ['bot', 'admin'])],
		chat_sub_tabs_access      : ['all'],
		permissions               : {
			auto_assign                 : false,
			assign_to_me                : false,
			observe_chat                : false,
			all_chats                   : false,
			team_view_chats             : false,
			trasnfer_chats              : false,
			request_to_join_group       : false,
			add_members_to_group        : false,
			accept_group_requests       : false,
			bot_message_toggle          : false,
			observer_chat_filter        : false,
			organization_users_contacts : false,
			bulk_auto_assign            : false,
			claim_chats                 : false,
			toggle_agent_status         : false,
			toggle_self_status          : true,
		},
	},
	cogoone_admin: {
		group_chats_query      : ({ agentId }) => [where('group_members', 'array-contains', agentId)],
		teams_chats_base_query : ({ agentId }) => [where('manager_ids', 'array-contains', agentId)],
		session_type_query     : getSupplySessionQuery,
		chat_sub_tabs_access   : ['all', 'groups', 'contacts'],
		accesible_filters      : {
			all      : ['15_min_filter', 'assigned_to', 'assigned_agent', 'chat_tags'],
			contacts : ['chat_tags'],
		},
		permissions: {
			auto_assign                 : true,
			assign_to_me                : true,
			observe_chat                : true,
			all_chats                   : true,
			team_view_chats             : true,
			trasnfer_chats              : true,
			request_to_join_group       : true,
			add_members_to_group        : true,
			accept_group_requests       : true,
			bot_message_toggle          : true,
			observer_chat_filter        : true,
			organization_users_contacts : true,
			bulk_auto_assign            : true,
			claim_chats                 : true,
			toggle_agent_status         : true,
			toggle_self_status          : false,
		},
	},
};
