const mawbControls = () => {
	return [
		{
			name: 'shipper_name',
			type: 'text',
			label: "Shipper's Name",
			className: 'primary lg',
			showOptional: false,
			placeholder: "Shipper's name*",
			span: 6,
			value: '',
			maxLength: 50,
			rules: { required: true },
		},
		{
			name: 'shipper_address',
			className: 'primary md',
			label: "Shipper's Address:",
			type: 'textarea',
			span: 12,
			maxLength: 150,
			row: 4,
			placeholder: 'Address...',
			rules: {
				required: true,
			},
		},
		{
			name: 'consignee_name',
			type: 'text',
			className: 'primary lg',
			label: "Consignee's Name",
			showOptional: false,
			value: '',
			span: 6,
			placeholder: "consignee's name*",
			maxLength: 50,
			rules: { required: true },
		},
		{
			name: 'consignee_address',
			className: 'primary md',
			label: "Consignee's Address:",
			type: 'textarea',
			span: 12,
			maxLength: 150,
			row: 4,
			placeholder: 'Address...',
			rules: {
				required: true,
			},
		},
		{
			name: 'origin_airport',
			type: 'text',
			className: 'primary lg',
			label: 'Origin:',
			placeholder: 'Enter Origin Airport',
			span: 6,
			rules: { required: true },
		},
		{
			name: 'destination_airport',
			type: 'text',
			className: 'primary lg',
			label: 'Destination:',
			placeholder: 'Enter Destination Airport',
			span: 6,
			rules: { required: true },
		},
		{
			name: 'accounting_information',
			type: 'text',
			className: 'primary lg',
			label: 'Accounting Information:',
			value: 'Freight PrePaid',
			span: 6,
			rules: { required: true },
		},
		{
			name: 'iata_code',
			type: 'text',
			className: 'primary lg',
			label: "Agent's Iata Code:*",
			value: '14-3-4526/0005',
			span: 6,
			rules: { required: true },
		},
		{
			name: 'declared_value_for_carriage',
			type: 'text',
			className: 'primary lg',
			label: 'Declared Value for Carriage:',
			value: 'NVD',
			span: 6,
			rules: { required: true },
		},
		{
			name: 'city',
			type: 'text',
			className: 'primary lg',
			span: 6,
			label: 'Issuing Carrier City:*',
			value: 'NEW DELHI',
			placeholder: 'City...',
			rules: { required: true },
		},
		{
			name: 'value_for_custom',
			type: 'text',
			className: 'primary lg',
			label: 'Declared Value for Customs:',
			showOptional: false,
			span: 6,
			placeholder: 'Enter Value For Custom',
		},
		{
			name: 'information',

			span: 12,
			showOptional: false,
		},
		{
			name: 'handling_information',
			type: 'text',
			className: 'primary lg',
			label: 'Handling Information:',
			showOptional: false,
			span: 6,
			placeholder: 'Handling Information...*',
			maxLength: 100,
			rules: { required: true },
		},
		{
			name: 'rate_per_kg',
			type: 'number',
			className: 'primary lg',
			label: 'Rate per Kg',
			showOptional: false,
			span: 6,
			placeholder: 'Rate per Kg',
			rules: { required: true },
		},
		{
			name: 'currency',
			placeholder: 'Select Currency',
			type: 'select',
			span: 6,
			label: 'Currency',
			optionsListKey: 'currencies',
			className: 'primary lg width',
			rules: {
				required: true,
			},
		},
		{
			name: 'other_charges_label',
			label: 'Other Charges Due Agent',
			showOptional: false,
			span: 12,
		},
		{
			name: 'agent_other_charges',
			className: 'primary lg',
			type: 'fieldArray',
			showOptional: false,
			showButtons: true,
			noDeleteButtonTill: 1,
			value: [
				{
					code: '',
					price: '',
				},
			],
			controls: [
				{
					name: 'code',
					type: 'text',
					className: 'primary lg',
					span: 2.5,
					placeholder: 'Enter Code',
					rules: {
						required: true,
					},
				},
				{
					name: 'price',
					placeholder: 'Enter Price',
					type: 'number',
					span: 2.5,
					className: 'primary lg',
					rules: {
						required: true,
					},
				},
			],
		},
		{
			name: 'other_charges_carrier',
			label: 'Other Charges Due Carrier',
			showOptional: false,
			span: 12,
		},
		{
			name: 'carrier_other_charges',
			className: 'primary lg',
			type: 'fieldArray',
			showOptional: false,
			showButtons: true,
			noDeleteButtonTill: 1,
			value: [
				{
					code: '',
					price: '',
				},
			],
			controls: [
				{
					name: 'code',
					type: 'text',
					className: 'primary lg',
					span: 2.5,
					placeholder: 'Enter Code',
					rules: {
						required: true,
					},
				},
				{
					name: 'price',
					placeholder: 'Enter Price',
					type: 'number',
					span: 2.5,
					className: 'primary lg',
					rules: {
						required: true,
					},
				},
			],
		},
		{
			name: 'dimension_details',
			span: 12,
			label: 'Dimensions(in cm)',
			showOptional: false,
		},
		{
			name: 'dimension',
			label: 'Dimensions (in cm)',
			type: 'fieldArray',
			className: 'primary lg',
			showOptional: false,
			showButtons: true,
			noDeleteButtonTill: 1,
			span: 4,
			value: [
				{
					length: '',
					breadth: '',
					height: '',
					package: '',
				},
			],
			controls: [
				{
					name: 'length',
					placeholder: 'length',
					label: 'Length',
					type: 'number',
					className: 'primary lg',
					span: 2,
					rules: {
						required: true,
						validate: (value) => (value < 0 ? 'Cannot be Negative' : true),
					},
				},
				{
					name: 'width',
					placeholder: 'width',
					label: 'Width',
					type: 'number',
					className: 'primary lg',
					span: 2,
					rules: {
						required: true,
						validate: (value) => (value < 0 ? 'Cannot be Negative' : true),
					},
				},
				{
					name: 'height',
					placeholder: 'height',
					label: 'Height',
					type: 'number',
					className: 'primary lg',
					span: 2,
					rules: {
						required: true,
						validate: (value) => (value < 0 ? 'Cannot be Negative' : true),
					},
				},
				{
					name: 'packages',
					placeholder: 'no of packages',
					label: 'Number of Packages',
					type: 'number',
					className: 'primary lg',
					span: 2,
					rules: {
						required: true,
						validate: (value) => (value < 0 ? 'Cannot be Negative' : true),
					},
				},
			],
		},
		{
			name: 'remark',
			className: 'primary lg',
			label: 'Remarks:',
			type: 'textarea',
			span: 6,
			maxLength: 150,
			placeholder: 'Remarks...',
			rows: 3,
			rules: {
				required: true,
			},
		},
		{
			name: 'commodity',
			className: 'primary lg',
			label: 'Commodity Details:',
			type: 'textarea',
			span: 6,
			maxLength: 300,
			placeholder: 'Commodity...',
			rows: 3,
			rules: {
				required: true,
			},
		},
		{
			name: 'place',
			type: 'text',
			className: 'primary lg input_place',
			showOptional: false,
			value: 'NEW DELHI',
			label: 'At Place:',
			placeholder: 'Place',
			rules: { required: true },
		},
	];
};

export default mawbControls;
