export const CUSTOM_TASKS = [
	'update_container_details',
	'upload_container_arrival_notice',
	'amend_draft_house_bill_of_lading',
	'choose_service_provider',
	'confirm_with_shipper',
	'update_nomination_details',
	'generate_freight_certificate',
	'generate_cargo_insurance',
	'upload_compliance_documents',
	'upload_booking_note',
	'add_consignee_details',
	'add_shipper_details',
	'confirm_cargo_readiness',
];

export const CUSTOM_TASK_MAPPING = {
	UPDATE_CONTAINER_DETAILS        : 'update_container_details',
	UPLOAD_CONTAINER_ARRIVAL_NOTICE : 'upload_container_arrival_notice',
	AMEND_DRAFT_BL                  : 'amend_draft_house_bill_of_lading',
	CHOOSE_SERVICE_PROVIDER         : 'choose_service_provider',
	CONFIRM_WITH_SHIPPER            : 'confirm_with_shipper',
	UPDATE_NOMINATION_DETAILS       : 'update_nomination_details',
	GENERATE_FREIGHT_CERTIFICATE    : 'generate_freight_certificate',
	GENERATE_CARGO_INSURANCE        : 'generate_cargo_insurance',
	UPLOAD_COMPLIANCE_DOCUMENTS     : 'upload_compliance_documents',
	UPLOAD_BOOKING_NOTE             : 'upload_booking_note',
	ADD_CONSIGNEE_DETAILS           : 'add_consignee_details',
	ADD_SHIPPER_DETAILS             : 'add_shipper_details',
	CONFIRM_CARGO_READINESS         : 'confirm_cargo_readiness',
};
