export const quoteData = {
	list: [{
		code    : 'IHE',
		name    : 'Inland Haulage Export',
		unit    : 'per_container',
		price   : 46500.0,
		margins : [
			{
				margin_type        : 'demand',
				min_value          : 0,
				unit               : 'per_container',
				code               : 'IHE',
				currency           : 'INR',
				type               : 'absolute_total',
				total_margin_value : 46500.0,
				value              : 46500.0,
				max_value          : 1000000000000000,
			},
		],
		currency                   : 'INR',
		quantity                   : 1.0,
		min_price                  : 0.0,
		tax_price                  : 8370.0,
		tax_percent                : 18.0,
		total_price                : 46500.0,
		product_code               : 'TRC00003',
		credit_amount              : 0.0,
		exchange_rate              : 1.0,
		discount_price             : 0.0,
		tax_total_price            : 54870.0,
		price_discounted           : 46500.0,
		tax_price_discounted       : 8370.0,
		total_price_discounted     : 46500.0,
		tax_total_price_discounted : 54870.0,
		is_deleted                 : true,
		changed_items              : {
			item : 'created',
			code : 'IHE',
		},
	}],
};
