import styles from './styles.module.css';

export const requestControls = ({ t = () => {}, entityCode = '', activeTab = 'REQUESTED', filters }) => [
	{
		name        : 'category',
		placeholder : t('incidentManagement:select_category_placeholder'),
		type        : 'asyncSelect',
		caret       : true,
		isClearable : true,
		asyncKey    : 'list_incident_types',
		searchByq   : true,
		initialCall : true,
		params      : { status: activeTab, entityCode },
		className   : styles.category_section,
	},
	{
		name        : 'subType',
		placeholder : t('incidentManagement:select_request_sub_type_placeholder'),
		type        : 'asyncSelect',
		caret       : true,
		isClearable : true,
		asyncKey    : 'list_incident_types',
		searchByq   : true,
		initialCall : true,
		params      : { status: activeTab, type: 'incidentSubtype', requestCategory: filters?.category, entityCode },
		className   : styles.category_section,
	},
	{
		name        : 'urgency',
		placeholder : t('incidentManagement:select_urgency_placeholder'),
		type        : 'select',
		caret       : true,
		isClearable : true,
		options     : [
			{ value: 'all', label: t('incidentManagement:urgency_label_all') },
			{ value: 'urgent', label: t('incidentManagement:urgency_label_urgent') },
		],
		className: styles.urgency_section,
	},
	{
		name                  : 'date',
		placeholder           : t('incidentManagement:select_date_placeholder'),
		type                  : 'singleDateRange',
		isPreviousDaysAllowed : true,
		caret                 : true,
		isClearable           : true,
		className             : styles.date_section,
	},
	{
		name      : 'isMyTaskOnly',
		type      : 'toggle',
		size      : 'sm',
		onLabel   : t('incidentManagement:toggle_label'),
		offLabel  : '',
		className : styles.toggle,
	},
];

export const remainControls = ({ t = () => {}, entityCode = '', activeTab = '', filters }) => [
	{
		name        : 'category',
		placeholder : t('incidentManagement:select_category_placeholder'),
		type        : 'asyncSelect',
		caret       : true,
		isClearable : true,
		initialCall : true,
		asyncKey    : 'list_incident_types',
		searchByq   : true,
		params      : { status: activeTab, entityCode },
		className   : styles.category_section,
	},
	{
		name        : 'subType',
		placeholder : t('incidentManagement:select_request_sub_type_placeholder'),
		type        : 'asyncSelect',
		caret       : true,
		isClearable : true,
		asyncKey    : 'list_incident_types',
		searchByq   : true,
		initialCall : true,
		params      : { status: activeTab, type: 'incidentSubtype', requestCategory: filters?.category, entityCode },
		className   : styles.category_section,
	},
	{
		name                  : 'date',
		placeholder           : t('incidentManagement:select_date_placeholder'),
		type                  : 'singleDateRange',
		caret                 : true,
		isPreviousDaysAllowed : true,
		isClearable           : true,
		className             : styles.date,
		style                 : { width: '170px' },
	},
	{
		name      : 'isMyTaskOnly',
		type      : 'toggle',
		size      : 'sm',
		onLabel   : t('incidentManagement:toggle_label'),
		offLabel  : '',
		className : styles.toggle,
	},
];
