const allocation = [
	{
		api          : 'list_allocations',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_allocation_configurations',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_allocation_relations',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_allocation_requests',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_allocation_quotas',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'create_allocation_configuration',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'publish_allocation_configuration',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'create_allocation_preference',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'bulk_update_allocation_preferences',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'update_allocation_preference',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_segments',
		access_type  : 'private',
		service_name : 'segmentation',
	},
	{
		api          : 'check_allocation_configuration_publishability',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'update_allocation_configuration',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_allocation_instances',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_allocation_configuration_mutual_exclusions',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'delete_allocation_instance_job',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'create_allocation_relation',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'create_allocation_request',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'create_allocation_quota',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_auth_roles',
		access_type  : 'private',
		service_name : 'auth',
	},
	{
		api          : 'list_organizations',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_users',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_partners',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_partner_users',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_allocation_details',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'approve_allocation_details',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'update_allocation_detail',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'update_allocation_request',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'update_allocation_relation',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'update_allocation_quota',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'bulk_approve_allocation_relations',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'bulk_approve_allocation_request',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
];

export default allocation;
