const allocation = [
	{
		api          : 'configurations',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'relations',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'requests',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'quotas',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'configuration',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'configuration_status',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'preference',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'preference_bulk_status',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_segments',
		access_type  : 'private',
		service_name : 'segmentation',
	},
	{
		api          : 'configuration_check_publishability',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'configuration_attributes',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'instances',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'configuration_mutual_exclusions',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'relation',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'request',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'quota',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'list_auth_roles',
		access_type  : 'private',
		service_name : 'auth',
	},
	{
		api          : 'list_organizations',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_users',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_partners',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_partner_users',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'details',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'details_status',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'detail_stakeholder',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'request_status',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'relation_status',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'quota_attributes',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'relation_bulk_approve',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
	{
		api          : 'request_bulk_approve',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
];

export default allocation;
