const allocation = {
	allocation_engine: [
		{
			api          : 'get_allocation_configurations',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_relations',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_requests',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_quotas',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_configuration',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_configuration_status',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_preference',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_preference_bulk_status',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'list_segments',
			access_type  : 'private',
			service_name : 'segmentation',
		},
		{
			api          : 'post_allocation_configuration_check_publishability',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_configuration_attributes',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_instances',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_configuration_mutual_exclusions',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_relation',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_request',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_quota',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'list_auth_roles',
			access_type  : 'private',
			service_name : 'auth',
		},
		{
			api          : 'list_organizations',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_organization_users',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_partners',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'list_partner_users',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'get_allocation_details',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_details_status',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_detail_stakeholder',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_request_status',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_relation_status',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_quota_attributes',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_relation_bulk_approve',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_request_bulk_approve',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
	],
	kam_expertise: [
		{
			api          : 'get_allocation_kam_expertise_rules',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_badge_configuration',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_badge_configuration_list',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_badge_configuration_detail_attributes',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_configuration',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_configuration_levels',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_mastery_badge_configuration',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_configuration_attributes',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_event_configuration',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_event_configuration_name',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_configuration',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_event_configuration_attributes',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_event_configuration',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_dashboard',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_event_rule_mapping',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_stats_list',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_event_scoring',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_event_scoring_attribute',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_card_details',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_badge_name',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_publishability',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_kam_expertise_version_configurations',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_level_overview',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_rule_options',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_kam_expertise_event_group_name',
			access_type  : 'private',
			feature      : 'kam_expertise',
			service_name : 'allocation',
		},
	],
	crm_feedback_dashboard: [
		{
			api          : 'list_organizations',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_lead_organizations',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'list_partner_users',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'list_partners',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'get_allocation_feedbacks',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_feedback_requests',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_feedback_stats',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_feedback_request_stats',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_feedback_responses',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_feedback_request_status',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_feedback_request_bulk_create',
			access_type  : 'private',
			service_name : 'allocation',
		},
	],
	account_scoring: [
		{
			api          : 'post_allocation_engagement_scoring_settings_attributes',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_engagement_scoring_settings',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_engagement_distribution_settings_attributes',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_engagement_scoring_leaderboard',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_engagement_scoring_account_distribution_graph',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_engagement_scoring_account_stats',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'list_segments',
			access_type  : 'private',
			service_name : 'segmentation',
		},
		{
			api          : 'list_partner_users',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'list_organizations',
			access_type  : 'private',
			service_name : 'organization',
		},		{
			api          : 'get_allocation_engagement_scoring_event_configurations',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'post_allocation_engagement_scoring_event_configurations',
			access_type  : 'private',
			service_name : 'allocation',
		},

	],
};

export default allocation;
