const cogoLens = [
	{
		api          : 'get_detect',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'post_detect',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'catch_operations',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'service_predict',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'get_local_charges',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'submit_feedback',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'update_charge_code_mappings',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'shipment_data',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'recent_classified_shipment',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'search_classified_shipment',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'subscribe_fcm_topic',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'recent_notification',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'recent_unclassified_mail',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'update_shipment_cogoid',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'submit_user_feedback',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'update_user_feedback',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'give_consent',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'send_mail',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'outlook_scopes',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'reply_mail',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'reply_all',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'entity_stakeholder_mappings',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'outlook_authorization_url',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'add_outlook_account',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'forward_mail',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'create_draft_email',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'update_rpa_mail',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'detect_concor_doc',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'get_attachments',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'get_mail',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'detect',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'list_rpa_mails',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'get_rpa_mail',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
	{
		api          : 'list_mails',
		access_type  : 'private',
		feature      : 'cogolens',
		service_name : 'cogolens',
	},
];

export default cogoLens;
