const demand_crm = [
	{
		api          : 'get_organization_commodity_segmentation_stats',
		access_type  : 'parivate',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_document_handling_preference',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_partner_addresses',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_organization_document_handling_preference',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_document_handling_user_detail',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_document_handling_preference',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_additional_preference',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_additional_preference',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_additional_preference',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_invoice_preference',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_invoice_preference',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_invoice_preference',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_invoice_preferences',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_commodity_trade_port_pairs',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api         : 'list_lead_contacts',
		access_type : 'private',
	},
	{
		api          : 'list_contracts',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'contract',
	},
	{
		api          : 'get_domestic_contract',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'contract',
	},
	{
		api          : 'generate_contract_reference_id',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'contract',
	},
	{
		api          : 'create_contract',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'contract',
	},
	{
		api         : 'list_contracted_organizations',
		access_type : 'private',
		feature     : 'demand_crm',
	},

	{
		api          : 'get_organization_segment_trade_information',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_organizations_segmentation_stats',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_wallet_share_stats',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_stakeholders',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_stakeholder',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_partner_user_allocation',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_organization_billing_cycles',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_trade_party',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_trade_parties',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_billing_cycle',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_payment_modes',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_payment_mode',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_payment_mode',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_billing_cycle',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'convert_importer_exporter_to_channel_partner',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_organization_advanced_verification',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_advanced_verification',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_shipment_report_schedule',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'shipment',
	},
	{
		feature      : 'demand_crm',
		api          : 'list_organization_trade_parties',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_shipment_report_schedule',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'shipment',
	},
	{
		api          : 'create_organization_trade_party',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_trade_party_detail',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_poc',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},

	{
		api          : 'create_shipment_report',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'shipment',
	},
	{
		api          : 'get_organizations_trade_port_pairs',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_trade_information_on_port_pair',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_trade_intelligence',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_country_shipment_stats',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_business',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'business',
	},
	{
		api          : 'get_cogoscore_tax_numbers',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'business',
	},

	{
		api          : 'get_shipment_alert_stats',
		access_type  : 'private',
		feature      : 'credit',
		service_name : 'shipment',
	},
	{
		api          : 'list_shipments',
		access_type  : 'private',
		feature      : 'shipment',
		service_name : 'shipment',
	},
	{
		api          : 'list_organization_users',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_partners',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'partner',
	},
	{
		feature     : 'supply_crm',
		api         : 'list_partners',
		access_type : 'private',
	},
	{
		api          : 'list_organization_addresses',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_billing_addresses',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},

	{
		api          : 'list_organization_documents',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_audits',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_credit_requests',
		access_type  : 'private',
		feature      : 'credit',
		service_name : 'credit',
	},
	{
		api          : 'list_credit_allocations',
		access_type  : 'private',
		feature      : 'credit',
		service_name : 'credit',
	},
	{
		api          : 'list_trade_contacts',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'trade',
	},
	{
		api          : 'list_organizations',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_spot_searches',
		access_type  : 'private',
		feature      : 'search',
		service_name : 'spot_search',
	},
	{
		api          : 'list_fcl_freight_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'fcl_freight_rate',
	},
	{
		api          : 'list_lcl_freight_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'lcl_freight_rate',
	},
	{
		api          : 'list_air_freight_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'air_freight_rate',
	},
	{
		api          : 'list_ftl_freight_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'ftl_freight_rate',
	},
	{
		api          : 'list_ltl_freight_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'ltl_freight_rate',
	},
	{
		api          : 'list_haulage_freight_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'haulage_freight_rate',
	},
	{
		api          : 'list_fcl_customs_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'fcl_customs_rate',
	},
	{
		api          : 'list_lcl_customs_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'lcl_customs_rate',
	},
	{
		api          : 'list_air_customs_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'air_customs_rate',
	},
	{
		api          : 'list_fcl_cfs_rates',
		access_type  : 'private',
		feature      : 'rms',
		service_name : 'fcl_cfs_rate',
	},
	{
		api          : 'create_organization_address',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_billing_address',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'bulk_create_organization_document',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_forecasts',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'forecast',
	},
	{
		api          : 'create_forecast',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'forecast',
	},
	{
		api          : 'create_organization_document',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_document',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'create_trade_contact',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'trade',
	},
	{
		api          : 'create_organization_bulk_operation_sheet',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_address',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organizations',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'onboard_organization',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'send_organization_user_welcome_email',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_services',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'submit_organization_kyc',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_partner',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_organization_billing_address',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_user',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'check_duplicate_organization',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'check_organization_user_invitation_eligibility',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'migrate_organization_to_partner',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_cogo_entities',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_checkouts',
		access_type  : 'private',
		service_name : 'checkout',
	},
	{
		api          : 'list_organization_line_item_aliases',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_line_item_alias',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_rate_charge_codes',
		access_type  : 'private',
		service_name : 'rate_sheet',
	},
	{
		api          : 'create_organization_note',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_notes',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_stats',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_communication_logs',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_communication_logs_by_view',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_communication_log',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_branch',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_branch',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_user_branch',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_billing_address_branch',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_address_branch',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_branches',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_branch',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'assign_agents_with_filters',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_buckets_stats',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_user_access_requests',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_user_invitation',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_user_invitation',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_partner',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'partner',
	},
	{
		api          : 'remove_organization_stakeholder',
		access_type  : 'private',
		feature      : 'demand_crm',
		service_name : 'organization',
	},
	{
		feature      : 'demand_crm',
		api          : 'update_organization_finance_detail',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api         : 'create_feedback',
		access_type : 'private',
		feature     : 'feedback',
	},
	{
		api         : 'get_organization_communication_reminder_stats',
		access_type : 'private',
		feature     : 'organization',
	},
	{
		api          : 'create_outgoing_call',
		access_type  : 'private',
		service_name : 'voice_call',
	},
	{
		api          : 'hang_up_outgoing_call',
		access_type  : 'private',
		service_name : 'voice_call',
	},
	{
		api          : 'check_outgoing_call_status',
		access_type  : 'private',
		service_name : 'voice_call',
	},
	{
		api          : 'list_call_history',
		access_type  : 'private',
		service_name : 'voice_call',
	},
	{
		api          : 'create_voice_call_communication_logs',
		access_type  : 'private',
		service_name : 'voice_call',
	},
	{
		api          : 'create_allocation_relation',
		access_type  : 'private',
		feature      : 'allocation',
		service_name : 'allocation',
	},
];

export default demand_crm;
