const partner = {
	cogo_one: [
		{
			api          : 'get_communication',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_outlook_details',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'sync_rpa_email',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_firestore_custom_token',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'assign_meeting_agent',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_organization_trade_parties',
			access_type  : 'private',
			service_name : 'organization',
			feature      : 'trade_party',
		},
		{
			api          : 'create_organization_trade_party',
			access_type  : 'private',
			service_name : 'organization',
			feature      : 'trade_party',
		},
		{
			api          : 'create_organization_trade_party_poc',
			access_type  : 'private',
			service_name : 'organization',
			feature      : 'trade_party',
		},
		{
			api          : 'update_channel_partner_document',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'update_organization_document',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'update_onboarding_requests',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'assign_onboarding_agent',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_spot_searches',
			access_type  : 'private',
			feature      : 'rate_requests',
			service_name : 'spot_search',
		},
		{
			api          : 'update_video_conference_user_activity',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'verify_organization_kyc',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'verify_channel_partner_kyc',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'verify_organization_trade_party',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_omnichannel_onboarding_requests',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_omnichannel_onboarding_timelines',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'post_allocation_request_status',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'get_allocation_request_rejection_reasons',
			access_type  : 'private',
			feature      : 'allocation',
			service_name : 'allocation',
		},
		{
			api          : 'get_video_conference_link',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_video_conference',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_shipment_quotation',
			access_type  : 'private',
			service_name : 'shipment',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_fcl_freight_rate_local',
			access_type  : 'private',
			service_name : 'fcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_fcl_freight_rate',
			access_type  : 'private',
			service_name : 'fcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_haulage_freight_rate',
			access_type  : 'private',
			service_name : 'haulage_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_trailer_freight_rate',
			access_type  : 'private',
			service_name : 'trailer_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_lcl_freight_rate',
			access_type  : 'private',
			service_name : 'lcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_air_freight_rate',
			access_type  : 'private',
			service_name : 'air_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_ftl_freight_rate',
			access_type  : 'private',
			service_name : 'ftl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_ltl_freight_rate',
			access_type  : 'private',
			service_name : 'ltl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_fcl_cfs_rate',
			access_type  : 'private',
			service_name : 'fcl_cfs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_fcl_customs_rate',
			access_type  : 'private',
			service_name : 'fcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_lcl_customs_rate',
			access_type  : 'private',
			service_name : 'lcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'get_air_customs_rate',
			access_type  : 'private',
			service_name : 'air_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_rate_charge_codes',
			access_type  : 'private',
			service_name : 'rate_sheet',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_air_freight_rate_requests',
			access_type  : 'private',
			service_name : 'air_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_fcl_freight_rate_requests',
			access_type  : 'private',
			service_name : 'fcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_lcl_freight_rate_requests',
			access_type  : 'private',
			service_name : 'lcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_ftl_freight_rate_requests',
			access_type  : 'private',
			service_name : 'ftl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_ltl_freight_rate_requests',
			access_type  : 'private',
			service_name : 'ltl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_fcl_customs_rate_requests',
			access_type  : 'private',
			service_name : 'fcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_fcl_cfs_rate_requests',
			access_type  : 'private',
			service_name : 'fcl_cfs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_lcl_customs_rate_requests',
			access_type  : 'private',
			service_name : 'lcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_air_customs_rate_requests',
			access_type  : 'private',
			service_name : 'air_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_haulage_freight_rate_requests',
			access_type  : 'private',
			service_name : 'haulage_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_trailer_freight_rate_requests',
			access_type  : 'private',
			service_name : 'haulage_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_fcl_freight_rate_feedbacks',
			access_type  : 'private',
			service_name : 'fcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_lcl_freight_rate_feedbacks',
			access_type  : 'private',
			service_name : 'lcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_air_freight_rate_feedbacks',
			access_type  : 'private',
			service_name : 'air_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_ftl_freight_rate_feedbacks',
			access_type  : 'private',
			service_name : 'ftl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_ltl_freight_rate_feedbacks',
			access_type  : 'private',
			service_name : 'ltl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_fcl_customs_rate_feedbacks',
			access_type  : 'private',
			service_name : 'fcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_lcl_customs_rate_feedbacks',
			access_type  : 'private',
			service_name : 'lcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_trailer_freight_rate_feedbacks',
			access_type  : 'private',
			service_name : 'haulage_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_haulage_freight_rate_feedbacks',
			access_type  : 'private',
			service_name : 'haulage_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_air_customs_rate_feedbacks',
			access_type  : 'private',
			service_name : 'air_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_fcl_freight_rate_job',
			access_type  : 'private',
			service_name : 'fcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_lcl_freight_rate_job',
			access_type  : 'private',
			service_name : 'lcl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_lcl_customs_rate_job',
			access_type  : 'private',
			service_name : 'lcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_air_customs_rate_job',
			access_type  : 'private',
			service_name : 'air_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_trailer_freight_rate_job',
			access_type  : 'private',
			service_name : 'haulage_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_ltl_freight_rate_job',
			access_type  : 'private',
			service_name : 'ltl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_air_freight_rate_job',
			access_type  : 'private',
			service_name : 'air_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_haulage_freight_rate_job',
			access_type  : 'private',
			service_name : 'haulage_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_fcl_customs_rate_job',
			access_type  : 'private',
			service_name : 'fcl_customs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_ftl_freight_rate_job',
			access_type  : 'private',
			service_name : 'ftl_freight_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'update_fcl_cfs_rate_job',
			access_type  : 'private',
			service_name : 'fcl_cfs_rate',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_smt_rate_jobs',
			access_type  : 'private',
			service_name : 'communication',
			feature      : 'rate_requests',
		},
		{
			api          : 'list_organization_pocs',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'create_cogoone_group_hash',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_cogoone_group_members',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_cogoone_groups',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_communication_internal_chat',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_channel_partner_users',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'list_lead_users',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'list_channel_partners',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'list_lead_channel_partners',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'create_draft_reply_all_html',
			access_type  : 'private',
			service_name : 'cogolens',
		},
		{
			api          : 'create_draft_reply_html',
			access_type  : 'private',
			service_name : 'cogolens',
		},
		{
			api          : 'list_shipment_operating_procedures',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'create_shipment_operating_procedure',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'create_shipment_operating_instruction',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'get_shipment_operating_procedure',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'post_allocation_feedback',
			access_type  : 'private',
			service_name : 'allocation',
		},
		{
			api          : 'create_lead_organization_communication_log',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'create_lead_user',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'send_booking_note_on_whatsapp',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'submit_omnichannel_kyc',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_agent_feedback',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_checkouts',
			access_type  : 'private',
			service_name : 'checkout',
		},
		{
			api          : 'get_tickets_configuration_categories',
			access_type  : 'private',
			service_name : 'tickets',
		},
		{
			api          : 'get_user',
			access_type  : 'private',
			service_name : 'user',
		},
		{
			api          : 'create_organization_communication_log',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_organization_communication_logs',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization_cogopoint_profile',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'list_promotions',
			access_type  : 'private',
			service_name : 'promotion',
		},
		{
			api          : 'list_user_call_details',
			access_type  : 'private',
			service_name : 'voice_call',
		},
		{
			api          : 'update_voice_call_record',
			access_type  : 'private',
			service_name : 'voice_call',
		},
		{
			api          : 'update_agent_work_preference',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_omnichannel_note',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_omnichannel_notes',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_omnichannel_note',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_outgoing_call',
			access_type  : 'private',
			service_name : 'voice_call',
		},
		{
			api          : 'list_chat_suggestions',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'check_outgoing_call_status',
			access_type  : 'private',
			service_name : 'voice_call',
		},
		{
			api          : 'hang_up_outgoing_call',
			access_type  : 'private',
			service_name : 'voice_call',
		},
		{
			api          : 'get_omnichannel_activity_logs',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_agent_work_preference',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_suggestion',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'bulk_assign_chat',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'assign_chat',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_communication',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_omnichannel_customer_insights',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_assigned_chat',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_chat_agents',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_communication_templates',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_communication_template',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_communication_template',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_communication_platform_chat',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_lead_user',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'list_assigned_chat_tags',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_organizations',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'create_platform_chat_user_onboarding',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_partners',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'list_cogoone_timelines',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_omnichannel_documents',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_omnichannel_document',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'submit_organization_kyc',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'update_omnichannel_document_details',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_organization_document',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'send_user_whatsapp_template',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_user_room',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_partner_users',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'convert_importer_exporter_to_channel_partner',
			access_type  : 'private',
			service_name : 'partner',
		},
		{
			api          : 'list_user_chat_summary',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'request_assign_chat',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'post_tickets_activity',
			access_type  : 'private',
			service_name : 'tickets',
		},
		{
			api          : 'post_tickets_ticket',
			access_type  : 'private',
			service_name : 'tickets',
		},
		{
			api          : 'get_tickets_stats',
			access_type  : 'private',
			service_name : 'tickets',
		},
		{
			api          : 'get_tickets_list',
			access_type  : 'private',
			service_name : 'tickets',
		},
		{
			api          : 'check_customer_checkout_quotation_conflict',
			access_type  : 'private',
			service_name : 'checkout',
		},
		{
			api          : 'list_servetel_agents',
			access_type  : 'private',
			service_name : 'voice_call',
		},
		{
			api          : 'update_live_call',
			access_type  : 'private',
			service_name : 'voice_call',
		},
		{
			api          : 'list_shipment_flash_booking_rates',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'list_organization_users',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_operators',
			access_type  : 'private',
			service_name : 'operator',
		},
		{
			api          : 'update_shipment_flash_booking_rate',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'create_cogoone_timeline',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'escalate_supplier_to_rm',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_promotional_rate_communication',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'send_flash_rate_revert_notification_on_email',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_user_contact_request',
			access_type  : 'private',
			service_name : 'user',
		},
		{
			api          : 'list_shipment_pending_tasks',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'list_shipments',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'list_shipment_services',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'send_users_bulk_communication',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'send_shipment_document_notification',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_email_suggestions',
			access_type  : 'private',
			service_name : 'cogolens',
		},
		{
			api          : 'get_omnichannel_agent_types',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_available_service_providers',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_cogoone_flash_rates_logs',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_lead_organizations',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'get_lead_organization_users',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'list_assigned_chats',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_agent_work_preference',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_shipment_stakeholders',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'get_lead_organization',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'list_lead_organization_users',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'get_omnichannel_agent_stats',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_saas_subscription_profile',
			service_name : 'saas_subscriptions_v2',
			access_type  : 'private',
		},
		{
			api          : 'saas_get_active_plan_checkout_details',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'list_organization_billing_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_organization_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'create_organization_billing_address',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'create_organization_address',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'create_subscription_payment_link',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'create_subscription_generate_invoice',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'list_roles',
			access_type  : 'private',
			service_name : 'auth',
		},
		{
			api         : 'list_chat_channels',
			access_type : 'private',
		},
		{
			api         : 'update_chat_channel_seen',
			access_type : 'private',
		},
		{
			api         : 'create_chat_message',
			access_type : 'private',
		},
		{
			api         : 'update_chat_message',
			access_type : 'private',
		},
		{
			api         : 'get_chat_channel',
			access_type : 'private',
		},
		{
			api          : 'sync_agent_work_preference',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_shipment_trade_partners',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'update_shipment_primary_poc',
			access_type  : 'private',
			service_name : 'shipment',
		},
		{
			api          : 'onboard_lead_organization',
			access_type  : 'private',
			service_name : 'lead',
		},
		{
			api          : 'list_cogoone_shifts',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_bulk_cogoone_shift',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_bulk_cogoone_shift',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_platform_config_constants',
			access_type  : 'private',
			service_name : 'platform_config',
		},
		{
			api          : 'list_cogoone_shifts',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'create_cogoone_calendar',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_cogoone_schedules',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_cogoone_schedule',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'list_cogoone_calendars',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_cogoone_calendar',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'update_communication_template',
			access_type  : 'private',
			service_name : 'communication',
		},
		{
			api          : 'get_organization_services',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_shipment',
			access_type  : 'private',
			service_name : 'bookings',
		},
	],
};

export default partner;
