const apis = [
	{
		api          : 'create_rfq',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'get_rfq_search',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'create_rfq_checkouts',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'list_rfqs',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'create_spot_search_checkout',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'spot_search',
	},
	{
		api          : 'update_rfq',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'remove_rfq_search',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'get_rfq',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'add_rfq_search_block',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'rfq',
	},
	{
		api          : 'create_spot_search_service',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'spot_search',
	},
	{
		api          : 'update_spot_search',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'spot_search',
	},
	{
		api          : 'get_organization',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'organization',
	},
	{
		api          : 'list_organizations',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_users',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'organization',
	},
	{
		api          : 'list_partner_users',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'partner',
	},
	{
		api          : 'list_organization_invoicing_parties',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_billing_address',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_billing_address',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'organization',
	},
	{
		api          : 'get_checkout',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'checkout',
	},
	{
		api          : 'update_checkout',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'checkout',
	},
	{
		api          : 'send_checkout_quotation_emails',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'checkout',
	},
	{
		api          : 'update_checkout_margin',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'checkout',
	},
	{
		api          : 'update_checkout_customize_quotation',
		access_type  : 'private',
		feature      : 'rfq',
		service_name : 'checkout',
	},
	{
		api          : 'send_booking_whatsapp_confirmation',
		access_type  : 'private',
		feature      : 'search',
		service_name : 'checkout',
	},
];
export default apis;
