const saas = {
	app_saas_tracking: [
		{
			api          : 'get_saas_container_subscription',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_shipment_details',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_update_saas_container_alert',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_shipment_poc',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_saas_container_alert',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_list_of_master_alerts',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_container_alerts',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'dismiss_saas_container_alert',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_saas_subscription_container_details',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_saas_shipment_details',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'callback_container_tracking',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_plan',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_subscription_container_details',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_subscription_poc_details',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_dsr',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'update_dsr_to_subscription_mapping',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_container_subscriptions',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'update_saas_dsr',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'send_dsr_mail',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_user_quota_usage',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'get_shipping_line_for_container_no',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_saas_container_shipping_lines',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_container_subscription',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'deactivate_saas_container_subscription',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_container_subscription_share',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_subscription_poc',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_store_quota',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'update_saas_store_quota',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_saas_container_alert',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'update_saas_container_alert',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_product_family',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_checkout',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_create_subscription_checkout',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_update_checkout',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_create_subscription',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_subscription_callback',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_dashboard',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_subscription_status',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_create_callback_for_plan_inquiry',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_organization_billing_address',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_organization_billing_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'create_saas_container_tracker_via_csv',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'unarchive_saas_container_subscription',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_saas_container_subscription_shared_details',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
	],
	app_saas_air_tracking: [
		{
			api          : 'create_saas_air_subscription',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'get_saas_air_subscription',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'create_saas_air_shipment_details',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'create_saas_air_shipment_poc',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'create_saas_air_subscription_poc',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'create_saas_air_subscription_share',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'create_saas_air_timeline',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'deactivate_saas_air_subscription',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'get_saas_air_shipment_details',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'get_saas_air_subscription_shared_details',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'get_saas_air_timeline',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'list_saas_air_subscriptions',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'list_saas_air_subscription_poc_details',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'get_airline_from_airway_bill',
			access_type  : 'private',
			service_name : 'operator',
		},
		{
			api          : 'create_update_saas_air_alert',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'unarchive_saas_air_subscription',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'saas_get_user_quota_usage',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'create_saas_air_tracker_via_csv',
			access_type  : 'private',
			service_name : 'air_tracking',
		},
		{
			api          : 'list_saas_store_quota',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
	],
	app_saas_map_tracking: [
		{
			api          : 'list_all_subscriptions',
			access_type  : 'public',
			service_name : 'air_tracking',
		},
		{
			api          : 'get_container_sea_route',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
	],
	app_saas_subscriptions: [
		{
			api          : 'saas_get_user_active_plan',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_create_subscription',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_checkout',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_dashboard',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_store_quota',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_product_family',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_subscription_status',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_update_checkout',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_subscription_callback',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_create_callback_for_plan_inquiry',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_order_details',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_usage_history',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'list_organization_billing_addresses',
			access_type  : 'public',
			service_name : 'organization',
		},
		{
			api          : 'create_organization_billing_address',
			access_type  : 'public',
			service_name : 'organization',
		},
		{
			api          : 'saas_get_user_quota_usage',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_milestone_status',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_deactivate_subscription',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_user_subscription_status',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_complete_order',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_payment_method',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_checkout_item',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_delete_checkout_item',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_create_checkout_items',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'list_organization_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
	],
	app_saas_schedules: [
		{
			api          : 'create_sailing_schedule_subscription',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'delete_sailing_schedule_subscription',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'list_sailing_schedule_subscriptions',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'get_sailing_schedule_scraping_job',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'create_sailing_schedule_scraping',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'create_sailing_schedule',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'list_sailing_schedule_port_pairs',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'create_sailing_schedule_port_pair',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'get_sailing_schedule_port_pair_coverages',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'update_sailing_schedule_port',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'get_sailing_schedules',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'update_sailing_schedule_port_pair_coverage',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
		{
			api          : 'create_sailing_schedule_port_pair_coverage',
			access_type  : 'private',
			service_name : 'sailing_schedule',
		},
	],
	app_saas_air_schedules: [
		{
			api          : 'create_saas_air_schedule_subscription',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'list_saas_air_schedule_subscription',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'get_saas_air_schedule_subscription',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'delete_saas_air_schedule_subscription',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'create_saas_air_schedule',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'create_saas_air_schedule_airport_pair',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'list_saas_store_quota',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_saas_air_schedule',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'get_saas_air_schedule_port_pair_coverage',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'list_saas_air_schedule_airport_pairs',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'create_saas_air_connection',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'create_saas_air_schedule_airport',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
		{
			api          : 'list_saas_air_schedule_subscription',
			access_type  : 'private',
			service_name : 'saas_air_schedules',
		},
	],
	app_saas_dsr: [
		{
			api          : 'create_saas_dsr',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_dsr_to_subscription_mapping',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'create_dsr_schedule',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'update_dsr_schedule',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_dsr',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'get_dsr_to_subscription_mapping',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_subscription_poc_details',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_container_subscriptions',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'update_saas_dsr',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
	],
	app_saas_freight_rate_trend: [
		{
			api          : 'get_freight_trend_subscription',
			access_type  : 'private',
			service_name : 'freight_trend',
		},
		{
			api          : 'list_freight_trend_subscriptions',
			access_type  : 'private',
			service_name : 'freight_trend',
		},
		{
			api          : 'list_freight_trend_rates',
			access_type  : 'private',
			service_name : 'freight_trend',
		},
		{
			api          : 'create_freight_trend_rate',
			access_type  : 'private',
			service_name : 'freight_trend',
		},
		{
			api          : 'create_freight_trend_subscription',
			access_type  : 'private',
			service_name : 'freight_trend',
		},
		{
			api          : 'list_saas_store_quota',
			access_type  : 'private',
			service_name : 'saas_traceability',
		},
		{
			api          : 'delete_freight_trend_subscription',
			access_type  : 'private',
			service_name : 'freight_trend',
		},
	],
	app_saas_cpq_products: [
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_cpq_contacts: [
		{
			api          : 'list_organizations',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_cpq_dashboard    : [],
	app_saas_create_quotation : [
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'update_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_edit_quotation: [
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'update_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_view_quotation  : [],
	app_saas_quotation_list  : [],
	app_saas_create_purchase : [
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'update_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_edit_purchase: [
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'update_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_view_purchase  : [],
	app_saas_purchase_list  : [],
	app_saas_create_invoice : [
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'update_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_edit_invoice: [
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'update_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_organization_search_history',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
	],
	app_saas_view_invoice  : [],
	app_saas_invoice_list  : [],
	app_saas_app_quotation : [
		{
			api          : 'get_recommended_spot_searches',
			access_type  : 'private',
			feature      : 'search',
			service_name : 'spot_search',
		},
		{
			api          : 'list_organizations',
			access_type  : 'public',
			service_name : 'organization',
		},
		{
			api         : 'post_saas_quote',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'put_saas_quote',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api          : 'create_organization_billing_address',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api         : 'put_saas_organization_set_seller_address',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_product_category',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_product_category_list',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_pdf',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api          : 'list_organization_billing_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api         : 'put_saas_quote',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_quote_list',
			access_type : 'private',
			module      : 'QuotationList',
			feature     : 'QuotationList',
		},
		{
			api         : 'get_saas_quote',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_quote_send',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_quote_draft',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_organization',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_organization_list',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_organization_partner_summary_list',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_product',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_product_list',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'delete_saas_product',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'delete_saas_organization_partner',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'patch_saas_product_item_price',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api          : 'get_exchange_rate',
			access_type  : 'private',
			service_name : 'exchange_rate',
		},
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			service_name : 'spot_search',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'public',
			service_name : 'spot_search',
		},
		{
			api          : 'get_sailing_schedules',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api         : 'get_saas_quote_summary',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'delete_saas_quote',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_organization_buyer',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_organization_partner_list',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_hs_code_hs_mapping',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_hs_code_list',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_hs_code_countries',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_section',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_heading',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_search',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api          : 'saas_get_user_quota_usage',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api         : 'get_saas_bill_status',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_trade_engine_draft',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_trade_engine_draft',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_trade_engine_service_rates',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_trade_engine_hs_engine',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_payment',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'post_saas_trade_engine',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_trade_engine',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_quote_received_list',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_trade_engine_pdf',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'put_saas_product_update_hscode',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'get_saas_bill_product_codes',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
		{
			api         : 'put_saas_quote_update_duties',
			access_type : 'private',
			module      : 'Quotation',
			feature     : 'Quotation',
		},
	],
	app_saas_cogopoint: [
		{
			api          : 'get_organization_cogopoint_profile',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'list_cogopoint_milestones',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'get_cogopoint_user_profile',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'get_cogopoint_history_detail',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'get_cogopoint_user_dashboard',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'list_user_cogopoint_histories',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'list_cogopoint_earnables',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
		{
			api          : 'list_cogopoint_ledgers',
			access_type  : 'private',
			service_name : 'cogopoint',
		},
	],
	app_saas_transaction_history: [
		{
			api         : 'get_saas_payment_details',
			access_type : 'private',
			module      : 'transactionHistory',
			feature     : 'transactionHistory',
		},
		{
			api         : 'get_saas_payment_history',
			access_type : 'private',
			module      : 'transactionHistory',
			feature     : 'transactionHistory',
		},
		{
			api         : 'get_saas_pdf_bill',
			access_type : 'private',
			module      : 'transactionHistory',
			feature     : 'transactionHistory',
		},
		{
			api         : 'get_saas_trade_engine',
			access_type : 'private',
			module      : 'transactionHistory',
			feature     : 'transactionHistory',
		},
		{
			api         : 'get_saas_trade_engine_pdf',
			access_type : 'private',
			module      : 'transactionHistory',
			feature     : 'transactionHistory',
		},
	],
	app_saas_hs_code_list: [
		{
			api         : 'get_saas_hs_code',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_section',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_heading',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_favourites',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_search',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'post_saas_hs_code_favourites',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'delete_saas_hs_code_favourites',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'post_saas_transaction_transaction_engine',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_hs_code_countries',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'get_saas_product_category',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
		{
			api         : 'post_saas_product',
			access_type : 'private',
			module      : 'hsCode',
			feature     : 'hsCode',
		},
	],
	app_saas_cogo_subscription: [
		{
			api          : 'saas_get_user_active_plan',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_create_subscription',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_checkout',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_dashboard',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'list_saas_store_quota',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_product_family',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_subscription_status',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_update_checkout',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_subscription_callback',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_create_callback_for_plan_inquiry',
			access_type  : 'public',
			service_name : 'saas_traceability',
		},
		{
			api          : 'saas_get_order_details',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_usage_history',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'list_organization_billing_addresses',
			access_type  : 'public',
			service_name : 'organization',
		},
		{
			api          : 'create_organization_billing_address',
			access_type  : 'public',
			service_name : 'organization',
		},
		{
			api          : 'saas_get_user_quota_usage',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_milestone_status',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_deactivate_subscription',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_user_subscription_status',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_complete_order',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_payment_method',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_checkout_item',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_delete_checkout_item',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_create_checkout_items',
			access_type  : 'public',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_plan_details',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'saas_get_plan_features',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'subscription_activate_now',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'create_organization_address',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_coupons',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'update_saas_checkout',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'list_organization_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
	],
	app_saas_insurance: [
		{
			api          : 'get_exchange_rate',
			access_type  : 'private',
			service_name : 'exchange_rate',
		},
		{
			api          : 'list_organization_billing_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api         : 'get_saas_bill_status',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'post_saas_insurance',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_list_commodities',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_rate',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'post_saas_insurance_checkout',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'post_saas_insurance_draft',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_list',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'post_saas_payment',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_details',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_list_summary',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_pdf',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_draft_details',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_list_countries',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api          : 'list_locations',
			access_type  : 'public',
			service_name : 'location',
		},
		{
			api         : 'get_saas_insurance_terms',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api         : 'get_saas_insurance_cancel',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
		{
			api          : 'create_organization_billing_address',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'create_organization_address',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api          : 'list_organization_addresses',
			access_type  : 'private',
			service_name : 'organization',
		},
		{
			api         : 'get_saas_faq',
			access_type : 'private',
			module      : 'insurance',
			feature     : 'insurance',
		},
	],
	app_saas_trade_partner: [
		{
			api         : 'delete_saas_organization_partner',
			access_type : 'private',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
		{
			api         : 'get_saas_organization_partner_list',
			access_type : 'private',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
		{
			api         : 'post_saas_organization_buyer',
			access_type : 'private',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
		{
			api         : 'put_saas_organization',
			access_type : 'private',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
		{
			api         : 'put_saas_organization_archive',
			access_type : 'private',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
		{
			api         : 'put_saas_organization_unarchive',
			access_type : 'private',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
		{
			api         : 'put_saas_organization_archive',
			access_type : 'private',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
		{
			api         : 'get_saas_organization_export',
			access_type : 'public',
			module      : 'trade-partner',
			feature     : 'trade-partner',
		},
	],
	app_saas_product_inventory: [
		{
			api         : 'put_saas_product_archive',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product_category',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product_top_products',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_hs_code_section',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_hs_code_heading',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_hs_code',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product_category_list',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product_list',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'post_saas_product',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product_top_list',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product_total_revenue',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'put_saas_product_unarchived',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_hs_code_countries',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'put_saas_product_unarchive',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'delete_saas_product',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'put_saas_product',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'post_saas_product_bulk_product_upload',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_product_export',
			access_type : 'public',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_error_export',
			access_type : 'public',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'post_saas_product_bulk_products_upload',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
		{
			api         : 'get_saas_hs_code_search',
			access_type : 'private',
			module      : 'product',
			feature     : 'product',
		},
	],
	app_saas_premium_services: [
		{
			api         : 'get_sailing_schedules',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api          : 'get_exchange_rate',
			access_type  : 'private',
			module       : 'dutiesTaxes',
			feature      : 'dutiesTaxes',
			service_name : 'exchange_rate',
		},
		{
			api         : 'saas_get_user_quota_usage',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_bill_status',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api          : 'get_exchange_rate',
			access_type  : 'private',
			module       : 'dutiesTaxes',
			feature      : 'dutiesTaxes',
			service_name : 'exchange_rate',
		},
		{
			api         : 'post_saas_trade_engine_duties_draft',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_trade_engine_draft',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'saas_get_user_quota_usage',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'post_saas_payment',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_trade_engine',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'post_saas_trade_engine',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'post_saas_trade_engine_hs_engine',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_hs_code_section',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_hs_code_heading',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_hs_code',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_product_category_list',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_product_list',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_hs_code_countries',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api          : 'get_spot_search',
			access_type  : 'private',
			module       : 'dutiesTaxes',
			feature      : 'dutiesTaxes',
			service_name : 'spot_search',
		},
		{
			api          : 'create_spot_search',
			access_type  : 'private',
			module       : 'dutiesTaxes',
			feature      : 'dutiesTaxes',
			service_name : 'spot_search',
		},
		{
			api         : 'get_saas_trade_engine_service_rates',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_trade_engine_verify_six_digit',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_hs_code_search',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
		{
			api         : 'get_saas_bill_product_codes',
			access_type : 'private',
			module      : 'dutiesTaxes',
			feature     : 'dutiesTaxes',
		},
	],
	app_saas_trader_eligibilty_check: [
		{
			api         : 'saas_get_user_quota_usage',
			access_type : 'private',
		},
		{
			api         : 'get_saas_bill_status',
			access_type : 'private',
			module      : 'trader-eligibility-check',
			feature     : 'trader-eligibility-check',
		},
		{
			api         : 'get_saas_trade_engine_service_rates',
			access_type : 'private',
			module      : 'trader-eligibility-check',
			feature     : 'trader-eligibility-check',
		},
		{
			api          : 'list_locations',
			access_type  : 'private',
			service_name : 'location',
		},
		{
			api         : 'get_saas_trade_engine',
			access_type : 'private',
			module      : 'trader-eligibility-check',
			feature     : 'trader-eligibility-check',
		},
		{
			api         : 'post_saas_payment',
			access_type : 'private',
			module      : 'trader-eligibility-check',
			feature     : 'trader-eligibility-check',
		},
		{
			api         : 'post_saas_trade_engine',
			access_type : 'private',
			module      : 'trader-eligibility-check',
			feature     : 'trader-eligibility-check',
		},
		{
			api         : 'post_saas_trade_engine_screening_draft',
			access_type : 'private',
			module      : 'trader-eligibility-check',
			feature     : 'trader-eligibility-check',
		},
		{
			api         : 'get_saas_bill_product_codes',
			access_type : 'private',
			module      : 'trader-eligibility-check',
			feature     : 'trader-eligibility-check',
		},
	],
	app_saas_order_history: [
		{
			api         : 'get_saas_trade_engine',
			access_type : 'private',
			module      : 'order-history',
			feature     : 'order-history',
		},
		{
			api         : 'get_saas_trade_engine_order_history',
			access_type : 'private',
			module      : 'order-history',
			feature     : 'order-history',
		},
	],
	app_saas_import_export_doc: [
		{
			api          : 'saas_get_user_quota_usage',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api          : 'get_saas_bill_status',
			access_type  : 'private',
			service_name : 'saas_subscriptions_v2',
		},
		{
			api         : 'post_saas_trade_engine_documents_draft',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'get_saas_bill_product_codes',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'get_saas_trade_engine_service_rates',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'post_saas_payment',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'get_saas_trade_engine',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'post_saas_trade_engine',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'get_saas_trade_engine_verify_six_digit',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'post_saas_trade_engine_hs_engine',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'get_saas_trade_engine_pdf',
			access_type : 'private',
			module      : 'import-export-documents',
			feature     : 'import-export-documents',
		},
		{
			api         : 'get_saas_product_category_list',
			access_type : 'private',
			module      : 'product-catalogue',
			feature     : 'product-catalogue',
		},
		{
			api         : 'get_saas_product_list',
			access_type : 'private',
			module      : 'product-catalogue',
			feature     : 'product-catalogue',
		},
		{
			api         : 'get_saas_hs_code_section',
			access_type : 'private',
			module      : 'product-catalogue',
			feature     : 'product-catalogue',
		},
		{
			api         : 'get_saas_hs_code_heading',
			access_type : 'private',
			module      : 'product-catalogue',
			feature     : 'product-catalogue',
		},
		{
			api         : 'get_saas_hs_code',
			access_type : 'private',
			module      : 'product-catalogue',
			feature     : 'product-catalogue',
		},
		{
			api         : 'get_saas_hs_code_search',
			access_type : 'private',
			module      : 'product-catalogue',
			feature     : 'product-catalogue',
		},
		{
			api         : 'get_saas_hs_code_countries',
			access_type : 'private',
			module      : 'product-catalogue',
			feature     : 'product-catalogue',
		},
	],

	app_saas_cogostore: [
		{
			api         : 'list_cogostore_voucher_brands',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'create_cogostore_cart_item',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'list_cogostore_products',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'get_cogostore_product',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'list_cogostore_product_categories',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'get_cogostore_cart',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'update_cogostore_cart_items',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'update_cogostore_cart_item',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'book_cogostore_cart',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'list_cogostore_orders',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'get_cogostore_order',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'list_cogostore_banners',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'send_cogostore_communication',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'get_cogostore_filters',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},
		{
			api         : 'list_cogostore_brands',
			access_type : 'private',
			module      : 'cogo-store',
			feature     : 'cogo-store',
			service_name : 'cogopoint',
		},	
	],

};
export default saas;
