const supply_crm = [
	{
		api          : 'onboard_channel_partner_user',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_channel_partner_user_status',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_organization_user',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'create_partner_user_allocation',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_channel_partner',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_channel_partner_verification',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'create_channel_partner_document',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'submit_channel_partner_kyc',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_partner_user_invitations',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'list_organization_stakeholders',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_stakeholder',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_partner_user_invitation',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_channel_partner_user',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_channel_partner_users',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'resend_channel_partner_user_verification_email',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'verify_channel_partner_user_mobile',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_channel_partner_documents',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'create_channel_partner_bank_details',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'create_channel_partner_billing_address',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_channel_partner_organization',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_organization_advanced_verification',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_advanced_verification',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'get_service_provider_lifecycle_stats',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'get_organization',
		access_type  : 'private',
		service_name : 'organization',
	},

	{
		feature      : 'supply_crm',
		api          : 'get_business',
		access_type  : 'private',
		service_name : 'business',
	},
	{
		api          : 'get_cogoscore_tax_numbers',
		access_type  : 'private',
		feature      : 'supply_crm',
		service_name : 'business',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organization_trade_parties',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'check_duplicate_organization',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'get_shipment_alert_stats',
		access_type  : 'private',
		service_name : 'shipment',
	},
	{
		feature      : 'supply_crm',
		api          : 'get_organization_services',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_shipment_services',
		access_type  : 'private',
		service_name : 'shipment',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_shipments',
		access_type  : 'private',
		service_name : 'shipment',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organization_users',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_partners',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_partner_users',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organization_addresses',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organization_billing_addresses',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organization_documents',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_trade_party',
		access_type  : 'private',
		feature      : 'supply_crm',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_poc',
		access_type  : 'private',
		feature      : 'supply_crm',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organization_audits',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_credit_requests',
		access_type  : 'private',
		service_name : 'credit',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_credit_allocations',
		access_type  : 'private',
		service_name : 'credit',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_trade_contacts',
		access_type  : 'private',
		service_name : 'trade',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organizations',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_spot_negotiations',
		access_type  : 'private',
		service_name : 'spot_negotiation',
	},
	{
		feature      : 'supply_crm',
		api          : 'create_organization_address',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'create_organization_billing_address',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'create_organization_document',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization_document',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_trade_party_finance_detail',
		access_type  : 'private',
		feature      : 'supply_crm',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization_trade_party_detail',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_trade_party',
		access_type  : 'private',
		feature      : 'supply_crm',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'create_trade_contact',
		access_type  : 'private',
		service_name : 'trade',
	},
	{
		feature      : 'supply_crm',
		api          : 'get_service_provider_stats',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'create_organization_bulk_operation_sheet',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization_finance_detail',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'create_organization_approval',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization_address',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization_service',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organizations',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'onboard_organization',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'send_organization_user_welcome_email',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'get_organization_services',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'submit_organization_kyc',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'get_partner',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization_billing_address',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_branch',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_branch',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_user_branch',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'update_organization_billing_address_branch',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_branches',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_branch',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_note',
		access_type  : 'private',
		feature      : 'supply_crm',
		service_name : 'organization',
	},
	{
		api          : 'list_organization_notes',
		access_type  : 'private',
		feature      : 'supply_crm',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'create_organization_communication_log',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'list_organization_communication_logs',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		feature      : 'supply_crm',
		api          : 'update_organization_document',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'onboard_channel_partner',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_channel_partner',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'create_channel_partner_bank_details',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_channel_partner_bank_details',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_business',
		access_type  : 'private',
		service_name : 'business',
	},
	{
		api          : 'validate_channel_partner_registration_number',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_cogoscore_tax_numbers',
		access_type  : 'private',
		service_name : 'business',
	},
	{
		api          : 'update_channel_partner_buy_services',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_channel_partner_sell_services',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_organization_trade_service_mapping_status',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_channel_partner_buy_services',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'get_channel_partner_sell_services',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_organization_service',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_organization_services',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'get_channel_partner_addresses',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'create_channel_partner_address',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api          : 'update_channel_partner_address',
		access_type  : 'private',
		service_name : 'partner',
	},
	{
		api         : 'generate_mobile_verification_link',
		access_type : 'private',
	},
	{
		api         : 'send_mobile_verification_email',
		access_type : 'private',
	},
	{
		api          : 'check_organization_user_invitation_eligibility',
		access_type  : 'private',
		service_name : 'organization',
	},
	{
		api          : 'create_organization_document_inventory_record',
		access_type  : 'private',
		service_name : 'organization',
		feature      : 'inventory_management',
	},
	{
		api          : 'list_organization_document_inventory',
		access_type  : 'private',
		service_name : 'organization',
		feature      : 'inventory_management',
	},
	{
		api          : 'update_organization_document_inventory',
		access_type  : 'private',
		service_name : 'organization',
		feature      : 'inventory_management',
	},
	{
		api          : 'update_organization_document_inventory_record',
		access_type  : 'private',
		service_name : 'organization',
		feature      : 'inventory_management',
	},
	{
		api          : 'list_organization_document_inventory_record',
		access_type  : 'private',
		service_name : 'organization',
		feature      : 'inventory_management',
	},
];

export default supply_crm;
