export const commodityOptions = [
	{ label: 'Agri Products', value: 'agri_products' },
	{
		label : 'Animal Products Except Meat',
		value : 'animal_products_except_meat',
	},
	{ label: 'Automobiles Parts', value: 'automobiles_parts' },
	{ label: 'Books', value: 'books' },
	{ label: 'Building Materials', value: 'building_materials' },
	{ label: 'Cement', value: 'cement' },
	{ label: 'Chemicals', value: 'chemicals' },
	{ label: 'Coal', value: 'coal' },
	{ label: 'Coal And Ash', value: 'coal_and_ash' },
	{ label: 'Consumer Durables', value: 'consumer_durables' },
	{ label: 'Cotton Finished Products', value: 'cotton_finished_products' },
	{ label: 'Cotton Raw', value: 'cotton_raw' },
	{ label: 'Daily Essentials', value: 'daily_essentials' },
	{ label: 'Electronics', value: 'electronics' },
	{ label: 'Fertilizers', value: 'fertilizers' },
	{ label: 'FMCG', value: 'fmcg' },
	{ label: 'Food Products', value: 'food_products' },
	{ label: 'Frigate Steel', value: 'frigate_steel' },
	{ label: 'Fruits Vegetables', value: 'fruits_vegetables' },
	{ label: 'Furniture', value: 'furniture' },
	{ label: 'Gas', value: 'gas' },
	{ label: 'Household Goods', value: 'household_goods' },
	{ label: 'Iron Ore', value: 'iron_ore' },
	{ label: 'Iron Pallets', value: 'iron_pallets' },
	{ label: 'Jute Finished Products', value: 'jute_finished_products' },
	{ label: 'Jute Raw', value: 'jute_raw' },
	{ label: 'Leather Finished Products', value: 'leather_finished_products' },
	{ label: 'Leather Raw', value: 'leather_raw' },
	{ label: 'Liquid Chemicals', value: 'liquid_chemicals' },
	{ label: 'Liquids Consumables', value: 'liquids_consumables' },
	{ label: 'Live Animals', value: 'live_animals' },
	{ label: 'Machinery New', value: 'machinery_new' },
	{ label: 'Machinery Old', value: 'machinery_old' },
	{ label: 'Medical Materials', value: 'medical_materials' },
	{ label: 'Medical Supplies', value: 'medical_supplies' },
	{ label: 'Medicines Materials', value: 'medicines_materials' },
	{ label: 'Metal', value: 'metal' },
	{ label: 'Metal Finished Products', value: 'metal_finished_products' },
	{ label: 'Minerals', value: 'minerals' },
	{ label: 'Not Available', value: 'not_available' },
	{ label: 'Others', value: 'others' },
	{ label: 'Paper Bales', value: 'paper_bales' },
	{ label: 'Paper Rolls', value: 'paper_rolls' },
	{ label: 'Petroleum', value: 'petroleum' },
	{ label: 'Plastic Finished Products', value: 'plastic_finished_products' },
	{ label: 'Plastic Raw', value: 'plastic_raw' },
	{ label: 'Powder', value: 'powder' },
	{ label: 'Pre Packed Food', value: 'pre_packed_food' },
	{ label: 'Refrigerated Goods', value: 'refrigerated_goods' },
	{ label: 'Rubber', value: 'rubber' },
	{ label: 'Standard Commodity', value: 'standard_commodity' },
	{ label: 'Wood Finished Furniture', value: 'wood_finished_furniture' },
	{ label: 'Wood Raw', value: 'wood_raw' },
];
