export const stateCodeOptions = [
	{ label: 'Andaman and Nicobar Islands - AN', value: 'AN' },
	{ label: 'Andhra Pradesh - AP', value: 'AP' },
	{ label: 'Arunachal Pradesh - AR', value: 'AR' },
	{ label: 'Assam - AS', value: 'AS' },
	{ label: 'Bharat For pan-India registration - BH', value: 'BH' },
	{ label: 'Bihar - BR', value: 'BR' },
	{ label: 'Chandigarh - CH', value: 'CH' },
	{ label: 'Chhattisgarh - CG', value: 'CG' },
	{ label: 'Dadra and Nagar Haveli and Daman and Diu - DD', value: 'DD' },
	{ label: 'Delhi - DL', value: 'DL' },
	{ label: 'Goa - GA', value: 'GA' },
	{ label: 'Gujarat - GJ', value: 'GJ' },
	{ label: 'Haryana - HR', value: 'HR' },
	{ label: 'Himachal Pradesh - HP', value: 'HP' },
	{ label: 'Jammu and Kashmir - JK', value: 'JK' },
	{ label: 'Jharkhand - JH', value: 'JH' },
	{ label: 'Karnataka - KA', value: 'KA' },
	{ label: 'Kerala - KL', value: 'KL' },
	{ label: 'Ladakh - LA', value: 'LA' },
	{ label: 'Lakshadweep - LD', value: 'LD' },
	{ label: 'Madhya Pradesh - MP', value: 'MP' },
	{ label: 'Maharashtra - MH', value: 'MH' },
	{ label: 'Manipur - MN', value: 'MN' },
	{ label: 'Meghalaya - ML', value: 'ML' },
	{ label: 'Mizoram - MZ', value: 'MZ' },
	{ label: 'Nagaland - NL', value: 'NL' },
	{ label: 'Odisha - OD', value: 'OD' },
	{ label: 'Puducherry - PY', value: 'PY' },
	{ label: 'Punjab - PB', value: 'PB' },
	{ label: 'Rajasthan - RJ', value: 'RJ' },
	{ label: 'Sikkim - SK', value: 'SK' },
	{ label: 'Tamil Nadu - TN', value: 'TN' },
	{ label: 'Telangana - TS', value: 'TS' },
	{ label: 'Tripura - TR', value: 'TR' },
	{ label: 'Uttar Pradesh - UP', value: 'UP' },
	{ label: 'Uttarakhand - UK', value: 'UK' },
	{ label: 'West Bengal - WB', value: 'WB' },
];
