import GLOBAL_CONSTANTS from '@cogoport/globalization/constants/globals';

export const cardControls = [
	{
		name        : 'truck_number',
		label       : 'Truck Number',
		span        : 2.25,
		className   : 'primary md',
		type        : 'text',
		placeholder : 'Enter Truck Number',
		disabled    : true,
		rules       : { required: 'Truck Number is required' },
	},
	{
		name        : 'mobile_number',
		label       : 'Contact Number',
		span        : 2.25,
		className   : 'primary md',
		type        : 'text',
		placeholder : 'Enter Contact Number',
		disabled    : true,
		rules       : { required: 'Mobile number is required' },
	},
	{
		name      : 'vendor',
		label     : 'Vendor',
		span      : 1.5,
		className : 'primary md',
		type      : 'select',
		options   : [
			{
				label : 'HPCL',
				value : 'hpcl',
			},
		],
		placeholder : 'Enter Vendor',
		rules       : { required: 'Vendor is required' },
	},
	{
		name        : 'ath_amount',
		label       : 'ATH Amount',
		span        : 1.5,
		className   : 'primary md',
		type        : 'number',
		placeholder : 'Enter ATH Amount',
		disabled    : true,
		rules       : { required: 'Ath amount is required' },
	},
	{
		name        : 'fuel_amount',
		label       : 'Fuel Amount',
		span        : 1.5,
		className   : 'primary md',
		type        : 'number',
		placeholder : 'Enter Fuel Amount',
		disabled    : true,
		rules       : { required: 'Fuel amount is required' },
	},
	{
		name        : 'input_amount',
		label       : 'Amount',
		span        : 1.5,
		className   : 'primary md',
		type        : 'number',
		placeholder : 'Enter Amount',
		rules       : { required: 'Amount is required' },
	},
	{
		name        : 'card_pin',
		label       : 'Card PIN',
		span        : 1.5,
		className   : 'primary md',
		type        : 'text',
		placeholder : 'Enter Amount',
		rules       : {
			required : 'Card PIN is required',
			pattern  : {
				value   : GLOBAL_CONSTANTS.regex_patterns.four_characters_pin,
				message : '4 Characters in PIN is required',
			},
		},
	},
	{
		name        : 'remarks',
		placeholder : 'Enter Remarks',
		type        : 'textarea',
		span        : 4,
		label       : 'Remarks',
		className   : 'primary sm',
		rows        : 2,
		rules       : {
			required: 'Remarks is required',
		},
	},
];
