/* eslint-disable max-lines-per-function */
import containerSize from '@cogoport/constants/container-sizes.json';
import containertypes from '@cogoport/constants/container-types.json';
import truckTypes from '@cogoport/constants/truck-types.json';
import getCommodityList from '@cogoport/globalization/utils/getCommodityList';

export default function getLtlFreight({ type = '' }) {
	const freightOptions = getCommodityList('freight');
	const ltl_freight = [
		{
			label    : 'Select Trade Type',
			name     : 'trade_type',
			type     : 'select',
			span     : 2,
			watch    : true,
			disabled : type === 'edit',
			options  : [
				{ label: 'Import', value: 'import' },
				{ label: 'Export', value: 'export' },
				{ label: 'Domestic', value: 'domestic' },
			],
		},
		{
			label          : 'Origin Location',
			name           : 'origin_location_id',
			placeholder    : 'Select Origin',
			type           : 'location-select',
			caret          : true,
			optionsListKey : 'locations',
			watch          : true,
			span           : 2,
			// handleChange,
			disabled       : type === 'edit',
			params         : {
				filters: {
					type: ['continent', 'country', 'pincode', 'seaport', 'airport'],
				},
			},
		},
		{
			label          : 'Destination',
			name           : 'destination_location_id',
			placeholder    : 'Select Destination ',
			type           : 'location-select',
			caret          : true,
			optionsListKey : 'locations',
			watch          : true,
			span           : 2,
			// handleChange,
			disabled       : type === 'edit',
			params         : {
				filters: {
					type: ['continent', 'country', 'pincode', 'seaport', 'airport'],
				},
			},
		},
		{
			label       : 'Commodity',
			name        : 'commodity',
			type        : 'select',
			span        : 2,
			placeholder : 'Select Commodity',
			caret       : true,
			watch       : true,
			disabled    : type === 'edit',
			options     : freightOptions,
		},
	];
	const ftl_freight = [
		{
			label    : 'Select Trade Type',
			name     : 'trade_type',
			type     : 'select',
			span     : 2,
			watch    : true,
			disabled : type === 'edit',
			options  : [
				{ label: 'Import', value: 'import' },
				{ label: 'Export', value: 'export' },
				{ label: 'Domestic', value: 'domestic' },
			],
		},
		{
			label          : 'Origin Location',
			name           : 'origin_location_id',
			placeholder    : 'Select Origin',
			type           : 'async_select',
			asyncKey       : 'list_locations',
			initialCall    : true,
			caret          : true,
			optionsListKey : 'locations',
			watch          : true,
			span           : 2,
			// handleChange,
			disabled       : type === 'edit',
			params         : {
				filters: {
					type: ['continent', 'country', 'pincode', 'seaport', 'airport'],
				},
			},
		},
		{
			label          : 'Destination',
			name           : 'destination_location_id',
			placeholder    : 'Select Destination',
			type           : 'async_select',
			asyncKey       : 'list_locations',
			initialCall    : true,
			caret          : true,
			optionsListKey : 'locations',
			watch          : true,
			span           : 2,
			// handleChange,
			disabled       : type === 'edit',
			params         : {
				filters: {
					type: ['continent', 'country', 'pincode', 'seaport', 'airport'],
				},
			},
		},
		{
			label       : 'Truck Type',
			name        : 'truck_type',
			placeholder : 'Select Truck Type',
			type        : 'select',
			span        : 2,
			caret       : true,
			watch       : true,
			disabled    : type === 'edit',
			options     : truckTypes,
		},
		{
			label         : 'Commodity',
			name          : 'commodity',
			type          : 'select',
			span          : 2,
			placeholder   : 'Select Commodity',
			caret         : true,
			watch         : true,
			disabled      : type === 'edit',
			commodityType : 'ftl_freight',
		},
	];
	const fcl_freight_local = [
		{
			label    : 'Select Trade Type',
			name     : 'trade_type',
			type     : 'select',
			span     : 2,
			watch    : true,
			disabled : type === 'edit',
			options  : [
				{ label: 'Import', value: 'import' },
				{ label: 'Export', value: 'export' },
			],
		},
		{
			label          : 'Origin Location',
			name           : 'origin_location_id',
			placeholder    : 'Select Origin',
			type           : 'location-select',
			optionsListKey : 'locations',
			caret          : true,
			watch          : true,
			span           : 2,
			// handleChange,
			disabled       : type === 'edit',
			params         : { filters: { type: ['continent', 'seaport', 'country'] } },
		},
		{
			label          : 'Destination',
			name           : 'destination_location_id',
			placeholder    : 'Select Destination',
			type           : 'location-select',
			caret          : true,
			// handleChange,
			optionsListKey : 'locations',
			watch          : true,
			span           : 2,
			disabled       : type === 'edit',
			params         : { filters: { type: ['continent', 'seaport', 'country'] } },
		},
		{
			name           : 'shipping_line_id',
			label          : 'Shipping line',
			type           : 'select',
			span           : 2,
			caret          : true,
			defaultOptions : true,
			watch          : true,
			// handleChange,
			disabled       : type === 'edit',
			optionsListKey : 'shipping-lines',
			placeholder    : 'Select Shipping Line',
		},
		{
			label          : 'Container Size',
			name           : 'container_size',
			type           : 'select',
			caret          : true,
			placeholder    : 'Select Container Size',
			watch          : true,
			span           : 2,
			disabled       : type === 'edit',
			optionsListKey : 'container-sizes',
			options        : containerSize,
		},
		{
			label          : 'Container Type',
			name           : 'container_type',
			type           : 'select',
			caret          : true,
			placeholder    : 'Select Container Type',
			watch          : true,
			span           : 2,
			disabled       : type === 'edit',
			optionsListKey : 'container-types',
			options        : containertypes,
		},
		{
			label         : 'Commodity',
			name          : 'commodity',
			type          : 'select',
			caret         : true,
			placeholder   : 'Select Commodity',
			watch         : true,
			span          : 2,
			disabled      : type === 'edit',
			commodityType : 'freight',
		},
	];
	const rail_domestic_freight = [
		{
			label    : 'Select Trade Type',
			name     : 'trade_type',
			type     : 'select',
			span     : 2,
			watch    : true,
			disabled : type === 'edit',
			options  : [{ label: 'Domestic', value: 'domestic' }],
		},
		{
			label       : 'Origin',
			name        : 'origin_location_id',
			placeholder : 'Select Origin',
			type        : 'async_select',
			asyncKey    : 'list_locations',
			initialCall : true,
			caret       : true,
			watch       : true,
			span        : 2,
			disabled    : type === 'edit',
			params      : { filters: { type: ['railway_terminal'] } },
		},
		{
			label          : 'Destination',
			name           : 'destination_location_id',
			placeholder    : 'Select Destination',
			type           : 'async_select',
			asyncKey       : 'list_locations',
			initialCall    : true,
			caret          : true,
			optionsListKey : 'locations',
			watch          : true,
			span           : 2,
			disabled       : type === 'edit',
			params         : { filters: { type: ['railway_terminal'] } },
		},
	];
	return { fcl_freight_local, ftl_freight, ltl_freight, rail_domestic_freight };
}
