import { Accordion } from '@cogoport/components';

import { AdditionalServiceList } from '../../../../../common/AdditionalServices';
import Route from '../../../../../common/Route';

import styles from './styles.module.css';

function OverviewManageServices() {
	const getTitle = (
		<div className={styles.title}>Manage Services</div>
	);

	const allServices = [
		{
			is_active                                : true,
			inco_term                                : 'cif',
			origin_port_id                           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
			origin_main_port_id                      : null,
			destination_port_id                      : '23630ba9-b478-4000-ba75-05606d72d19f',
			destination_main_port_id                 : null,
			preferred_container_pickup_location_id   : 'd6bc9552-b8c5-42a4-98df-c08dfaf530cb',
			preferred_container_handover_location_id : 'd68099de-bb62-44b6-8db9-3882d09335a4',
			preferred_shipping_line_id               : '8b0f6780-1b22-4f80-b96c-bedb18711ac3',
			hs_code                                  : {
				id      : '10912692-9ddc-4b99-b87d-5cb829f35314',
				name    : 'Cereals',
				hs_code : '10',
			},
			shipment_id                     : 'c491c741-7bd3-4d9e-a51c-e5472278abd7',
			container_size                  : '40',
			container_type                  : 'standard',
			commodity_description           : 'sadffdcew',
			commodity                       : 'general',
			shipping_line_id                : 'c3649537-0c4b-4614-b313-98540cffcf40',
			containers_count                : 1,
			state                           : 'completed',
			cancellation_reason             : null,
			free_days_detention_origin      : 0,
			free_days_detention_destination : 14,
			free_days_demurrage_destination : 0,
			free_days_demurrage_origin      : 0,
			free_days_plugin_origin         : 0,
			free_days_plugin_destination    : 0,
			schedule_departure              : '2023-03-27T20:32:00',
			selected_schedule_departure     : '2023-03-22T00:00:00',
			schedule_arrival                : '2023-03-29T13:00:00',
			selected_schedule_arrival       : '2023-03-30T00:00:00',
			movement_detail                 : [
				{
					vessel             : 'dsf',
					voyage             : 'dasfgds',
					to_port            : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
					from_port          : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
					to_airport         : null,
					to_port_id         : '23630ba9-b478-4000-ba75-05606d72d19f',
					from_airport       : null,
					from_port_id       : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
					service_type       : 'fcl_freight_service',
					flight_number      : null,
					to_airport_id      : null,
					from_airport_id    : null,
					schedule_arrival   : '2023-03-29T18:30:00+05:30',
					schedule_departure : '2023-03-28T02:02:00+05:30',
				},
			],
			consignee_detail                 : null,
			reallocation_process_id          : null,
			bls_count                        : 1,
			bl_type                          : 'sob',
			cargo_readiness_date             : '2023-03-15',
			service_provider_reference_id    : null,
			paying_party_details             : null,
			booking_proof                    : null,
			agent_cancellation_reason        : null,
			bl_category                      : 'mbl',
			booking_reference_number         : '1234',
			rate_reference_number            : null,
			can_change_booking_params_status : null,
			booking_params                   : null,
			can_purchase_invoice_create      : false,
			cargo_weight_per_container       : 18,
			main_service_id                  : null,
			booking_rate_procurement_proof   : null,
			id                               : 'b7f3a877-4b77-4e34-a67e-c2ec6020aa9d',
			shipment_type                    : 'fcl_freight',
			service_type                     : 'fcl_freight_service',
			shipment_serial_id               : 149057,
			shipment_state                   : 'completed',
			importer_exporter_id             : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id         : '12aa63d6-a13c-42cd-bbee-645e47b8055f',
			service_provider_id              : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
			service_provider_poc_id          : null,
			created_at                       : '2023-03-15T07:33:37.822Z',
			all_states                       : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'containers_gated_in',
				'vessel_departed',
				'vessel_arrived',
				'containers_gated_out',
				'completed',
			],
			display_service_type : 'fcl_freight_service',
			payment_term         : 'prepaid',
			port                 : null,
			origin_port          : {
				id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
				name         : 'Jawaharlal Nehru (Nhava Sheva)',
				display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				pincode_id   : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
				port_code    : 'INNSA',
				postal_code  : '400707',
			},
			destination_port: {
				id           : '23630ba9-b478-4000-ba75-05606d72d19f',
				name         : 'Jebel Ali',
				display_name : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				pincode_id   : null,
				port_code    : 'AEJEA',
				postal_code  : null,
			},
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : {
				id            : 'c3649537-0c4b-4614-b313-98540cffcf40',
				business_name : 'MAERSK LINE INDIA PVT LTD',
				short_name    : 'Maersk',
				logo_url      : 'https://prod-cogoport.s3.ap-south-1.amazonaws.com/3341a08bd807a189547419c9f62fa050/Maersk%20Line.svg',
			},
			origin_airport      : null,
			destination_airport : null,
			airport             : null,
			airline             : null,
			importer_exporter   : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
				business_name       : 'AHI CARGO SOLUTION PRIVATE LIMITED',
				trade_name          : 'AHI CARGO SOLUTIONS PVT LTD',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 80949,
				sage_company_id     : '301',
				registration_number : 'AAMCA3315R',
			},
			container_pickup_location: {
				id           : 'd6bc9552-b8c5-42a4-98df-c08dfaf530cb',
				name         : 'Santa Rita',
				display_name : 'Santa Rita (BRSRR), Brazil, Sam',
				pincode_id   : null,
				port_code    : 'BRSRR',
				postal_code  : null,
			},
			container_handover_location: {
				id           : 'd68099de-bb62-44b6-8db9-3882d09335a4',
				name         : 'Blackburn',
				display_name : 'Blackburn (GBBLK), United Kingdom, Europe',
				pincode_id   : null,
				port_code    : 'GBBLK',
				postal_code  : null,
			},
			preferred_shipping_line: {
				id            : '8b0f6780-1b22-4f80-b96c-bedb18711ac3',
				business_name : 'ECONSHIP MARINE PVT LTD',
				short_name    : 'Econship Marine',
				logo_url      : 'https://prod-cogoport.s3.ap-south-1.amazonaws.com/a2bc15f94967f2fb823ba27dca67187f/ECON.svg',
			},
			port_of_loading                 : null,
			pending_tasks_count             : 6,
			unread_messages_count           : 0,
			show_edit_params                : false,
			preferred_departure_date        : null,
			origin_cargo_handling_type      : null,
			destination_cargo_handling_type : null,
			booking_note_number             : '1234',
			buy_quotation_agreed_rates      : 300,
			shipper_details                 : {
				id              : 'cdd6ed77-caa1-435d-877f-f53351a0f662',
				name            : 'VOLTAS LTD',
				address         : 'Khasra no 1765,1766,1768 to 1775 and 1872 ,1873/2,, \nMunicipality Kharkhoda, \nVillage Jatola, Sonipat, \nHaryana, 13140  \n',
				organization_id : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			},
			bn_expiry       : '2023-03-19T07:36:00.000Z',
			si_cutoff       : '2023-03-16T07:36:00.000Z',
			vgm_cutoff      : '2023-03-15T07:36:00.000Z',
			gate_in_cutoff  : '2023-03-18T07:36:00.000Z',
			document_cutoff : '2023-03-17T07:36:00.000Z',
			supplier_poc    : null,
		},
		{
			is_active                                : true,
			inco_term                                : 'cif',
			origin_port_id                           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
			origin_main_port_id                      : null,
			destination_port_id                      : '23630ba9-b478-4000-ba75-05606d72d19f',
			destination_main_port_id                 : null,
			preferred_container_pickup_location_id   : 'd6bc9552-b8c5-42a4-98df-c08dfaf530cb',
			preferred_container_handover_location_id : 'd68099de-bb62-44b6-8db9-3882d09335a4',
			preferred_shipping_line_id               : '8b0f6780-1b22-4f80-b96c-bedb18711ac3',
			hs_code                                  : {
				id      : '10912692-9ddc-4b99-b87d-5cb829f35314',
				name    : 'Cereals',
				hs_code : '10',
			},
			shipment_id                     : 'c491c741-7bd3-4d9e-a51c-e5472278abd7',
			container_size                  : '20',
			container_type                  : 'standard',
			commodity_description           : 'sadffdcew',
			commodity                       : 'general',
			shipping_line_id                : 'c3649537-0c4b-4614-b313-98540cffcf40',
			containers_count                : 1,
			state                           : 'completed',
			cancellation_reason             : null,
			free_days_detention_origin      : 11,
			free_days_detention_destination : 14,
			free_days_demurrage_destination : 0,
			free_days_demurrage_origin      : 11,
			free_days_plugin_origin         : 0,
			free_days_plugin_destination    : 0,
			schedule_departure              : '2023-03-27T20:32:00',
			selected_schedule_departure     : '2023-03-22T00:00:00',
			schedule_arrival                : '2023-03-29T13:00:00',
			selected_schedule_arrival       : '2023-03-30T00:00:00',
			movement_detail                 : [
				{
					vessel             : 'dsf',
					voyage             : 'dasfgds',
					to_port            : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
					from_port          : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
					to_airport         : null,
					to_port_id         : '23630ba9-b478-4000-ba75-05606d72d19f',
					from_airport       : null,
					from_port_id       : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
					service_type       : 'fcl_freight_service',
					flight_number      : null,
					to_airport_id      : null,
					from_airport_id    : null,
					schedule_arrival   : '2023-03-29T18:30:00+05:30',
					schedule_departure : '2023-03-28T02:02:00+05:30',
				},
			],
			consignee_detail                 : null,
			reallocation_process_id          : null,
			bls_count                        : 1,
			bl_type                          : 'sob',
			cargo_readiness_date             : '2023-03-15',
			service_provider_reference_id    : null,
			paying_party_details             : null,
			booking_proof                    : null,
			agent_cancellation_reason        : null,
			bl_category                      : 'mbl',
			booking_reference_number         : '1234',
			rate_reference_number            : null,
			can_change_booking_params_status : null,
			booking_params                   : null,
			can_purchase_invoice_create      : false,
			cargo_weight_per_container       : 18,
			main_service_id                  : 'b7f3a877-4b77-4e34-a67e-c2ec6020aa9d',
			booking_rate_procurement_proof   : null,
			id                               : 'ff891ab4-84a9-46db-9eb8-979690cb5b38',
			shipment_type                    : 'fcl_freight',
			service_type                     : 'fcl_freight_service',
			shipment_serial_id               : 149057,
			shipment_state                   : 'completed',
			importer_exporter_id             : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id         : '12aa63d6-a13c-42cd-bbee-645e47b8055f',
			service_provider_id              : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
			service_provider_poc_id          : null,
			created_at                       : '2023-03-15T07:33:37.900Z',
			all_states                       : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'containers_gated_in',
				'vessel_departed',
				'vessel_arrived',
				'containers_gated_out',
				'completed',
			],
			display_service_type : 'fcl_freight_service',
			payment_term         : 'prepaid',
			port                 : null,
			origin_port          : {
				id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
				name         : 'Jawaharlal Nehru (Nhava Sheva)',
				display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				pincode_id   : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
				port_code    : 'INNSA',
				postal_code  : '400707',
			},
			destination_port: {
				id           : '23630ba9-b478-4000-ba75-05606d72d19f',
				name         : 'Jebel Ali',
				display_name : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
				pincode_id   : null,
				port_code    : 'AEJEA',
				postal_code  : null,
			},
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : {
				id            : 'c3649537-0c4b-4614-b313-98540cffcf40',
				business_name : 'MAERSK LINE INDIA PVT LTD',
				short_name    : 'Maersk',
				logo_url      : 'https://prod-cogoport.s3.ap-south-1.amazonaws.com/3341a08bd807a189547419c9f62fa050/Maersk%20Line.svg',
			},
			origin_airport      : null,
			destination_airport : null,
			airport             : null,
			airline             : null,
			importer_exporter   : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
				business_name       : 'AHI CARGO SOLUTION PRIVATE LIMITED',
				trade_name          : 'AHI CARGO SOLUTIONS PVT LTD',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 80949,
				sage_company_id     : '301',
				registration_number : 'AAMCA3315R',
			},
			container_pickup_location: {
				id           : 'd6bc9552-b8c5-42a4-98df-c08dfaf530cb',
				name         : 'Santa Rita',
				display_name : 'Santa Rita (BRSRR), Brazil, Sam',
				pincode_id   : null,
				port_code    : 'BRSRR',
				postal_code  : null,
			},
			container_handover_location: {
				id           : 'd68099de-bb62-44b6-8db9-3882d09335a4',
				name         : 'Blackburn',
				display_name : 'Blackburn (GBBLK), United Kingdom, Europe',
				pincode_id   : null,
				port_code    : 'GBBLK',
				postal_code  : null,
			},
			preferred_shipping_line: {
				id            : '8b0f6780-1b22-4f80-b96c-bedb18711ac3',
				business_name : 'ECONSHIP MARINE PVT LTD',
				short_name    : 'Econship Marine',
				logo_url      : 'https://prod-cogoport.s3.ap-south-1.amazonaws.com/a2bc15f94967f2fb823ba27dca67187f/ECON.svg',
			},
			port_of_loading       : null,
			pending_tasks_count   : 0,
			unread_messages_count : 0,
			show_edit_params      : false,
		},
		{
			is_active                     : true,
			shipment_id                   : 'c491c741-7bd3-4d9e-a51c-e5472278abd7',
			port_id                       : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
			trade_type                    : 'export',
			service_provider_id           : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
			container_size                : '20',
			container_type                : 'standard',
			commodity                     : 'general',
			containers_count              : 1,
			state                         : 'completed',
			cancellation_reason           : null,
			reallocation_process_id       : null,
			service_provider_reference_id : null,
			agent_cancellation_reason     : null,
			can_purchase_invoice_create   : false,
			paying_party_details          : null,
			pol_id                        : 'fcl_locals.pol_id',
			main_service_id               : null,
			id                            : 'a782f7b9-92d7-492d-a27b-28c8df1b72e0',
			shipment_type                 : 'fcl_freight',
			service_type                  : 'fcl_freight_local_service',
			shipment_serial_id            : 149057,
			shipment_state                : 'completed',
			importer_exporter_id          : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id      : '12aa63d6-a13c-42cd-bbee-645e47b8055f',
			service_provider_poc_id       : null,
			created_at                    : '2023-03-15T07:33:38.889Z',
			all_states                    : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'containers_gated_in',
				'vessel_departed',
				'vessel_arrived',
				'containers_gated_out',
				'completed',
			],
			display_service_type : 'fcl_freight_local_service',
			payment_term         : 'prepaid',
			port                 : {
				id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
				name         : 'Jawaharlal Nehru (Nhava Sheva)',
				display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				pincode_id   : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
				port_code    : 'INNSA',
				postal_code  : '400707',
			},
			origin_port           : null,
			destination_port      : null,
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : null,
			origin_airport        : null,
			destination_airport   : null,
			airport               : null,
			airline               : null,
			importer_exporter     : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
				business_name       : 'AHI CARGO SOLUTION PRIVATE LIMITED',
				trade_name          : 'AHI CARGO SOLUTIONS PVT LTD',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 80949,
				sage_company_id     : '301',
				registration_number : 'AAMCA3315R',
			},
			container_pickup_location   : null,
			container_handover_location : null,
			preferred_shipping_line     : null,
			hs_code                     : null,
			port_of_loading             : null,
			pending_tasks_count         : 0,
			unread_messages_count       : 0,
			show_edit_params            : false,
		},
		{
			is_active                     : true,
			shipment_id                   : 'c491c741-7bd3-4d9e-a51c-e5472278abd7',
			port_id                       : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
			trade_type                    : 'export',
			service_provider_id           : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
			container_size                : '40',
			container_type                : 'standard',
			commodity                     : 'general',
			containers_count              : 1,
			state                         : 'completed',
			cancellation_reason           : null,
			reallocation_process_id       : null,
			service_provider_reference_id : null,
			agent_cancellation_reason     : null,
			can_purchase_invoice_create   : false,
			paying_party_details          : null,
			pol_id                        : 'fcl_locals.pol_id',
			main_service_id               : null,
			id                            : 'b4ef2a0e-04d2-4630-9cc0-6061820f15fc',
			shipment_type                 : 'fcl_freight',
			service_type                  : 'fcl_freight_local_service',
			shipment_serial_id            : 149057,
			shipment_state                : 'completed',
			importer_exporter_id          : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id      : '12aa63d6-a13c-42cd-bbee-645e47b8055f',
			service_provider_poc_id       : null,
			created_at                    : '2023-03-15T07:33:38.946Z',
			all_states                    : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'containers_gated_in',
				'vessel_departed',
				'vessel_arrived',
				'containers_gated_out',
				'completed',
			],
			display_service_type : 'fcl_freight_local_service',
			payment_term         : 'prepaid',
			port                 : {
				id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
				name         : 'Jawaharlal Nehru (Nhava Sheva)',
				display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				pincode_id   : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
				port_code    : 'INNSA',
				postal_code  : '400707',
			},
			origin_port           : null,
			destination_port      : null,
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : null,
			origin_airport        : null,
			destination_airport   : null,
			airport               : null,
			airline               : null,
			importer_exporter     : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : 'f06d843c-88b1-42fa-82be-f40e68f6fb65',
				business_name       : 'AHI CARGO SOLUTION PRIVATE LIMITED',
				trade_name          : 'AHI CARGO SOLUTIONS PVT LTD',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 80949,
				sage_company_id     : '301',
				registration_number : 'AAMCA3315R',
			},
			container_pickup_location   : null,
			container_handover_location : null,
			preferred_shipping_line     : null,
			hs_code                     : null,
			port_of_loading             : null,
			pending_tasks_count         : 0,
			unread_messages_count       : 0,
			show_edit_params            : false,
		},
	];

	const list = [
		{
			is_active                                : true,
			inco_term                                : 'exw',
			origin_port_id                           : '8aa0a40a-468c-4084-b343-c38e54adde36',
			origin_main_port_id                      : null,
			destination_port_id                      : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
			destination_main_port_id                 : null,
			preferred_container_pickup_location_id   : '8aa0a40a-468c-4084-b343-c38e54adde36',
			preferred_container_handover_location_id : '8aa0a40a-468c-4084-b343-c38e54adde36',
			preferred_shipping_line_id               : 'b5573cc4-8599-4957-a6f7-766a317290da',
			hs_code                                  : {
				id      : 'dd08ca8b-f329-4f7d-beea-010498d4fd82',
				name    : 'Air Conditioning Machines (temp & Hum Change), Pts',
				hs_code : '8415',
			},
			shipment_id                     : 'c2f006c3-37d0-443f-af04-5083b16c63c5',
			container_size                  : '40HC',
			container_type                  : 'standard',
			commodity_description           : 'Freezers',
			commodity                       : 'general',
			shipping_line_id                : 'b5573cc4-8599-4957-a6f7-766a317290da',
			containers_count                : 3,
			state                           : 'completed',
			cancellation_reason             : null,
			free_days_detention_origin      : 7,
			free_days_detention_destination : 7,
			free_days_demurrage_destination : 1,
			free_days_demurrage_origin      : 4,
			free_days_plugin_origin         : 10,
			free_days_plugin_destination    : 10,
			schedule_departure              : '2023-02-19T09:09:00',
			selected_schedule_departure     : '2023-02-19T14:31:00',
			schedule_arrival                : '2023-02-23T09:01:00',
			selected_schedule_arrival       : '2023-02-23T14:31:00',
			movement_detail                 : [
				{
					vessel             : 'MSC IVANA',
					voyage             : 'IS308A',
					to_port            : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
					from_port          : 'Colombo (LKCMB), Colombo, Sri Lanka',
					to_airport         : null,
					to_port_id         : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
					from_airport       : null,
					from_port_id       : '8aa0a40a-468c-4084-b343-c38e54adde36',
					service_type       : 'fcl_freight_service',
					flight_number      : null,
					to_airport_id      : null,
					from_airport_id    : null,
					schedule_arrival   : '2023-02-23T14:31:00+05:30',
					schedule_departure : '2023-02-19T14:39:00+05:30',
				},
			],
			consignee_detail                 : null,
			reallocation_process_id          : null,
			bls_count                        : 1,
			bl_type                          : 'sob',
			cargo_readiness_date             : '2023-02-14',
			service_provider_reference_id    : null,
			paying_party_details             : null,
			booking_proof                    : null,
			agent_cancellation_reason        : null,
			bl_category                      : 'hbl',
			booking_reference_number         : null,
			rate_reference_number            : '',
			can_change_booking_params_status : null,
			booking_params                   : null,
			can_purchase_invoice_create      : false,
			cargo_weight_per_container       : 18,
			main_service_id                  : null,
			booking_rate_procurement_proof   : null,
			id                               : '0b2dc2a4-54d7-4c99-94ad-37adea44fa80',
			shipment_type                    : 'fcl_freight',
			service_type                     : 'fcl_freight_service',
			shipment_serial_id               : 137254,
			shipment_state                   : 'completed',
			importer_exporter_id             : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id         : '6fc02a80-5d9f-42a2-b7f4-81ecce754089',
			service_provider_id              : '30118add-065c-4f28-8377-af5ccb7c8f54',
			service_provider_poc_id          : null,
			created_at                       : '2023-02-15T05:10:17.075Z',
			all_states                       : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'containers_gated_in',
				'vessel_departed',
				'vessel_arrived',
				'containers_gated_out',
				'completed',
			],
			display_service_type : 'fcl_freight_service',
			payment_term         : 'collect',
			port                 : null,
			origin_port          : {
				id           : '8aa0a40a-468c-4084-b343-c38e54adde36',
				name         : 'Colombo',
				display_name : 'Colombo (LKCMB), Colombo, Sri Lanka',
				pincode_id   : null,
				port_code    : 'LKCMB',
				postal_code  : null,
			},
			destination_port: {
				id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
				name         : 'Jawaharlal Nehru (Nhava Sheva)',
				display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				pincode_id   : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
				port_code    : 'INNSA',
				postal_code  : '400707',
			},
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : {
				id            : 'b5573cc4-8599-4957-a6f7-766a317290da',
				business_name : 'Any Shipping Line',
				short_name    : 'Any Line',
				logo_url      : null,
			},
			origin_airport      : null,
			destination_airport : null,
			airport             : null,
			airline             : null,
			importer_exporter   : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : '30118add-065c-4f28-8377-af5ccb7c8f54',
				business_name       : 'S & R Super Logistics (Lanka) Pvt. Ltd',
				trade_name          : 'S & R Super Logistics (Lanka) Pvt. Ltd',
				country_id          : 'e362729d-14ca-4cac-bd27-92bd01cd83d6',
				serial_id           : 56130,
				sage_company_id     : '301',
				registration_number : '114321443',
			},
			container_pickup_location: {
				id           : '8aa0a40a-468c-4084-b343-c38e54adde36',
				name         : 'Colombo',
				display_name : 'Colombo (LKCMB), Colombo, Sri Lanka',
				pincode_id   : null,
				port_code    : 'LKCMB',
				postal_code  : null,
			},
			container_handover_location: {
				id           : '8aa0a40a-468c-4084-b343-c38e54adde36',
				name         : 'Colombo',
				display_name : 'Colombo (LKCMB), Colombo, Sri Lanka',
				pincode_id   : null,
				port_code    : 'LKCMB',
				postal_code  : null,
			},
			preferred_shipping_line: {
				id            : 'b5573cc4-8599-4957-a6f7-766a317290da',
				business_name : 'Any Shipping Line',
				short_name    : 'Any Line',
				logo_url      : null,
			},
			port_of_loading       : null,
			pending_tasks_count   : 2,
			unread_messages_count : 0,
			service_supply_agent  : {
				id                  : '50a051d1-9f90-4514-b7ac-7fd73ef37ac3',
				name                : 'Ankur Chamola',
				email               : 'ankur.chamola@cogoport.com',
				mobile_number       : '7840077780',
				mobile_country_code : '+91',
				mobile_verified     : false,
				preferred_languages : [
					'uk_english',
					'english',
					'us_english',
				],
				birth_date                       : null,
				picture                          : null,
				alert_preferences                : [],
				whatsapp_number                  : null,
				whatsapp_country_code            : null,
				whatsapp_verified                : false,
				mobile_number_eformat            : '917840077780',
				whatsapp_number_eformat          : '',
				alternate_mobile_numbers         : [],
				alternate_mobile_number_eformats : [],
				used_organization_ids            : [],
				lead_user_id                     : null,
				email_verified                   : true,
				used_partner_ids                 : [],
				mobile_token                     : null,
				last_mobile_token_sent_at        : null,
				mobile_token_expiry_at           : null,
			},
			show_edit_params                : false,
			preferred_departure_date        : null,
			origin_cargo_handling_type      : null,
			destination_cargo_handling_type : 'dpd_cfs_factory_destuffing',
			booking_note_number             : 'SWEN/CMB/0045/23 ',
			buy_quotation_agreed_rates      : 750,
			shipper_details                 : {
				id              : 'cdd6ed77-caa1-435d-877f-f53351a0f662',
				name            : 'VOLTAS LTD',
				address         : 'Khasra no 1765,1766,1768 to 1775 and 1872 ,1873/2,, \nMunicipality Kharkhoda, \nVillage Jatola, Sonipat, \nHaryana, 13140  \n',
				organization_id : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			},
			container_status     : 'Not Picked',
			origin_oversea_agent : {
				id                  : '50a051d1-9f90-4514-b7ac-7fd73ef37ac3',
				name                : 'Ankur Chamola',
				email               : 'ankur.chamola@cogoport.com',
				mobile_number       : '7840077780',
				mobile_country_code : '+91',
			},
		},
		{
			is_active                     : true,
			shipment_id                   : 'c2f006c3-37d0-443f-af04-5083b16c63c5',
			port_id                       : '8aa0a40a-468c-4084-b343-c38e54adde36',
			trade_type                    : 'export',
			service_provider_id           : '30118add-065c-4f28-8377-af5ccb7c8f54',
			container_size                : '40HC',
			container_type                : 'standard',
			commodity                     : 'general',
			containers_count              : 3,
			state                         : 'completed',
			cancellation_reason           : null,
			reallocation_process_id       : null,
			service_provider_reference_id : null,
			agent_cancellation_reason     : null,
			can_purchase_invoice_create   : false,
			paying_party_details          : null,
			pol_id                        : 'fcl_locals.pol_id',
			main_service_id               : null,
			id                            : '59346eff-f228-424a-a45e-332a93561c44',
			shipment_type                 : 'fcl_freight',
			service_type                  : 'fcl_freight_local_service',
			shipment_serial_id            : 137254,
			shipment_state                : 'completed',
			importer_exporter_id          : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id      : '6fc02a80-5d9f-42a2-b7f4-81ecce754089',
			service_provider_poc_id       : null,
			created_at                    : '2023-02-15T05:10:18.441Z',
			all_states                    : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'containers_gated_in',
				'vessel_departed',
				'vessel_arrived',
				'containers_gated_out',
				'completed',
			],
			display_service_type : 'fcl_freight_local_service',
			payment_term         : 'collect',
			port                 : {
				id           : '8aa0a40a-468c-4084-b343-c38e54adde36',
				name         : 'Colombo',
				display_name : 'Colombo (LKCMB), Colombo, Sri Lanka',
				pincode_id   : null,
				port_code    : 'LKCMB',
				postal_code  : null,
			},
			origin_port           : null,
			destination_port      : null,
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : null,
			origin_airport        : null,
			destination_airport   : null,
			airport               : null,
			airline               : null,
			importer_exporter     : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : '30118add-065c-4f28-8377-af5ccb7c8f54',
				business_name       : 'S & R Super Logistics (Lanka) Pvt. Ltd',
				trade_name          : 'S & R Super Logistics (Lanka) Pvt. Ltd',
				country_id          : 'e362729d-14ca-4cac-bd27-92bd01cd83d6',
				serial_id           : 56130,
				sage_company_id     : '301',
				registration_number : '114321443',
			},
			container_pickup_location   : null,
			container_handover_location : null,
			preferred_shipping_line     : null,
			hs_code                     : null,
			port_of_loading             : null,
			pending_tasks_count         : 0,
			unread_messages_count       : 0,
			service_supply_agent        : {
				id                  : '50a051d1-9f90-4514-b7ac-7fd73ef37ac3',
				name                : 'Ankur Chamola',
				email               : 'ankur.chamola@cogoport.com',
				mobile_number       : '7840077780',
				mobile_country_code : '+91',
				mobile_verified     : false,
				preferred_languages : [
					'uk_english',
					'english',
					'us_english',
				],
				birth_date                       : null,
				picture                          : null,
				alert_preferences                : [],
				whatsapp_number                  : null,
				whatsapp_country_code            : null,
				whatsapp_verified                : false,
				mobile_number_eformat            : '917840077780',
				whatsapp_number_eformat          : '',
				alternate_mobile_numbers         : [],
				alternate_mobile_number_eformats : [],
				used_organization_ids            : [],
				lead_user_id                     : null,
				email_verified                   : true,
				used_partner_ids                 : [],
				mobile_token                     : null,
				last_mobile_token_sent_at        : null,
				mobile_token_expiry_at           : null,
			},
			show_edit_params: false,
		},
		{
			is_active                     : true,
			shipment_id                   : 'c2f006c3-37d0-443f-af04-5083b16c63c5',
			port_id                       : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
			trade_type                    : 'import',
			service_provider_id           : 'ce9b5260-7662-4dac-a250-ddfa1cffe166',
			container_size                : '40HC',
			container_type                : 'standard',
			commodity                     : 'general',
			containers_count              : 3,
			state                         : 'completed',
			cancellation_reason           : null,
			reallocation_process_id       : null,
			service_provider_reference_id : null,
			agent_cancellation_reason     : null,
			can_purchase_invoice_create   : false,
			paying_party_details          : null,
			pol_id                        : 'fcl_locals.pol_id',
			main_service_id               : null,
			id                            : '962cfae8-57cc-4499-b4c7-33dac3211478',
			shipment_type                 : 'fcl_freight',
			service_type                  : 'fcl_freight_local_service',
			shipment_serial_id            : 137254,
			shipment_state                : 'completed',
			importer_exporter_id          : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id      : '6fc02a80-5d9f-42a2-b7f4-81ecce754089',
			service_provider_poc_id       : null,
			created_at                    : '2023-02-21T07:11:46.865Z',
			all_states                    : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'containers_gated_in',
				'vessel_departed',
				'vessel_arrived',
				'containers_gated_out',
				'completed',
			],
			display_service_type : 'fcl_freight_local_service',
			payment_term         : 'collect',
			port                 : {
				id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
				name         : 'Jawaharlal Nehru (Nhava Sheva)',
				display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				pincode_id   : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
				port_code    : 'INNSA',
				postal_code  : '400707',
			},
			origin_port           : null,
			destination_port      : null,
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : null,
			origin_airport        : null,
			destination_airport   : null,
			airport               : null,
			airline               : null,
			importer_exporter     : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : 'ce9b5260-7662-4dac-a250-ddfa1cffe166',
				business_name       : 'SWEN CONTAINER LINE PRIVATE LIMITED',
				trade_name          : 'SWEN CONTAINER LINE PRIVATE LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 73077,
				sage_company_id     : '301',
				registration_number : 'ABDCS5261N',
			},
			container_pickup_location   : null,
			container_handover_location : null,
			preferred_shipping_line     : null,
			hs_code                     : null,
			port_of_loading             : null,
			pending_tasks_count         : 0,
			unread_messages_count       : 0,
			service_supply_agent        : {
				id                  : '50a051d1-9f90-4514-b7ac-7fd73ef37ac3',
				name                : 'Ankur Chamola',
				email               : 'ankur.chamola@cogoport.com',
				mobile_number       : '7840077780',
				mobile_country_code : '+91',
				mobile_verified     : false,
				preferred_languages : [
					'uk_english',
					'english',
					'us_english',
				],
				birth_date                       : null,
				picture                          : null,
				alert_preferences                : [],
				whatsapp_number                  : null,
				whatsapp_country_code            : null,
				whatsapp_verified                : false,
				mobile_number_eformat            : '917840077780',
				whatsapp_number_eformat          : '',
				alternate_mobile_numbers         : [],
				alternate_mobile_number_eformats : [],
				used_organization_ids            : [],
				lead_user_id                     : null,
				email_verified                   : true,
				used_partner_ids                 : [],
				mobile_token                     : null,
				last_mobile_token_sent_at        : null,
				mobile_token_expiry_at           : null,
			},
			show_edit_params: false,
		},
		{
			is_active                     : true,
			shipment_id                   : 'c2f006c3-37d0-443f-af04-5083b16c63c5',
			port_id                       : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
			trade_type                    : 'import',
			container_type                : 'standard',
			container_size                : '40HC',
			commodity                     : null,
			containers_count              : 3,
			cargo_weight_per_container    : 18,
			state                         : 'completed',
			cancellation_reason           : null,
			cargo_handling_type           : 'dpd_cfs_factory_destuffing',
			reallocation_process_id       : null,
			service_provider_reference_id : null,
			paying_party_details          : null,
			booking_proof                 : null,
			agent_cancellation_reason     : null,
			can_purchase_invoice_create   : true,
			main_service_id               : null,
			id                            : '27f9e67b-bda7-4779-bac4-64da14b37038',
			shipment_type                 : 'fcl_freight',
			service_type                  : 'fcl_cfs_service',
			shipment_serial_id            : 137254,
			shipment_state                : 'completed',
			importer_exporter_id          : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
			importer_exporter_poc_id      : '6fc02a80-5d9f-42a2-b7f4-81ecce754089',
			service_provider_id           : '1022c6f3-83ce-45a8-9742-9da81ce001a2',
			service_provider_poc_id       : null,
			created_at                    : '2023-02-21T07:12:08.847Z',
			all_states                    : [
				'init',
				'awaiting_service_provider_confirmation',
				'confirmed_by_service_provider',
				'completed',
			],
			display_service_type : 'fcl_cfs_service',
			payment_term         : 'collect',
			port                 : {
				id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
				name         : 'Jawaharlal Nehru (Nhava Sheva)',
				display_name : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
				pincode_id   : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
				port_code    : 'INNSA',
				postal_code  : '400707',
			},
			origin_port           : null,
			destination_port      : null,
			origin_main_port      : null,
			destination_main_port : null,
			origin_location       : null,
			location              : null,
			destination_location  : null,
			console_point         : null,
			deconsole_point       : null,
			pincode               : null,
			shipping_line         : null,
			origin_airport        : null,
			destination_airport   : null,
			airport               : null,
			airline               : null,
			importer_exporter     : {
				id                  : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
				business_name       : 'VOLTAS LIMITED',
				trade_name          : 'VOLTAS LIMITED',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 29612,
				sage_company_id     : '301',
				registration_number : 'AAACV2809D',
			},
			service_provider: {
				id                  : '1022c6f3-83ce-45a8-9742-9da81ce001a2',
				business_name       : 'KESTREL AVIATION PRIVATE LIMITED',
				trade_name          : 'KESTREL AVIATION PVT LTD',
				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
				serial_id           : 36279,
				sage_company_id     : '301',
				registration_number : 'AADCK2002L',
			},
			container_pickup_location   : null,
			container_handover_location : null,
			preferred_shipping_line     : null,
			hs_code                     : null,
			port_of_loading             : null,
			pending_tasks_count         : 0,
			unread_messages_count       : 0,
			service_supply_agent        : {
				id                  : '37095899-766f-4ae8-a007-0da63efddaad',
				name                : 'Harshad Mehra',
				email               : 'supply_support@cogoport.com',
				mobile_number       : '7506077725',
				mobile_country_code : '+91',
				mobile_verified     : false,
				preferred_languages : [
					'uk_english',
					'english',
					'us_english',
				],
				birth_date                       : null,
				picture                          : null,
				alert_preferences                : [],
				whatsapp_number                  : null,
				whatsapp_country_code            : null,
				whatsapp_verified                : false,
				mobile_number_eformat            : '917506077725',
				whatsapp_number_eformat          : '',
				alternate_mobile_numbers         : [],
				alternate_mobile_number_eformats : [],
				used_organization_ids            : [],
				lead_user_id                     : null,
				email_verified                   : true,
				used_partner_ids                 : [],
				mobile_token                     : null,
				last_mobile_token_sent_at        : null,
				mobile_token_expiry_at           : null,
			},
			show_edit_params: false,
		},
	];
	return (
		<Accordion title={getTitle}>
			<Route allServices={allServices} />
			<div className={styles.line} />

			<AdditionalServiceList
				services={list}
				// refetchServices={refetchServices}
				// activeTab={activeTab}
			/>
		</Accordion>
	);
}
export default OverviewManageServices;
