export const urgencyOptions = [
	{ label: 'Surrender (Telex) BL Payments', value: 'telex' },
	{ label: 'BL Amendment Payments', value: 'bl_amnd' },
	{ label: 'LDC/LBC Payments', value: 'ldc_lbc' },
	{ label: 'Cancel Charges', value: 'cxl' },
	{ label: 'Detention Payments', value: 'dtn' },
	{ label: 'Direct Port Delivery (DPD)', value: 'dpd' },
	{ label: 'Short Payment', value: 'sp' },
	{ label: 'ODEX', value: 'odex' },
	{ label: 'Short Transit Shipment', value: 'sts' },
	{ label: 'Co-ordination Charges', value: 'cc' },
	{ label: 'SEZ Shipment', value: 'sezs' },
	{ label: 'Airlines DO Payments', value: 'adp' },
	{ label: 'Urgent', value: 'urgent' },
];
