export const ASYNC_SELECT_MAPPING = [
	{
		placeholder : 'Managers',
		asyncKey    : 'list_all_managers',
		isClearable : true,
		size        : 'sm',
		multiple    : true,
		key         : 'manager_ids',
	},
	{
		placeholder : 'Squads',
		asyncKey    : 'list_squads',
		isClearable : true,
		size        : 'sm',
		multiple    : true,
		key         : 'squad_ids',
	},
	{
		placeholder : 'Tribes',
		asyncKey    : 'list_tribes',
		isClearable : true,
		size        : 'sm',
		multiple    : true,
		key         : 'tribe_ids',
	},
	{
		placeholder : 'Chapters',
		asyncKey    : 'list_chapters',
		isClearable : true,
		size        : 'sm',
		multiple    : true,
		key         : 'chapter_ids',
	},
	{
		placeholder : 'Employees',
		asyncKey    : 'list_employees',
		isClearable : true,
		size        : 'sm',
		multiple    : true,
		key         : 'employee_ids',
	},
];
