export const dummyData = {
	list: [
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 1,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 2,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 3,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 4,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 5,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 6,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 7,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 8,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 9,
		},
		{
			name         : 'XYZ Name',
			Type         : 'Type',
			Frequency    : 'Weekly',
			CreatedOn    : '22 Feb 2023',
			LastEditedOn : '23 Feb 2023',
			id           : 10,
		},
	],
};
