export const agentDetails = [
	{
		label          : 'Agent Name',
		key            : 'agent_name',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'agent_name',
		customType     : 'input',
	},
	{
		label          : 'Agent Mobile Number',
		key            : 'agent_mobile_number',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'agent_mobile_number',
		customType     : 'input',
	},
	{
		label          : 'Agent Company Name',
		key            : 'agent_company_name',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'agent_company_name',
		customType     : 'input',
	},
	{
		label          : 'Fleet Owner Agreement',
		key            : 'fleet_owner_agreement_agent',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'fleet_owner_agreement',
		customType     : 'document',
	},
	{
		label          : 'PAN Card',
		key            : 'pan_card_agent',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'pan_card',
		customType     : 'document',
	},
	{
		label          : 'GSTIN Proof',
		key            : 'gstin_proof_agent',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'gstin_proof',
		customType     : 'document',
	},
	{
		label          : 'Bank Account Details',
		key            : 'bank_account_details_agent',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'bank_account_details',
		customType     : 'document',
	},
	{
		label          : 'ITR Declaration',
		key            : 'itr_declaration_agent',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'itr_declaration',
		customType     : 'document',
	},
	{
		label          : 'Udyam Ceretificate For MSME',
		key            : 'udyam_ceretificate_for_msme_agent',
		dataMainAccess : 'agent_details',
		dataAccessKey  : 'agent_udyam_certificate',
		customType     : 'document',
	},
	{
		label          : 'Aadhar Card',
		key            : 'aadhar_card_agent',
		dataMainAccess : 'agent_details',
		dataSubAccess  : 'agent_kyc_details',
		dataAccessKey  : 'aadhar_card',
		customType     : 'document',
	},
	{
		label          : 'Voter ID Card',
		key            : 'voter_id_card_agent',
		dataMainAccess : 'agent_details',
		dataSubAccess  : 'agent_kyc_details',
		dataAccessKey  : 'voter_id_card',
		customType     : 'document',
	},
	{
		label          : 'Driving License',
		key            : 'driving_license_agent',
		dataMainAccess : 'agent_details',
		dataSubAccess  : 'agent_kyc_details',
		dataAccessKey  : 'driving_licence',
		customType     : 'document',
	},
];
