export const REJECTED_DOCUMENTS = [
	{
		label          : 'Commercial Invoice Image',
		key            : 'commmercial_invoice_image_rejected',
		dataAccessKey  : 'commercial_invoice_images',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'E-Way Bill Image',
		key            : 'eway_bill_image_rejected',
		dataAccessKey  : 'eway_bill_images',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'LR Image',
		key            : 'lr_image_rejected',
		dataAccessKey  : 'lr_images',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'Weight Note Image',
		key            : 'weight_note_image_rejected',
		dataAccessKey  : 'weight_note_image',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'Selfie With Loaded Truck',
		key            : 'selfie_with_loaded_truck_rejected',
		dataAccessKey  : 'selfie_with_loaded_truck',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'Fleet Owner Letter',
		key            : 'fleet_owner_letter_rejected',
		dataAccessKey  : 'fleet_owner_letter',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'PoD Upload',
		key            : 'pod_upload_rejected',
		dataAccessKey  : 'proof_of_delivery',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'Invoice Submission',
		key            : 'invoice_submission_rejected',
		dataAccessKey  : 'invoice_submission',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'Start Kilometers Images',
		key            : 'start_kilometer_images_rejected',
		dataAccessKey  : 'start_kilometer_images',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'End Kilometers Images',
		key            : 'end_kilometer_images_rejected',
		dataAccessKey  : 'end_kilometer_images',
		customType     : 'document',
		dataMainAccess : 'rejected_documents',
	},
	{
		label          : 'RC',
		key            : 'registration_ceretificate_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'registration_certificate',
		customType     : 'document',
	},
	{
		label          : 'Road Permit',
		key            : 'road_permit_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'road_permit',
		customType     : 'document',
	},
	{
		label          : 'Pollution Ceretificate',
		key            : 'pollution_ceretificate_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'pollution_certificate',
		customType     : 'document',
	},
	{
		label          : 'Road Worthiness',
		key            : 'road_worthiness_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'road_worthiness_certificate',
		customType     : 'document',
	},
	{
		label          : 'Cancelled Cheque',
		key            : 'cancelled_cheque_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'cancelled_cheque',
		customType     : 'document',
	},
	{
		label          : 'Driver DL Upload',
		key            : 'driver_dl_upload_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'driving_licence',
		customType     : 'document',
	},
	{
		label          : 'PAN Card (Vendor)',
		key            : 'pan_card_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'pan_card_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'GSTIN Proof (Vendor)',
		key            : 'gstin_proof_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'gstin_proof_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'Bank Account Details (Vendor)',
		key            : 'bank_account_details_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'bank_account_details_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'TDS Ceretificate (Vendor)',
		key            : 'tds_ceretificate_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'tds_certificate_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'ITR Declaration (Vendor)',
		key            : 'itr_declaration_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'itr_declaration_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'Purchase Agreement Letter (Vendor)',
		key            : 'purchase_agreement_letter_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'purchase_agreement_letter_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'Udyam Ceretificate For MSME (Vendor)',
		key            : 'udyam_ceretificate_for_msme_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'fleet_owner_udyam_certificate_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'Aadhar Card (Vendor)',
		key            : 'aadhar_card_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'aadhar_card_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'Voter ID Card (Vendor)',
		key            : 'voter_id_card_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'voter_id_card_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'Driving License (Vendor)',
		key            : 'driving_license_vendor_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'driving_licence_fleet_owner',
		customType     : 'document',
	},
	{
		label          : 'Fleet Owner Agreement (Agent)',
		key            : 'fleet_owner_agreement_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'fleet_owner_agreement_agent',
		customType     : 'document',
	},
	{
		label          : 'PAN Card (Agent)',
		key            : 'pan_card_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'pan_card_agent',
		customType     : 'document',
	},
	{
		label          : 'GSTIN Proof (Agent)',
		key            : 'gstin_proof_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'gstin_proof_agent',
		customType     : 'document',
	},
	{
		label          : 'Bank Account Details (Agent)',
		key            : 'bank_account_details_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'bank_account_details_agent',
		customType     : 'document',
	},
	{
		label          : 'ITR Declaration (Agent)',
		key            : 'itr_declaration_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'itr_declaration_agent',
		customType     : 'document',
	},
	{
		label          : 'Udyam Ceretificate For MSME (Agent)',
		key            : 'udyam_ceretificate_for_msme_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'agent_udyam_certificate_agent',
		customType     : 'document',
	},
	{
		label          : 'Aadhar Card (Agent)',
		key            : 'aadhar_card_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'aadhar_card_agent',
		customType     : 'document',
	},
	{
		label          : 'Voter ID Card (Agent)',
		key            : 'voter_id_card_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'voter_id_card_agent',
		customType     : 'document',
	},
	{
		label          : 'Driving License (Agent)',
		key            : 'driving_license_agent_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'driving_licence_agent',
		customType     : 'document',
	},
	{
		label          : 'Other Documents',
		key            : 'other_documents_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'other',
		customType     : 'document',
	},
	{
		label          : 'Guage Before Taking Fuel',
		key            : 'gauge_before_taking_fuel_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'gauge_before_taking_fuel',
		customType     : 'document',
	},
	{
		label          : 'Guage After Taking Fuel',
		key            : 'gauge_after_taking_fuel_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'gauge_after_taking_fuel',
		customType     : 'document',
	},
	{
		label          : 'Proof of Fuel Quantity',
		key            : 'proof_of_fuel_quantity_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'proof_of_fuel_quantity',
		customType     : 'document',
	},
	{
		label          : 'Proof of Fuel Payement',
		key            : 'proof_of_fuel_payment_rejected',
		dataMainAccess : 'rejected_documents',
		dataAccessKey  : 'proof_of_fuel_payment',
		customType     : 'document',
	},
];
