export const VENDOR_DETAILS = [
	{
		label          : 'Fleet Owner Name',
		key            : 'fleet_owner_name_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'fleet_owner_name',
		customType     : 'input',
	},
	{
		label          : 'Fleet Owner Mobile Number',
		key            : 'fleet_owner_mobile_number_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'fleet_owner_mobile_number',
		customType     : 'input',
	},
	{
		label          : 'Fleet Owner Company Name',
		key            : 'fleet_owner_company_name_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'fleet_owner_company_name',
		customType     : 'input',
	},
	{
		label          : 'PAN Card',
		key            : 'pan_card_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'pan_card',
		customType     : 'document',
	},
	{
		label          : 'GSTIN Proof',
		key            : 'gstin_proof_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'gstin_proof',
		customType     : 'document',
	},
	{
		label          : 'Bank Account Details',
		key            : 'bank_account_details_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'bank_account_details',
		customType     : 'document',
	},
	{
		label          : 'TDS Ceretificate',
		key            : 'tds_ceretificate_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'tds_certificate',
		customType     : 'document',
	},
	{
		label          : 'ITR Declaration',
		key            : 'itr_declaration_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'itr_declaration',
		customType     : 'document',
	},
	{
		label          : 'Purchase Agreement Letter',
		key            : 'purchase_agreement_letter_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'purchase_agreement_letter',
		customType     : 'document',
	},
	{
		label          : 'Udyam Ceretificate For MSME',
		key            : 'udyam_ceretificate_for_msme_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataAccessKey  : 'fleet_owner_udyam_certificate',
		customType     : 'document',
	},
	{
		label          : 'Aadhar Card',
		key            : 'aadhar_card_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataSubAccess  : 'fleet_owner_kyc_details',
		dataAccessKey  : 'aadhar_card',
		customType     : 'document',
	},
	{
		label          : 'Voter ID Card',
		key            : 'voter_id_card_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataSubAccess  : 'fleet_owner_kyc_details',
		dataAccessKey  : 'voter_id_card',
		customType     : 'document',
	},
	{
		label          : 'Driving License',
		key            : 'driving_license_vendor',
		dataMainAccess : 'fleet_owner_details',
		dataSubAccess  : 'fleet_owner_kyc_details',
		dataAccessKey  : 'driving_licence',
		customType     : 'document',
	},
];
