const createFormControls = [

	{
		name        : 'name',
		label       : 'Name',
		type        : 'text',
		placeholder : 'Enter name',
	},
	{
		name        : 'type',
		label       : 'Type',
		type        : 'select',
		placeholder : 'Select type',
		options     : [
			{ label: 'Pincode', value: 'pincode' },
			{ label: 'City', value: 'city' },
			{ label: 'Region', value: 'region' },
			{ label: 'Seaport', value: 'seaport' },
			{ label: 'Airport', value: 'airport' },
			{ label: 'Cluster', value: 'cluster' },
			{ label: 'Cfs', value: 'cfs' },
			{ label: 'Yard', value: 'yard' },
			{
				label : 'Warehouse',
				value : 'warehouse',
			},
			{
				label : 'Railway Terminal',
				value : 'railway_terminal',
			},
		],

		rules: { required: 'Type is Required' },
	},
	{
		name        : 'status',
		label       : 'Status',
		type        : 'select',
		placeholder : 'Select status',
		options     : [
			{ label: 'Active', value: 'active' },
			{ label: 'Inactive', value: 'inactive' },
		],
		rules: { required: 'status is Required' },
	},
	{
		name        : 'postal_code',
		label       : 'Postal code',
		type        : 'text',
		placeholder : 'Enter postal code',
		condition   : { type: ['pincode', 'airport', 'seaport'] },

	},
	{
		name        : 'site_code',
		label       : 'Site code',
		type        : 'text',
		placeholder : 'Enter location code',
		condition   : { type: ['warehouse', 'railway_terminal'] },
	},
	{
		name        : 'address',
		label       : 'Address',
		type        : 'text',
		placeholder : 'Enter address',
	},
	{
		name        : 'latitude',
		label       : 'Latitude',
		type        : 'text',
		placeholder : 'Enter latitude',
		rules       : { required: 'Latitude required' },
	},
	{
		name        : 'longitude',
		label       : 'Longitude',
		type        : 'text',
		placeholder : 'Enter longitude',
		rules       : { required: 'longitude required' },
	},
	{
		name        : 'currency_code',
		label       : 'Currency code',
		type        : 'text',
		placeholder : 'Enter currency code',
		condition   : { type: ['country'] },
		rules       : { required: 'Required' },
	},
	{
		name        : 'country_code',
		label       : 'Country code',
		type        : 'text',
		placeholder : 'Enter country code',
		condition   : { type: ['country'] },
		rules       : { required: 'Required' },
	},
	{
		name        : 'mobile_country_code',
		label       : 'Mobile country code',
		type        : 'text',
		condition   : { type: ['country'] },
		placeholder : 'Enter mobile country code',
		rules       : { required: 'Required' },
	},
	{
		name    : 'country_id',
		label   : 'Country',
		type    : 'select',
		options : [
			{
				value : '182d828e-765c-462e-8dda-26fac133e459',
				label : 'Fiji, Australia',
			}, {
				value : '2dc13ba6-5018-4aa4-bc0c-f4853c05190b',
				label : 'Uzbekistan, Med',
			}, {
				value : '08f7f774-eccd-4058-ac08-577b5f18c804',
				label : 'Anguilla, North America',
			},
		],
		placeholder    : 'Select country',
		optionsListKey : 'locations',
		condition      : {
			type: [
				'city',
				'seaport',
				'airport',
				'pincode',
				'cfs',
				'cluster',
				'region',
				'yard',
				'railway_terminal',
				'warehouse',
			],
		},
		params : { filters: { type: ['country'] } },
		rules  : { required: 'Required , country' },
	},
	{
		name    : 'zone_id',
		label   : 'Zone',
		type    : 'select',
		options : [
			{
				value : '1ae7237e-77f5-43c0-807f-2124836c7369',
				label : 'North India',
			}, {
				value : '466fd023-448a-4c01-b80d-7ccc11578eeb',
				label : 'South India',
			}, {
				value : '20a47220-b4b4-472b-84d7-46c8c8d47d2a',
				label : 'West India',
			},
		],
		placeholder    : 'Select Zone',
		optionsListKey : 'locations',
		isClearable    : true,
		params         : { filters: { type: ['zone'] } },
	},
	{
		name    : 'region_id',
		label   : 'Region',
		type    : 'select',
		options : [
			{
				value : '2abeb582-270e-4f8b-b0eb-a83364446369',
				label : 'Massachusetts',
			}, {
				value : 'd085f5f6-caf6-414d-b261-f060e32ebfb4',
				label : 'Kansas',
			}, {
				value : 'a415e6de-e5c8-41e4-9106-0cc99c97591c',
				label : 'Nebraska',
			},
		],
		placeholder    : 'Select region',
		optionsListKey : 'locations',
		isClearable    : true,
		params         : { filters: { type: ['region'] } },
	},
	{
		name    : 'city_id',
		label   : 'City',
		type    : 'select',
		options : [
			{
				value : '000548d6-ca6c-4595-8ea6-c70d316cf522',
				label : 'Cambron-Casteau',
			}, {
				value : '0019b4d7-a3f5-4478-be3e-8a3cb01781aa',
				label : 'East Langton',
			}, {
				value : '001a6e7a-1014-4999-9f46-2f39f545cf6c',
				label : 'Gas Hills',
			},
		],
		placeholder    : 'Select city',
		optionsListKey : 'locations',
		isClearable    : true,
		condition      : {
			type: [
				'seaport',
				'airport',
				'pincode',
				'cfs',
				'cluster',
				'yard',
				'warehouse',
				'railway_terminal',
			],
		},
		rules  : { message: 'Required' },
		params : { filters: { type: ['city'] } },
	},
	{
		name    : 'cluster_id',
		label   : 'Cluster',
		type    : 'select',
		options : [
			{
				value : '961354f5-715b-4dd1-a3a7-6583439de2bf',
				label : 'Orissa',
			},
			{
				value : 'a886a12f-1305-4adf-b8e2-c168196e51cb',
				label : 'Princess Dock',

			}, {
				value : 'c551c09e-7b9e-4d31-8b49-db0345b250d4',
				label : 'Assam',

			},
		],
		placeholder    : 'Select cluster',
		optionsListKey : 'locations',
		isClearable    : true,
		condition      : {
			type: ['seaport', 'airport', 'pincode', 'cfs', 'cluster', 'yard'],
		},
		params: { filters: { type: ['cluster'] } },
	},
	{
		name    : 'pincode_id',
		label   : 'Pincode',
		type    : 'select',
		options : [
			{
				value : '00030e6f-c3de-43a5-9cd8-aa731db65517',
				label : 'G411EL-Govan',
			}, {
				value : '000340a7-f99f-47b4-8281-98c5a4e38afa',
				label : 'AB555JB-Speyside Glenlivet',
			}, {
				value : '0004bac0-161d-4827-8daa-6a4aa1caef99',
				label : '12144-Defreestville',
			},
		],
		placeholder    : 'Select pincode',
		optionsListKey : 'locations',
		isClearable    : true,
		condition      : {
			type: [
				'seaport',
				'airport',
				'cfs',
				'yard',
				'railway_terminal',
				'warehouse',
			],
		},
		rules  : { required: 'Required' },
		params : { filters: { type: ['pincode'] } },
	},
	{
		name    : 'cfs_code',
		label   : 'CFS',
		type    : 'select',
		options : [
			{
				value : '11514984-2deb-4959-bd7b-53bb756d67d7',
				label : 'SEATECH',

			}, {
				value : '24fb4ec7-eac9-4e99-b861-0af8427bd7d1',
				label : 'SEABIRD',

			}, {
				value : '347b9dce-d9e1-4185-9945-b45709f19661',
				label : 'KRISHNAPATNAM',
			},
		],
		placeholder    : 'Select cfs',
		optionsListKey : 'locations',
		condition      : { type: ['cfs'] },
		params         : { filters: { type: ['cfs'] } },
	},
	{
		name        : 'port_code',
		label       : 'Port code',
		type        : 'text',
		placeholder : 'Enter port',
		condition   : { type: ['seaport', 'airport'] },
	},
	{
		name        : 'inttra_code',
		label       : 'Inttra code',
		type        : 'text',
		condition   : { type: ['seaport'] },
		placeholder : 'Enter inttra code',
	},
	{
		name        : 'cfs_agency_name',
		label       : 'CFS agency name',
		type        : 'text',
		condition   : { type: ['cfs'] },
		placeholder : 'Enter cfs agency name',
	},
	{
		name        : 'is_icd',
		label       : 'ICD',
		type        : 'select',
		selectType  : 'pills',
		placeholder : 'Select ICD',
		options     : [
			{ label: 'Yes', value: 'Yes' },
			{ label: 'No', value: 'No' },
		],
		condition: { type: ['seaport'] },
	},
	{
		name           : 'local_languages',
		label          : 'Local languages',
		multiple       : true,
		type           : 'select',
		placeholder    : 'Select languages',
		optionsListKey : 'languages',
		options        : [
			{ value: 'uk_english', label: 'English UK' },
			{ value: 'english', label: 'English India' },
			{ value: 'us_english', label: 'English US' },
			{ value: 'spanish', label: 'Spanish' },
			{ value: 'mandarin_chinese', label: 'Mandarin chinese' },
			{ value: 'arabic', label: 'العربية, Arabic' },
			{ value: 'bengali', label: 'বাংলা' },
			{ value: 'hindi', label: 'हिन्दी' },
			{ value: 'russian', label: 'русский язык,Russian' },
			{ value: 'portuguese', label: 'Português' },
			{ value: 'japanese', label: '日本語 (にほんご／にっぽんご)' },
			{ value: 'german', label: 'Deutsch' },
			{ value: 'wu_chinese', label: 'Wu chinese' },
			{ value: 'javanese', label: 'basa Jawa' },
			{ value: 'korean', label: '한국어 (韓國語), 조선말 (朝鮮語)' },
			{ value: 'french', label: 'français, langue française' },
			{ value: 'turkish', label: 'Türkçe' },
			{ value: 'vietnamese', label: 'Tiếng Việt' },
			{ value: 'telugu', label: 'తెలుగు' },
			{ value: 'yue_chinese', label: 'Yue chinese' },
			{ value: 'marathi', label: 'मराठी' },
			{ value: 'tamil', label: 'தமிழ்' },
			{ value: 'italian', label: 'Italiano' },
			{ value: 'urdu', label: 'اردو' },
			{ value: 'minnan_chinese', label: 'Minnan chinese' },
			{ value: 'jinyu_chinese', label: 'Jinyu chinese' },
			{ value: 'gujarati', label: 'ગુજરાતી' },
			{ value: 'polish', label: 'polski' },
			{ value: 'ukrainian', label: 'українська' },
			{ value: 'persian', label: 'فارسی' },
			{ value: 'xiang_chinese', label: 'Xiang chinese' },
			{ value: 'malayalam', label: 'മലയാളം' },
			{ value: 'hakka_chinese', label: 'Hakka chinese' },
			{ value: 'kannada', label: 'ಕನ್ನಡ' },
			{ value: 'oriya', label: 'ଓଡ଼ିଆ' },
			{ value: 'western_punjabi', label: 'Western punjabi' },
			{ value: 'sunda', label: 'Sunda' },
			{ value: 'eastern_punjabi', label: 'Eastern punjabi' },
			{ value: 'romanian', label: 'română' },
			{ value: 'dutch', label: 'Nederlands, Vlaams' },
			{ value: 'assamese', label: 'অসমীয়া' },
		],
	},
	{
		name        : 'aliases_attributes',
		label       : 'Aliases attributes',
		type        : 'childformat',
		showButtons : true,
		buttonText  : 'Add Aliases',
		childFormat : [
			{
				name     : 'id',
				label    : 'ID',
				disabled : true,
				show     : false,
				type     : 'text',
			},
			{
				name  : 'name',
				label : 'Name',
				type  : 'text',
				rules : { required: 'Required' },
			},
		],
	},
	{
		name            : 'flag_icon_url',
		showLabel       : false,
		label           : 'Flag Icon svg/image',
		span            : 12,
		type            : 'file',
		themeType       : 'secondary',
		drag            : true,
		uploadIcon      : 'ic-upload',
		onlyURLOnChange : true,
		accept:
				'image/*,.pdf,.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		uploadType: 'aws',
	},
	{
		name            : 'flag_image_url',
		showLabel       : false,
		label           : 'Flag Icon png/image',
		span            : 12,
		type            : 'file',
		themeType       : 'secondary',
		drag            : true,
		uploadIcon      : 'ic-upload',
		onlyURLOnChange : true,
		accept:
				'image/*,.pdf,.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
		uploadType: 'aws',
	},
];

export default createFormControls;
