const updateForm = {
	title      : 'Update location',
	submitText : 'Update',
	api        : {
		endpoint : 'update_location',
		method   : 'post',
	},
	controls: [
		{
			name        : 'name',
			label       : 'Name',
			type        : 'text',
			placeholder : 'Enter name',
		},
		{
			name        : 'type',
			label       : 'Type',
			type        : 'select',
			placeholder : 'Select type',
			options     : [
				{ label: 'Pincode', value: 'pincode' },
				{ label: 'City', value: 'city' },
				{ label: 'Region', value: 'region' },
				{ label: 'Seaport', value: 'seaport' },
				{ label: 'Airport', value: 'airport' },
				{ label: 'Cluster', value: 'cluster' },
				{ label: 'Cfs', value: 'cfs' },
				{ label: 'Yard', value: 'yard' },
				{
					label : 'Warehouse',
					value : 'warehouse',
				},
				{
					label : 'Railway Terminal',
					value : 'railway_terminal',
				},
			],
			validations: [{ type: 'required', message: 'Type is Required' }],
		},
		{
			name        : 'status',
			label       : 'Status',
			type        : 'select',
			placeholder : 'Select status',
			options     : [
				{ label: 'Active', value: 'active' },
				{ label: 'Inactive', value: 'inactive' },
			],
			validations: [{ type: 'required', message: 'status is Required' }],
		},
		{
			name        : 'postal_code',
			label       : 'Postal code',
			type        : 'text',
			placeholder : 'Enter postal code',
			condition   : { type: ['pincode', 'airport', 'seaport'] },
		},
		{
			name        : 'site_code',
			label       : 'Site code',
			type        : 'text',
			placeholder : 'Enter location code',
			condition   : { type: ['warehouse', 'railway_terminal'] },
		},
		{
			name        : 'address',
			label       : 'Address',
			type        : 'text',
			placeholder : 'Enter address',
		},
		{
			name        : 'latitude',
			label       : 'Latitude',
			type        : 'text',
			placeholder : 'Enter latitude',
			validations : [{ type: 'required', message: 'Latitude required' }],
		},
		{
			name        : 'longitude',
			label       : 'Longitude',
			type        : 'text',
			placeholder : 'Enter longitude',
			validations : [{ type: 'required', message: 'longitude required' }],
		},
		{
			name        : 'currency_code',
			label       : 'Currency code',
			type        : 'text',
			placeholder : 'Enter currency code',
			condition   : { type: ['country'] },
			validations : [{ type: 'required', message: 'Required' }],
		},
		{
			name        : 'country_code',
			label       : 'Country code',
			type        : 'text',
			placeholder : 'Enter country code',
			condition   : { type: ['country'] },
			validations : [{ type: 'required', message: 'Required' }],
		},
		{
			name        : 'mobile_country_code',
			label       : 'Mobile country code',
			type        : 'text',
			condition   : { type: ['country'] },
			placeholder : 'Enter mobile country code',
			validations : [{ type: 'required', message: 'Required' }],
		},
		{
			name           : 'country_id',
			label          : 'Country',
			type           : 'location-select',
			placeholder    : 'Select country',
			optionsListKey : 'locations',
			condition      : {
				type: [
					'city',
					'seaport',
					'airport',
					'pincode',
					'cfs',
					'cluster',
					'region',
					'yard',
					'warehouse',
					'railway_terminal',
				],
			},
			params      : { filters: { type: ['country'] } },
			validations : [{ type: 'required', message: 'Required , country' }],
		},
		{
			name           : 'zone_id',
			label          : 'Zone',
			type           : 'location-select',
			placeholder    : 'Select region',
			optionsListKey : 'locations',
			isClearable    : true,
			params         : { filters: { type: ['zone'] } },
		},
		{
			name           : 'region_id',
			label          : 'Region',
			type           : 'location-select',
			placeholder    : 'Select region',
			optionsListKey : 'locations',
			isClearable    : true,
			params         : { filters: { type: ['region'] } },
		},
		{
			name           : 'city_id',
			label          : 'City',
			type           : 'location-select',
			placeholder    : 'Select city',
			optionsListKey : 'locations',
			isClearable    : true,
			condition      : {
				type: [
					'seaport',
					'airport',
					'pincode',
					'cfs',
					'cluster',
					'yard',
					'warehouse',
					'railway_terminal',
				],
			},
			validations : [{ type: 'required', message: 'Required' }],
			params      : { filters: { type: ['city'] } },
		},
		{
			name           : 'cluster_id',
			label          : 'Cluster',
			type           : 'location-select',
			placeholder    : 'Select cluster',
			optionsListKey : 'locations',
			isClearable    : true,
			condition      : {
				type: ['seaport', 'airport', 'pincode', 'cfs', 'cluster', 'yard'],
			},
			params: { filters: { type: ['cluster'] } },
		},
		{
			name           : 'pincode_id',
			label          : 'Pincode',
			type           : 'select',
			placeholder    : 'Select pincode',
			optionsListKey : 'locations',
			isClearable    : true,
			condition      : {
				type: [
					'seaport',
					'airport',
					'cfs',
					'yard',
					'warehouse',
					'railway_terminal',
				],
			},
			validations : [{ type: 'required', message: 'Required' }],
			params      : { filters: { type: ['pincode'] } },
		},
		{
			name           : 'cfs_code',
			label          : 'CFS',
			type           : 'location-select',
			placeholder    : 'Select cfs',
			optionsListKey : 'locations',
			condition      : { type: ['cfs'] },
			params         : { filters: { type: ['cfs'] } },
		},
		{
			name        : 'port_code',
			label       : 'Port code',
			type        : 'text',
			placeholder : 'Enter port',
			condition   : { type: ['seaport', 'airport'] },
		},
		{
			name        : 'inttra_code',
			label       : 'Inttra code',
			type        : 'text',
			condition   : { type: ['seaport'] },
			placeholder : 'Enter inttra code',
		},
		{
			name        : 'cfs_agency_name',
			label       : 'CFS agency name',
			type        : 'text',
			condition   : { type: ['cfs'] },
			placeholder : 'Enter cfs agency name',
		},
		{
			name           : 'local_languages',
			label          : 'Local languages',
			multiple       : true,
			type           : 'select',
			placeholder    : 'Select languages',
			optionsListKey : 'languages',
		},
		{
			name        : 'aliases_attributes',
			label       : 'Aliases attributes',
			type        : 'childformat',
			showButtons : true,
			buttonText  : 'Add Aliases',
			childFormat : [
				{
					name     : 'id',
					label    : 'ID',
					disabled : true,
					show     : false,
					type     : 'text',
				},
				{
					name        : 'name',
					label       : 'Name',
					type        : 'text',
					validations : [{ type: 'required', message: 'Required' }],
				},
			],
		},
		{
			name            : 'flag_icon_url',
			showLabel       : false,
			label           : 'Flag Icon svg/image',
			span            : 12,
			type            : 'file',
			themeType       : 'secondary',
			drag            : true,
			uploadIcon      : 'ic-upload',
			onlyURLOnChange : true,
			accept:
				'image/*,.pdf,.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			uploadType: 'aws',
		},
		{
			name            : 'flag_image_url',
			showLabel       : false,
			label           : 'Flag Icon png/image',
			span            : 12,
			type            : 'file',
			themeType       : 'secondary',
			drag            : true,
			uploadIcon      : 'ic-upload',
			onlyURLOnChange : true,
			accept:
				'image/*,.pdf,.doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document',
			uploadType: 'aws',
		},
	],
};

export default updateForm;
