export const controls = [
	{
		name        : 'country_id',
		label       : 'Country of Registration',
		type        : 'select',
		placeholder : 'Select a Country',
		span        : '30%',
		condition   : {
			type: [
				'city',
				'seaport',
				'airport',
				'pincode',
				'cfs',
				'cluster',
				'region',
				'yard',
				'railway_terminal',
				'warehouse',
			],
		},
		rules: { required: 'Country is required' },
	},
	{
		name        : 'tax_number_type',
		label       : 'Tax Number',
		type        : 'select',
		placeholder : 'Select',
		span        : '8%',
		condition   : { type: ['country'] },
		rules       : { required: 'Tax Number is Required' },
	},
	{
		name        : 'tax_number',
		label       : 'Document Number',
		type        : 'text',
		span        : '22%',
		condition   : { type: ['country'] },
		placeholder : 'Enter Document No',
		rules       : { required: 'Document No is required' },
	},
	{
		name        : 'name',
		label       : 'Name of the Organization',
		type        : 'text',
		span        : '30%',
		placeholder : 'Type here',
		rules       : { required: 'Role Short Name is required' },
	},
	{
		name            : 'tax_proof_url',
		showLabel       : false,
		label           : 'Upload Tax Document Proof (Pan/GST Certificate)',
		span            : '100%',
		type            : 'file',
		themeType       : 'secondary',
		drag            : true,
		uploadIcon      : 'ic-upload',
		onlyURLOnChange : true,
		accept          : 'image/*',
		uploadType      : 'aws',
	},
	{
		name        : 'company_type',
		label       : 'Type of Company',
		type        : 'select',
		placeholder : 'Select an Organization Type',
		span        : '40%',
		rules       : { required: 'Company Type is required' },
	},
	{
		name        : 'city_id',
		label       : 'Branch',
		type        : 'select',
		span        : '40%',
		placeholder : 'Select a city',
		condition   : {
			type: [
				'seaport',
				'airport',
				'pincode',
				'cfs',
				'cluster',
				'yard',
				'warehouse',
				'railway_terminal',
			],
		},
		rules : { message: 'City is Required' },
	},
];
