import { amountControls } from '../../commons/controls/amountControls';
import { customerControls } from '../../commons/controls/customerControls';
import { deliveryControls } from '../../commons/controls/deliveryControls';
import { fleetOwnerDriverDetailControls } from '../../commons/controls/fleetOwnerDriverDetailControls';
import { uploadControls } from '../../commons/controls/uploadControls';
import Label from '../../commons/Label';
import { commodityOptions } from '../../commons/utils/commodityOptions';
import { indentDhalaType } from '../../commons/utils/indentDhalaTypeOptions';
import { indentTruckType } from '../../commons/utils/indentTruckTypeOptions';
import { truckLengthOptions } from '../../commons/utils/truckLengthOptions';
import { truckType } from '../../commons/utils/truckTypeOptions';

export const formControls = {
	mainControls: [
		...customerControls,
		{
			name        : 'business_mode',
			placeholder : 'Type here...',
			type        : 'select',
			span        : 4,
			label       : <Label>Business Mode</Label>,
			options     : [
				{ label: 'FCM', value: 'fcm' },
				{ label: 'RCM', value: 'rcm' },
			],
			className: 'primary lg',
		},
		{
			name        : 'truck_type',
			placeholder : 'Select',
			label       : <Label>Truck Type</Label>,
			type        : 'select',
			options     : truckType,
			className   : 'primary lg',
			span        : 4,
		},
		{
			name         : 'item_value',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			showOptional : false,
			label        : 'Item Value',
			className    : 'primary lg',
		},
		{
			name        : 'indent_truck_type',
			placeholder : 'Select',
			label       : <Label>Indent Truck Type</Label>,
			type        : 'select',
			options     : indentTruckType,
			className   : 'primary lg',
			span        : 4,
		},
		{
			name        : 'indent_dhala_type',
			placeholder : 'Select',
			label       : <Label>Indent Dhala Type</Label>,
			type        : 'select',
			options     : indentDhalaType,
			className   : 'primary lg',
			span        : 4,
		},
		{
			name        : 'indent_truck_length',
			placeholder : 'Select',
			label       : <Label>Indent Truck Length</Label>,
			type        : 'select',
			options     : truckLengthOptions,
			className   : 'primary lg',
			span        : 4,
		},
		{
			name         : 'consignor_name',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignor Name',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'consignor_address',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignor Address',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'consignor_gstin',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignor GSTIN',
			showOptional : false,
			rules        : {
				pattern: {
					// value   : patterns.GST_NUMBER,
					message: 'GST Number is invalid',
				},
			},
			className: 'primary lg',
		},
		{
			name         : 'consignee_name',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignee Name',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'consignee_address',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignee Address',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'consignee_gstin',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Consignee GSTIN',
			showOptional : false,
			rules        : {
				pattern: {
					// value   : patterns.GST_NUMBER,
					message: 'GST Number is invalid',
				},
			},
			className: 'primary lg',
		},
		{
			name           : 'from_town',
			placeholder    : 'Select',
			label          : <Label>From Town</Label>,
			type           : 'select',
			optionsListKey : 'fortigo_locations',
			className      : 'primary lg',
			span           : 4,
		},
		{
			name           : 'to_town',
			placeholder    : 'Select',
			label          : <Label>To Town</Label>,
			type           : 'select',
			optionsListKey : 'fortigo_locations',
			className      : 'primary lg',
			span           : 4,
		},
		{
			name         : 'place_of_supply',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Place of Supply',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name        : 'rate_type',
			placeholder : 'Select',
			label       : <Label required>Rate Type</Label>,
			type        : 'select',
			options     : [
				{ label: 'Fixed', value: 'Fixed' },
				{ label: 'RPT', value: 'RPT' },
			],
			className : 'primary lg',
			rules     : {
				required: 'This is required',
			},
			span: 4,
		},
		{
			name           : 'from_state',
			placeholder    : 'Select',
			label          : <Label>From State</Label>,
			type           : 'select',
			optionsListKey : 'fortigo_locations',
			className      : 'primary lg',
			span           : 4,
		},
		{
			name           : 'to_state',
			placeholder    : 'Select',
			label          : <Label>To State</Label>,
			type           : 'select',
			optionsListKey : 'fortigo_locations',
			className      : 'primary lg',
			span           : 4,
		},
		{
			name        : 'truck_no',
			placeholder : 'Type here...',
			type        : 'text',
			span        : 4,
			label       : <Label>Truck No</Label>,
			className   : 'primary lg',
		},
		{
			name        : 'actual_weight',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label required>Actual Weight</Label>,
			rules       : {
				required: 'This is required',
			},
			className: 'primary lg',
		},
		{
			name         : 'charged_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Charged Weight',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name        : 'rate',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label required>Rate</Label>,
			className   : 'primary lg',
			rules       : {
				required: 'This is required',
			},
		},
		{
			name        : 'tax_percent',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label required>Tax Percent</Label>,
			className   : 'primary lg',
			rules       : {
				required : 'This is required',
				min      : 0,
				max      : 100,
			},
		},
		{
			name        : 'gcn_no',
			placeholder : 'Type here...',
			type        : 'text',
			span        : 4,
			label       : <Label>GCN No</Label>,
			className   : 'primary lg',
		},
		{
			name      : 'gcn_date',
			label     : <Label>GCN Date</Label>,
			type      : 'datepicker',
			className : 'primary lg',
			// usePortal: true,
			span      : 4,
		},
		{
			name        : 'value_of_goods',
			placeholder : 'Type here...',
			type        : 'number',
			span        : 4,
			label       : <Label>Value of Goods</Label>,
			className   : 'primary lg',
		},
		{
			name         : 'kind_attention',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Kind Attention',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'invoice_no',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Invoice No',
			showOptional : false,
			className    : 'primary lg',
		},
		...amountControls,
		{
			name        : 'sac_code',
			placeholder : 'Select',
			label       : <Label required>SAC Code</Label>,
			type        : 'select',
			options     : [
				{ label: '996791 - Freight Transportation', value: 996791 },
				{ label: '996513 - Rental Invoice', value: 996513 },
			],
			rules: {
				required: 'This is required',
			},
			className : 'primary lg',
			span      : 4,
		},
		{
			name         : 'item_discount',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Item Discount',
			showOptional : false,
			className    : 'primary lg',
		},
		...fleetOwnerDriverDetailControls,
		{
			name           : 'pickup_date_time',
			label          : <Label>Pickup Date Time</Label>,
			type           : 'datepicker',
			className      : 'primary lg',
			withTimePicker : true,
			usePortal      : true,
			span           : 4,
		},
		{
			name        : 'eway_bill_no',
			placeholder : 'Type here...',
			label       : <Label>Eway Bill No</Label>,
			type        : 'text',
			className   : 'primary lg',
			span        : 4,
		},
		{
			name        : 'commodity_type',
			placeholder : 'Select',
			label       : <Label>Commodity Type</Label>,
			type        : 'select',
			className   : 'primary lg',
			options     : commodityOptions,
			span        : 4,
		},
		...deliveryControls,
		{
			name         : 'vendor_code',
			placeholder  : 'Type here...',
			label        : 'Vendor Code',
			type         : 'text',
			className    : 'primary lg',
			span         : 4,
			showOptional : false,
		},
		{
			name        : 'sale_price',
			placeholder : 'Type here...',
			label       : <Label>Sale Price</Label>,
			type        : 'number',
			className   : 'primary lg',
			span        : 4,
		},
		{
			name         : 'excess_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Excess Weight',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'short_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Short Weight',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'package_count',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'No. of Pkgs',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'sc_number',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'S.C. No.',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'loading_weight',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Loading Weight',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'grade',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Grade',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'converted_case',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Converted Case',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'empty_quantity',
			placeholder  : 'Type here...',
			type         : 'number',
			span         : 4,
			label        : 'Empty Quantity',
			showOptional : false,
			className    : 'primary lg',
		},
		{
			name         : 'permit_no',
			placeholder  : 'Type here...',
			type         : 'text',
			span         : 4,
			label        : 'Permit No.',
			showOptional : false,
			className    : 'primary lg',
		},
		...uploadControls,
	],
};
