const dummyData = {
	list: [{
		vendorSerialId : '1',
		kycStatus      : 'verified',
		name           : 'nagi',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '2',
		kycStatus      : 'verified',
		name           : 'vivek',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '3',
		kycStatus      : 'verified',
		name           : 'nagi',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '4',
		kycStatus      : 'verified',
		name           : 'vivek',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '5',
		kycStatus      : 'verified',
		name           : 'nagi',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '6',
		kycStatus      : 'verified',
		name           : 'vivek',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '7',
		kycStatus      : 'verified',
		name           : 'nagi',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '8',
		kycStatus      : 'verified',
		name           : 'vivek',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '9',
		kycStatus      : 'verified',
		name           : 'nagi',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '10',
		kycStatus      : 'verified',
		name           : 'vivek',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '11',
		kycStatus      : 'verified',
		name           : 'nagi',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '12',
		kycStatus      : 'verified',
		name           : 'vivek',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	}, {
		vendorSerialId : '13',
		kycStatus      : 'pending',
		name           : 'nagi',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	{
		vendorSerialId : '14',
		kycStatus      : 'pending',
		name           : 'vivek',
		pan            : 'drtpg2989d',
		category       : 'RENT',
		payments       : 'INR 210000',
		openInvoices   : 12,
		createdAt      : '12/12/2011',
	},
	],
	pageIndex    : 1,
	totalPage    : 2,
	totalRecords : 14,
};

export default dummyData;
