export const cargoArrivalData = {
	notify            : '',
	consignee         : '',
	shipper           : '',
	job_ref_no        : '',
	inv_ref_no        : '',
	igm_dt            : '',
	port_of_loading   : '',
	port_of_discharge : '',
	pan               : '',
	tan               : '',
	weight            : '',
	volume            : '',
	packages_count    : '',
	containers        : [
		{
			container_no        : '',
			marks_and_number    : '',
			package_description : '',
			gross_weight        : '',
			measurement         : '',
		},
	],
	generic_statement              : '',
	freight_amount                 : '',
	freight_payable_at             : '',
	number_of_original_MTDs        : '',
	place_and_date_of_issue        : '',
	authorized_signatory_text      : '',
	authorized_signatory_image_url : '',
	other_particulars              : '',
	shipment_details               : {
		po_no         : '',
		hbl_no        : '',
		hawb_no       : '',
		vessel        : '',
		voyage        : '',
		flight_number : '',
		obl_number    : '',
		obl_date      : '',
		mawb_no       : '',
		mawb_date     : '',
		service_name  : '',
		booking_no    : '',
		carrier_name  : '',
		origin        : '',
		destination   : '',
		eta           : '',
		etd           : '',
		warehouse     : '',
		item_no       : '',
		sub_item_no   : '',
		all_prepaid   : '',
	},
};
