export const leftDataControls = {
	lcl_freight_service: [
		{ name: 'po_no', fullWidth: false, label: 'PO Number' },
		{ name: 'hbl_no', fullWidth: false, label: 'HBL Number' },
		{ name: 'vessel', fullWidth: false, label: 'Vessel' },
		{ name: 'voyage', fullWidth: false, label: 'Voyage' },
		{ name: 'booking_no', fullWidth: false, label: 'booking no' },
		{ name: 'service_name', fullWidth: false, label: 'Service' },
		{ name: 'obl_number', fullWidth: false, label: 'Obl Number' },
		{ name: 'obl_date', fullWidth: false, label: 'Obl Date' },
		{ name: 'origin', fullWidth: false, label: 'Origin' },
		{ name: 'port_of_loading', fullWidth: false, label: 'POL' },
		{ name: 'port_of_discharge', fullWidth: false, label: 'POD' },
		{ name: 'eta', fullWidth: false, label: 'ETA' },
		{ name: 'destination', fullWidth: false, label: 'Final Dest' },
		{ name: 'etd', fullWidth: false, label: 'ETD' },
		{ name: 'warehouse', fullWidth: false, label: 'Warehouse' },
		{ name: 'item_no', fullWidth: false, label: 'Item No' },
		{ name: 'sub_item_no', fullWidth: false, label: 'SubItem No' },
		{ name: 'carrier_name', fullWidth: false, label: 'Carrier name' },
		{ name: 'all_prepaid', fullWidth: false, label: 'All Prepaid' },
	],
	fcl_freight_service: [
		{ name: 'po_no', fullWidth: false, label: 'PO Number' },
		{ name: 'hbl_no', fullWidth: false, label: 'HBL Number' },
		{ name: 'vessel', fullWidth: false, label: 'Vessel' },
		{ name: 'voyage', fullWidth: false, label: 'Voyage' },
		{ name: 'booking_no', fullWidth: false, label: 'booking no' },
		{ name: 'service_name', fullWidth: false, label: 'Service' },
		{ name: 'obl_number', fullWidth: false, label: 'Obl Number' },
		{ name: 'obl_date', fullWidth: false, label: 'Obl Date' },
		{ name: 'origin', fullWidth: false, label: 'Origin' },
		{ name: 'port_of_loading', fullWidth: false, label: 'POL' },
		{ name: 'port_of_discharge', fullWidth: false, label: 'POD' },
		{ name: 'eta', fullWidth: false, label: 'ETA' },
		{ name: 'destination', fullWidth: false, label: 'Final Dest' },
		{ name: 'etd', fullWidth: false, label: 'ETD' },
		{ name: 'warehouse', fullWidth: false, label: 'Warehouse' },
		{ name: 'item_no', fullWidth: false, label: 'Item No' },
		{ name: 'sub_item_no', fullWidth: false, label: 'SubItem No' },
		{ name: 'all_prepaid', fullWidth: false, label: 'All Prepaid' },
	],
};
