import { Loader, Pagination } from '@cogoport/components';
import React, { useState } from 'react';

import EmptyState from '../../common/EmptyState';
import useGetFeedbackList from '../../hooks/useGetFeedbackList';

import FeedbackCard from './FeedbackCard';
import Filters from './Filters';
import styles from './styles.module.css';

function FeedbackDashboard() {
	const [filters, setFilters] = useState({ page: 1 });
	const { data = {}, loading, page } = useGetFeedbackList({ filters, setFilters });
	const { list = [] } = data;
	// const { list = [] } = 	{
	// 	list: [
	// 		{
	// 			id             : '96b38a6e-5a0d-48ab-ba92-1ecd887dc184',
	// 			booking_params : {
	// 				bls_count : 1,
	// 				inco_term : 'cif',
	// 				rate_card : {
	// 					card    : 'fa976924-aeb2-46b7-86a2-44b241f01836',
	// 					legs    : null,
	// 					tags    : [],
	// 					price   : 12908.46085991,
	// 					source  : 'spot_rates',
	// 					arrival : '2023-06-18T00:00:00.000Z',
	// 					margins : [
	// 						{
	// 							id           : 'cbbb4230-4b76-40bd-89fb-8bc751984f5a',
	// 							status       : 'active',
	// 							filters      : {},
	// 							service      : 'fcl_freight',
	// 							agent_id     : null,
	// 							created_at   : '2021-12-22T05:09:48.451Z',
	// 							partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 							updated_at   : '2022-11-03T07:36:24.589Z',
	// 							margin_type  : 'cogoport',
	// 							agent_rm_ids : [],
	// 							margin_slabs : [
	// 								{
	// 									lower_limit   : 0.0,
	// 									upper_limit   : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									],
	// 									margin_values_hash: {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									},
	// 								},
	// 							],
	// 							location_type : null,
	// 							margin_values : [
	// 								{
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 3.0,
	// 									currency  : 'USD',
	// 									max_value : 300.0,
	// 									min_value : 0.0,
	// 								},
	// 							],
	// 							organization_id    : null,
	// 							filters_keys_count : 0,
	// 							margin_values_hash : {
	// 								BAS: {
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 3.0,
	// 									currency  : 'USD',
	// 									max_value : 300.0,
	// 									min_value : 0.0,
	// 								},
	// 							},
	// 							service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							margin_slabs_currency : 'USD',
	// 						},
	// 						{
	// 							id      : '1efc2610-f137-4c9e-b6c4-fb5ffbb08338',
	// 							status  : 'active',
	// 							filters : {
	// 								trade_type: 'export',
	// 							},
	// 							service      : 'fcl_freight',
	// 							agent_id     : '0ccfc574-f942-4fb4-971d-a34c7ae691c3',
	// 							created_at   : '2021-05-06T15:24:51.960Z',
	// 							partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 							updated_at   : '2023-04-20T10:11:46.900Z',
	// 							margin_type  : 'demand',
	// 							agent_rm_ids : [
	// 								'cd8dde11-678c-4467-85b2-2e2d6055bef4',
	// 								'95d62549-8ab6-4ee5-a655-9edd0ec46dac',
	// 							],
	// 							margin_slabs: [
	// 								{
	// 									lower_limit   : 0.0,
	// 									upper_limit   : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									],
	// 									margin_values_hash: {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									},
	// 								},
	// 							],
	// 							location_type : null,
	// 							margin_values : [
	// 								{
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 5.0,
	// 									currency  : 'USD',
	// 									max_value : 150.0,
	// 									min_value : 25.0,
	// 								},
	// 							],
	// 							organization_id    : null,
	// 							filters_keys_count : 1,
	// 							margin_values_hash : {
	// 								BAS: {
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 5.0,
	// 									currency  : 'USD',
	// 									max_value : 150.0,
	// 									min_value : 25.0,
	// 								},
	// 							},
	// 							service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							margin_slabs_currency : 'USD',
	// 						},
	// 					],
	// 					rate_id    : '890f5d53-caa6-4e17-9244-71b64fbbb6d7',
	// 					is_liked   : false,
	// 					commodity  : 'general',
	// 					departure  : '2023-06-15T00:00:00.000Z',
	// 					si_cutoff  : null,
	// 					line_items : [
	// 						{
	// 							code    : 'BAS',
	// 							name    : 'Basic Freight',
	// 							unit    : 'per_container',
	// 							price   : 151.69,
	// 							source  : 'system',
	// 							margins : [
	// 								{
	// 									code               : 'BAS',
	// 									type               : 'percentage',
	// 									value              : 3.0,
	// 									currency           : 'USD',
	// 									max_value          : 300.0,
	// 									min_value          : 0.0,
	// 									margin_type        : 'cogoport',
	// 									margin_value       : 3.69,
	// 									total_margin_value : 3.69,
	// 								},
	// 								{
	// 									code               : 'BAS',
	// 									type               : 'percentage',
	// 									value              : 5.0,
	// 									currency           : 'USD',
	// 									max_value          : 150.0,
	// 									min_value          : 25.0,
	// 									margin_type        : 'demand',
	// 									margin_value       : 25.0,
	// 									total_margin_value : 25.0,
	// 								},
	// 							],
	// 							remarks: [
	// 								'test1212',
	// 							],
	// 							currency               : 'USD',
	// 							quantity               : 1,
	// 							buy_price              : 123.0,
	// 							total_price            : 151.69,
	// 							service_name           : 'fcl_freight',
	// 							service_type           : 'export',
	// 							total_buy_price        : 123.0,
	// 							price_discounted       : 151.69,
	// 							total_price_discounted : 151.69,
	// 						},
	// 					],
	// 					service_id   : null,
	// 					vgm_cutoff   : null,
	// 					is_disliked  : true,
	// 					likes_count  : 95,
	// 					total_price  : 12908.46085991,
	// 					validity_id  : '70500b13-9941-4291-b9bd-c9c3ca62121c',
	// 					origin_local : {
	// 						source              : 'spot_rates',
	// 						margins             : [],
	// 						line_items          : [],
	// 						service_provider_id : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 					},
	// 					payment_term : 'prepaid',
	// 					service_type : 'fcl_freight',
	// 					transit_time : 3,
	// 					validity_end : '2023-06-15',
	// 					weight_limit : {
	// 						unit       : 'per_container',
	// 						slabs      : [],
	// 						margins    : [],
	// 						remarks    : [],
	// 						free_limit : 18.0,
	// 					},
	// 					freight_price : 151.69,
	// 					origin_plugin : null,
	// 					schedule_type : 'direct',
	// 					service_rates : {
	// 						'e2111b1f-d265-4d8c-aca2-ffd6fd566638': {
	// 							legs    : null,
	// 							tags    : [],
	// 							price   : 12908.46085991,
	// 							source  : 'spot_rates',
	// 							arrival : '2023-06-18T00:00:00.000Z',
	// 							margins : [
	// 								{
	// 									id           : 'cbbb4230-4b76-40bd-89fb-8bc751984f5a',
	// 									status       : 'active',
	// 									filters      : {},
	// 									service      : 'fcl_freight',
	// 									agent_id     : null,
	// 									created_at   : '2021-12-22T05:09:48.451Z',
	// 									partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 									updated_at   : '2022-11-03T07:36:24.589Z',
	// 									margin_type  : 'cogoport',
	// 									agent_rm_ids : [],
	// 									margin_slabs : [
	// 										{
	// 											lower_limit   : 0.0,
	// 											upper_limit   : null,
	// 											margin_values : [
	// 												{
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 3.0,
	// 													currency  : 'USD',
	// 													max_value : 300.0,
	// 													min_value : 0.0,
	// 												},
	// 											],
	// 											margin_values_hash: {
	// 												BAS: {
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 3.0,
	// 													currency  : 'USD',
	// 													max_value : 300.0,
	// 													min_value : 0.0,
	// 												},
	// 											},
	// 										},
	// 									],
	// 									location_type : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									],
	// 									organization_id    : null,
	// 									filters_keys_count : 0,
	// 									margin_values_hash : {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									},
	// 									service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 									margin_slabs_currency : 'USD',
	// 								},
	// 								{
	// 									id      : '1efc2610-f137-4c9e-b6c4-fb5ffbb08338',
	// 									status  : 'active',
	// 									filters : {
	// 										trade_type: 'export',
	// 									},
	// 									service      : 'fcl_freight',
	// 									agent_id     : '0ccfc574-f942-4fb4-971d-a34c7ae691c3',
	// 									created_at   : '2021-05-06T15:24:51.960Z',
	// 									partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 									updated_at   : '2023-04-20T10:11:46.900Z',
	// 									margin_type  : 'demand',
	// 									agent_rm_ids : [
	// 										'cd8dde11-678c-4467-85b2-2e2d6055bef4',
	// 										'95d62549-8ab6-4ee5-a655-9edd0ec46dac',
	// 									],
	// 									margin_slabs: [
	// 										{
	// 											lower_limit   : 0.0,
	// 											upper_limit   : null,
	// 											margin_values : [
	// 												{
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 5.0,
	// 													currency  : 'USD',
	// 													max_value : 150.0,
	// 													min_value : 25.0,
	// 												},
	// 											],
	// 											margin_values_hash: {
	// 												BAS: {
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 5.0,
	// 													currency  : 'USD',
	// 													max_value : 150.0,
	// 													min_value : 25.0,
	// 												},
	// 											},
	// 										},
	// 									],
	// 									location_type : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									],
	// 									organization_id    : null,
	// 									filters_keys_count : 1,
	// 									margin_values_hash : {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									},
	// 									service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 									margin_slabs_currency : 'USD',
	// 								},
	// 							],
	// 							rate_id    : '890f5d53-caa6-4e17-9244-71b64fbbb6d7',
	// 							commodity  : 'general',
	// 							departure  : '2023-06-15T00:00:00.000Z',
	// 							si_cutoff  : null,
	// 							line_items : [
	// 								{
	// 									code    : 'BAS',
	// 									name    : 'Basic Freight',
	// 									unit    : 'per_container',
	// 									price   : 151.69,
	// 									source  : 'system',
	// 									margins : [
	// 										{
	// 											code               : 'BAS',
	// 											type               : 'percentage',
	// 											value              : 3.0,
	// 											currency           : 'USD',
	// 											max_value          : 300.0,
	// 											min_value          : 0.0,
	// 											margin_type        : 'cogoport',
	// 											margin_value       : 3.69,
	// 											total_margin_value : 3.69,
	// 										},
	// 										{
	// 											code               : 'BAS',
	// 											type               : 'percentage',
	// 											value              : 5.0,
	// 											currency           : 'USD',
	// 											max_value          : 150.0,
	// 											min_value          : 25.0,
	// 											margin_type        : 'demand',
	// 											margin_value       : 25.0,
	// 											total_margin_value : 25.0,
	// 										},
	// 									],
	// 									remarks: [
	// 										'test1212',
	// 									],
	// 									currency               : 'USD',
	// 									quantity               : 1,
	// 									buy_price              : 123.0,
	// 									total_price            : 151.69,
	// 									service_name           : 'fcl_freight',
	// 									service_type           : 'export',
	// 									total_buy_price        : 123.0,
	// 									price_discounted       : 151.69,
	// 									total_price_discounted : 151.69,
	// 								},
	// 							],
	// 							service_id   : null,
	// 							vgm_cutoff   : null,
	// 							likes_count  : 0,
	// 							total_price  : 12908.46085991,
	// 							validity_id  : '70500b13-9941-4291-b9bd-c9c3ca62121c',
	// 							origin_local : {
	// 								source              : 'spot_rates',
	// 								margins             : [],
	// 								line_items          : [],
	// 								service_provider_id : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							},
	// 							payment_term : 'prepaid',
	// 							service_type : 'fcl_freight',
	// 							transit_time : 3,
	// 							validity_end : '2023-06-15',
	// 							weight_limit : {
	// 								unit       : 'per_container',
	// 								slabs      : [],
	// 								margins    : [],
	// 								remarks    : [],
	// 								free_limit : 18.0,
	// 							},
	// 							origin_plugin : null,
	// 							schedule_type : 'direct',
	// 							total_margins : {
	// 								demand   : 2127.440975,
	// 								supply   : 0,
	// 								cogoport : 314.01028791,
	// 								currency : 'INR',
	// 							},
	// 							cogo_entity_id   : null,
	// 							container_size   : '20',
	// 							container_type   : 'standard',
	// 							dislikes_count   : 0,
	// 							validity_start   : '2023-06-08',
	// 							number_of_stops  : 0,
	// 							schedule_source  : 'predicted',
	// 							terminal_cutoff  : null,
	// 							containers_count : 1,
	// 							origin_demurrage : {
	// 								unit    : 'per_container',
	// 								slabs   : [],
	// 								margins : [],
	// 							},
	// 							origin_detention: {
	// 								unit    : 'per_container',
	// 								slabs   : [],
	// 								margins : [],
	// 							},
	// 							price_discounted  : 12908.46085991,
	// 							shipping_line_id  : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 							destination_local : {
	// 								margins: [],
	// 							},
	// 							is_rate_available     : true,
	// 							reliability_score     : 62,
	// 							destination_plugin    : null,
	// 							origin_main_port_id   : null,
	// 							service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							terms_and_conditions  : null,
	// 							total_price_currency  : 'INR',
	// 							destination_demurrage : {
	// 								unit    : 'per_container',
	// 								slabs   : [],
	// 								margins : [],
	// 							},
	// 							destination_detention: {
	// 								id                       : 'b1f22359-4cbe-4535-975e-30609dc33d01',
	// 								unit                     : 'per_container',
	// 								slabs                    : [],
	// 								margins                  : [],
	// 								remarks                  : [],
	// 								free_limit               : 12,
	// 								trade_type               : 'import',
	// 								location_id              : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 								location_type            : 'port',
	// 								free_days_type           : 'detention',
	// 								is_slabs_missing         : true,
	// 								shipping_line_id         : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 								specificity_type         : 'rate_specific',
	// 								service_provider_id      : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 								previous_days_applicable : false,
	// 								rate_not_available_entry : false,
	// 							},
	// 							rate_reference_number          : null,
	// 							total_price_discounted         : 12908.46085991,
	// 							origin_document_charges        : null,
	// 							destination_main_port_id       : null,
	// 							destination_document_charges   : null,
	// 							booking_rate_procurement_proof : null,
	// 							service_provider               : {
	// 								id             : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 								business_name  : 'MAERSK LINE A/S',
	// 								short_name     : 'MAERSK LINE A/S',
	// 								category_types : [
	// 									'shipping_line',
	// 								],
	// 								account_type : 'service_provider',
	// 								kyc_status   : 'verified',
	// 								status       : 'active',
	// 							},
	// 						},
	// 						'f2f0dbfc-aae1-4648-bd10-915e06a70261': {
	// 							source               : 'spot_rates',
	// 							margins              : [],
	// 							airline_id           : null,
	// 							line_items           : [],
	// 							trade_type           : 'export',
	// 							main_port_id         : null,
	// 							service_type         : 'fcl_freight_local',
	// 							container_size       : '20',
	// 							container_type       : 'standard',
	// 							shipping_line_id     : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 							is_rate_available    : false,
	// 							service_provider_id  : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							dependent_service_id : null,
	// 							service_provider     : {
	// 								id             : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 								business_name  : 'MAERSK LINE A/S',
	// 								short_name     : 'MAERSK LINE A/S',
	// 								category_types : [
	// 									'shipping_line',
	// 								],
	// 								account_type : 'service_provider',
	// 								kyc_status   : 'verified',
	// 								status       : 'active',
	// 							},
	// 						},
	// 					},
	// 					bookings_count   : 47,
	// 					cogo_entity_id   : null,
	// 					container_size   : '20',
	// 					container_type   : 'standard',
	// 					dislikes_count   : 0,
	// 					validity_start   : '2023-06-08',
	// 					number_of_stops  : 0,
	// 					schedule_source  : 'predicted',
	// 					terminal_cutoff  : null,
	// 					containers_count : 1,
	// 					origin_demurrage : {
	// 						unit    : 'per_container',
	// 						slabs   : [],
	// 						margins : [],
	// 					},
	// 					origin_detention: {
	// 						unit    : 'per_container',
	// 						slabs   : [],
	// 						margins : [],
	// 					},
	// 					price_discounted  : 12908.46085991,
	// 					shipping_line_id  : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 					destination_local : {
	// 						margins: [],
	// 					},
	// 					is_rate_available     : true,
	// 					reliability_score     : 62,
	// 					destination_plugin    : null,
	// 					origin_main_port_id   : null,
	// 					service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 					terms_and_conditions  : [],
	// 					total_price_currency  : 'INR',
	// 					destination_demurrage : {
	// 						unit    : 'per_container',
	// 						slabs   : [],
	// 						margins : [],
	// 					},
	// 					destination_detention: {
	// 						id                       : 'b1f22359-4cbe-4535-975e-30609dc33d01',
	// 						unit                     : 'per_container',
	// 						slabs                    : [],
	// 						margins                  : [],
	// 						remarks                  : [],
	// 						free_limit               : 12,
	// 						trade_type               : 'import',
	// 						location_id              : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 						location_type            : 'port',
	// 						free_days_type           : 'detention',
	// 						is_slabs_missing         : true,
	// 						shipping_line_id         : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 						specificity_type         : 'rate_specific',
	// 						service_provider_id      : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 						previous_days_applicable : false,
	// 						rate_not_available_entry : false,
	// 					},
	// 					rate_reference_number          : null,
	// 					freight_price_currency         : 'USD',
	// 					total_price_discounted         : 12908.46085991,
	// 					origin_document_charges        : null,
	// 					destination_main_port_id       : null,
	// 					freight_price_discounted       : 151.69,
	// 					destination_document_charges   : null,
	// 					booking_rate_procurement_proof : null,
	// 				},
	// 				container_size             : '20',
	// 				container_type             : 'standard',
	// 				origin_port_id             : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
	// 				containers_count           : 1,
	// 				destination_port_id        : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 				cargo_weight_per_container : 18,
	// 			},
	// 			cogo_entity_id : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 			closed_by_id   : '2dbe768e-929d-4e54-baf0-309ef68c978b',
	// 			closed_by      : {
	// 				id                    : '2dbe768e-929d-4e54-baf0-309ef68c978b',
	// 				name                  : 'Cogo Envision',
	// 				email                 : 'cogo.envision@cogoport.com',
	// 				mobile_number_eformat : '919649665944',
	// 			},
	// 			closing_remarks: [
	// 				'rate_added',
	// 			],
	// 			created_at          : '2023-06-06T16:06:38.486008Z',
	// 			fcl_freight_rate_id : '890f5d53-caa6-4e17-9244-71b64fbbb6d7',
	// 			feedback_type       : 'disliked',
	// 			feedbacks           : [
	// 				'unsatisfactory_rate',
	// 			],
	// 			outcome           : null,
	// 			outcome_object_id : null,
	// 			performed_by_id   : '039a0141-e6f3-43b0-9c51-144b22b9fc84',
	// 			performed_by      : {
	// 				id                    : '039a0141-e6f3-43b0-9c51-144b22b9fc84',
	// 				name                  : 'Santram Gurjar',
	// 				email                 : 'santram.gurjar@cogoport.com',
	// 				mobile_number_eformat : '919649665944',
	// 			},
	// 			performed_by_org_id : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
	// 			performed_by_org    : {
	// 				id             : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
	// 				status         : 'active',
	// 				kyc_status     : 'verified',
	// 				short_name     : 'VOLTAS LIMITED',
	// 				account_type   : 'importer_exporter',
	// 				business_name  : 'VOLTAS LIMITED',
	// 				category_types : null,
	// 			},
	// 			performed_by_type               : 'agent',
	// 			preferred_detention_free_days   : null,
	// 			preferred_freight_rate          : 213.0,
	// 			preferred_freight_rate_currency : 'USD',
	// 			preferred_shipping_line_ids     : [],
	// 			preferred_shipping_lines        : null,
	// 			remarks                         : [
	// 				'test 2222',
	// 			],
	// 			serial_id                : 9590,
	// 			source                   : 'spot_search',
	// 			source_id                : '2d656169-21c7-49ff-a10a-0f1b2952622f',
	// 			status                   : 'inactive',
	// 			updated_at               : '2023-06-06T16:17:20.355809Z',
	// 			validity_id              : '70500b13-9941-4291-b9bd-c9c3ca62121c',
	// 			origin_port_id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
	// 			origin_continent_id      : 'a5fad8d7-ea33-4dab-82d6-e7097fbffee1',
	// 			origin_trade_id          : 'd1e7b3ca-7518-4706-a644-e99d3aa2e0a9',
	// 			origin_country_id        : '541d1232-58ce-4d64-83d6-556a42209eb7',
	// 			destination_port_id      : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 			destination_continent_id : '4a4c0a00-1cc6-4662-822b-b2655c783ee8',
	// 			destination_trade_id     : '0cd3ac76-ee4e-4178-9511-8cf93caf045b',
	// 			destination_country_id   : '345f3aa9-ae78-40cf-b70a-fc5c3af2af99',
	// 			commodity                : 'general',
	// 			container_size           : '20',
	// 			container_type           : 'standard',
	// 			service_provider_id      : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 			origin_port              : {
	// 				id                  : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
	// 				loc                 : 'POINT (72.948 18.952)',
	// 				name                : 'Jawaharlal Nehru (Nhava Sheva)',
	// 				type                : 'seaport',
	// 				is_icd              : false,
	// 				status              : 'active',
	// 				address             : '',
	// 				city_id             : '4067099b-a672-40e1-b67d-ee58bdb1bbbd',
	// 				zone_id             : null,
	// 				cfs_code            : null,
	// 				latitude            : '18.952',
	// 				trade_id            : 'd1e7b3ca-7518-4706-a644-e99d3aa2e0a9',
	// 				longitude           : '72.948',
	// 				port_code           : 'INNSA',
	// 				region_id           : 'd25f8326-5d9f-416b-bbe8-81a84e466716',
	// 				site_code           : null,
	// 				airport_id          : null,
	// 				cluster_id          : null,
	// 				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
	// 				created_at          : '2019-11-22T05:00:13.528Z',
	// 				pincode_id          : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
	// 				seaport_id          : null,
	// 				updated_at          : '2023-01-10T14:56:17.403Z',
	// 				inttra_code         : 'INNSA',
	// 				postal_code         : '400707',
	// 				continent_id        : 'a5fad8d7-ea33-4dab-82d6-e7097fbffee1',
	// 				country_code        : 'IN',
	// 				display_name        : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
	// 				currency_code       : 'INR',
	// 				flag_icon_url       : '',
	// 				flag_image_url      : '',
	// 				cfs_agency_name     : null,
	// 				local_languages     : [],
	// 				mobile_country_code : null,
	// 			},
	// 			destination_port: {
	// 				id                  : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 				loc                 : 'POINT (55.052065 25.00328)',
	// 				name                : 'Jebel Ali',
	// 				type                : 'seaport',
	// 				is_icd              : false,
	// 				status              : 'active',
	// 				address             : null,
	// 				city_id             : '65199746-5fc9-43a5-87c4-0d37816ef904',
	// 				zone_id             : null,
	// 				cfs_code            : null,
	// 				latitude            : '25.00328',
	// 				trade_id            : '0cd3ac76-ee4e-4178-9511-8cf93caf045b',
	// 				longitude           : '55.052065',
	// 				port_code           : 'AEJEA',
	// 				region_id           : null,
	// 				site_code           : null,
	// 				airport_id          : null,
	// 				cluster_id          : null,
	// 				country_id          : '345f3aa9-ae78-40cf-b70a-fc5c3af2af99',
	// 				created_at          : '2019-11-22T05:00:17.467Z',
	// 				pincode_id          : null,
	// 				seaport_id          : null,
	// 				updated_at          : '2019-11-22T05:00:17.467Z',
	// 				inttra_code         : 'AEJEA',
	// 				postal_code         : null,
	// 				continent_id        : '4a4c0a00-1cc6-4662-822b-b2655c783ee8',
	// 				country_code        : 'AE',
	// 				display_name        : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
	// 				currency_code       : 'AED',
	// 				flag_icon_url       : null,
	// 				flag_image_url      : null,
	// 				cfs_agency_name     : null,
	// 				local_languages     : null,
	// 				mobile_country_code : null,
	// 			},
	// 			attachment_file_urls  : [],
	// 			commodity_description : null,
	// 			feedback_line_items   : [
	// 				{
	// 					code    : 'BAS',
	// 					unit    : 'per_container',
	// 					price   : 2345.0,
	// 					slabs   : [],
	// 					remarks : [
	// 						'testing',
	// 					],
	// 					currency: 'USD',
	// 				},
	// 			],
	// 			containers_count : 1,
	// 			bls_count        : 1,
	// 			inco_term        : 'cif',
	// 			old_price        : 151.69,
	// 			new_price        : 2345.0,
	// 			deviation        : 2193.31,
	// 		},
	// 		{
	// 			id             : '04962412-d6bc-4027-8a96-f236d2d2e9c1',
	// 			booking_params : {
	// 				bls_count : 1,
	// 				inco_term : 'cif',
	// 				rate_card : {
	// 					card    : 'c88f1030-fc3b-4da7-9a3f-2a1067475fec',
	// 					legs    : null,
	// 					tags    : [],
	// 					price   : 12908.46085991,
	// 					source  : 'spot_rates',
	// 					arrival : '2023-06-18T00:00:00.000Z',
	// 					margins : [
	// 						{
	// 							id           : 'cbbb4230-4b76-40bd-89fb-8bc751984f5a',
	// 							status       : 'active',
	// 							filters      : {},
	// 							service      : 'fcl_freight',
	// 							agent_id     : null,
	// 							created_at   : '2021-12-22T05:09:48.451Z',
	// 							partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 							updated_at   : '2022-11-03T07:36:24.589Z',
	// 							margin_type  : 'cogoport',
	// 							agent_rm_ids : [],
	// 							margin_slabs : [
	// 								{
	// 									lower_limit   : 0.0,
	// 									upper_limit   : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									],
	// 									margin_values_hash: {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									},
	// 								},
	// 							],
	// 							location_type : null,
	// 							margin_values : [
	// 								{
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 3.0,
	// 									currency  : 'USD',
	// 									max_value : 300.0,
	// 									min_value : 0.0,
	// 								},
	// 							],
	// 							organization_id    : null,
	// 							filters_keys_count : 0,
	// 							margin_values_hash : {
	// 								BAS: {
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 3.0,
	// 									currency  : 'USD',
	// 									max_value : 300.0,
	// 									min_value : 0.0,
	// 								},
	// 							},
	// 							service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							margin_slabs_currency : 'USD',
	// 						},
	// 						{
	// 							id      : '1efc2610-f137-4c9e-b6c4-fb5ffbb08338',
	// 							status  : 'active',
	// 							filters : {
	// 								trade_type: 'export',
	// 							},
	// 							service      : 'fcl_freight',
	// 							agent_id     : '0ccfc574-f942-4fb4-971d-a34c7ae691c3',
	// 							created_at   : '2021-05-06T15:24:51.960Z',
	// 							partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 							updated_at   : '2023-04-20T10:11:46.900Z',
	// 							margin_type  : 'demand',
	// 							agent_rm_ids : [
	// 								'cd8dde11-678c-4467-85b2-2e2d6055bef4',
	// 								'95d62549-8ab6-4ee5-a655-9edd0ec46dac',
	// 							],
	// 							margin_slabs: [
	// 								{
	// 									lower_limit   : 0.0,
	// 									upper_limit   : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									],
	// 									margin_values_hash: {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									},
	// 								},
	// 							],
	// 							location_type : null,
	// 							margin_values : [
	// 								{
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 5.0,
	// 									currency  : 'USD',
	// 									max_value : 150.0,
	// 									min_value : 25.0,
	// 								},
	// 							],
	// 							organization_id    : null,
	// 							filters_keys_count : 1,
	// 							margin_values_hash : {
	// 								BAS: {
	// 									code      : 'BAS',
	// 									type      : 'percentage',
	// 									value     : 5.0,
	// 									currency  : 'USD',
	// 									max_value : 150.0,
	// 									min_value : 25.0,
	// 								},
	// 							},
	// 							service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							margin_slabs_currency : 'USD',
	// 						},
	// 					],
	// 					rate_id    : '890f5d53-caa6-4e17-9244-71b64fbbb6d7',
	// 					is_liked   : true,
	// 					commodity  : 'general',
	// 					departure  : '2023-06-15T00:00:00.000Z',
	// 					si_cutoff  : null,
	// 					line_items : [
	// 						{
	// 							code    : 'BAS',
	// 							name    : 'Basic Freight',
	// 							unit    : 'per_container',
	// 							price   : 151.69,
	// 							source  : 'system',
	// 							margins : [
	// 								{
	// 									code               : 'BAS',
	// 									type               : 'percentage',
	// 									value              : 3.0,
	// 									currency           : 'USD',
	// 									max_value          : 300.0,
	// 									min_value          : 0.0,
	// 									margin_type        : 'cogoport',
	// 									margin_value       : 3.69,
	// 									total_margin_value : 3.69,
	// 								},
	// 								{
	// 									code               : 'BAS',
	// 									type               : 'percentage',
	// 									value              : 5.0,
	// 									currency           : 'USD',
	// 									max_value          : 150.0,
	// 									min_value          : 25.0,
	// 									margin_type        : 'demand',
	// 									margin_value       : 25.0,
	// 									total_margin_value : 25.0,
	// 								},
	// 							],
	// 							remarks: [
	// 								'test1212',
	// 							],
	// 							currency               : 'USD',
	// 							quantity               : 1,
	// 							buy_price              : 123.0,
	// 							total_price            : 151.69,
	// 							service_name           : 'fcl_freight',
	// 							service_type           : 'export',
	// 							total_buy_price        : 123.0,
	// 							price_discounted       : 151.69,
	// 							total_price_discounted : 151.69,
	// 						},
	// 					],
	// 					service_id   : null,
	// 					vgm_cutoff   : null,
	// 					is_disliked  : false,
	// 					likes_count  : 97,
	// 					total_price  : 12908.46085991,
	// 					validity_id  : '70500b13-9941-4291-b9bd-c9c3ca62121c',
	// 					origin_local : {
	// 						source              : 'spot_rates',
	// 						margins             : [],
	// 						line_items          : [],
	// 						service_provider_id : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 					},
	// 					payment_term : 'prepaid',
	// 					service_type : 'fcl_freight',
	// 					transit_time : 3,
	// 					validity_end : '2023-06-15',
	// 					weight_limit : {
	// 						unit       : 'per_container',
	// 						slabs      : [],
	// 						margins    : [],
	// 						remarks    : [],
	// 						free_limit : 18.0,
	// 					},
	// 					freight_price : 151.69,
	// 					origin_plugin : null,
	// 					schedule_type : 'direct',
	// 					service_rates : {
	// 						'a3087c64-a133-4686-848e-5a735aa411cc': {
	// 							source               : 'spot_rates',
	// 							margins              : [],
	// 							airline_id           : null,
	// 							line_items           : [],
	// 							trade_type           : 'export',
	// 							main_port_id         : null,
	// 							service_type         : 'fcl_freight_local',
	// 							container_size       : '20',
	// 							container_type       : 'standard',
	// 							shipping_line_id     : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 							is_rate_available    : false,
	// 							service_provider_id  : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							dependent_service_id : null,
	// 							service_provider     : {
	// 								id             : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 								business_name  : 'MAERSK LINE A/S',
	// 								short_name     : 'MAERSK LINE A/S',
	// 								category_types : [
	// 									'shipping_line',
	// 								],
	// 								account_type : 'service_provider',
	// 								kyc_status   : 'verified',
	// 								status       : 'active',
	// 							},
	// 						},
	// 						'a9252440-fe29-4230-bf1d-ab1458666642': {
	// 							legs    : null,
	// 							tags    : [],
	// 							price   : 12908.46085991,
	// 							source  : 'spot_rates',
	// 							arrival : '2023-06-18T00:00:00.000Z',
	// 							margins : [
	// 								{
	// 									id           : 'cbbb4230-4b76-40bd-89fb-8bc751984f5a',
	// 									status       : 'active',
	// 									filters      : {},
	// 									service      : 'fcl_freight',
	// 									agent_id     : null,
	// 									created_at   : '2021-12-22T05:09:48.451Z',
	// 									partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 									updated_at   : '2022-11-03T07:36:24.589Z',
	// 									margin_type  : 'cogoport',
	// 									agent_rm_ids : [],
	// 									margin_slabs : [
	// 										{
	// 											lower_limit   : 0.0,
	// 											upper_limit   : null,
	// 											margin_values : [
	// 												{
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 3.0,
	// 													currency  : 'USD',
	// 													max_value : 300.0,
	// 													min_value : 0.0,
	// 												},
	// 											],
	// 											margin_values_hash: {
	// 												BAS: {
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 3.0,
	// 													currency  : 'USD',
	// 													max_value : 300.0,
	// 													min_value : 0.0,
	// 												},
	// 											},
	// 										},
	// 									],
	// 									location_type : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									],
	// 									organization_id    : null,
	// 									filters_keys_count : 0,
	// 									margin_values_hash : {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 3.0,
	// 											currency  : 'USD',
	// 											max_value : 300.0,
	// 											min_value : 0.0,
	// 										},
	// 									},
	// 									service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 									margin_slabs_currency : 'USD',
	// 								},
	// 								{
	// 									id      : '1efc2610-f137-4c9e-b6c4-fb5ffbb08338',
	// 									status  : 'active',
	// 									filters : {
	// 										trade_type: 'export',
	// 									},
	// 									service      : 'fcl_freight',
	// 									agent_id     : '0ccfc574-f942-4fb4-971d-a34c7ae691c3',
	// 									created_at   : '2021-05-06T15:24:51.960Z',
	// 									partner_id   : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 									updated_at   : '2023-04-20T10:11:46.900Z',
	// 									margin_type  : 'demand',
	// 									agent_rm_ids : [
	// 										'cd8dde11-678c-4467-85b2-2e2d6055bef4',
	// 										'95d62549-8ab6-4ee5-a655-9edd0ec46dac',
	// 									],
	// 									margin_slabs: [
	// 										{
	// 											lower_limit   : 0.0,
	// 											upper_limit   : null,
	// 											margin_values : [
	// 												{
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 5.0,
	// 													currency  : 'USD',
	// 													max_value : 150.0,
	// 													min_value : 25.0,
	// 												},
	// 											],
	// 											margin_values_hash: {
	// 												BAS: {
	// 													code      : 'BAS',
	// 													type      : 'percentage',
	// 													value     : 5.0,
	// 													currency  : 'USD',
	// 													max_value : 150.0,
	// 													min_value : 25.0,
	// 												},
	// 											},
	// 										},
	// 									],
	// 									location_type : null,
	// 									margin_values : [
	// 										{
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									],
	// 									organization_id    : null,
	// 									filters_keys_count : 1,
	// 									margin_values_hash : {
	// 										BAS: {
	// 											code      : 'BAS',
	// 											type      : 'percentage',
	// 											value     : 5.0,
	// 											currency  : 'USD',
	// 											max_value : 150.0,
	// 											min_value : 25.0,
	// 										},
	// 									},
	// 									service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 									margin_slabs_currency : 'USD',
	// 								},
	// 							],
	// 							rate_id    : '890f5d53-caa6-4e17-9244-71b64fbbb6d7',
	// 							commodity  : 'general',
	// 							departure  : '2023-06-15T00:00:00.000Z',
	// 							si_cutoff  : null,
	// 							line_items : [
	// 								{
	// 									code    : 'BAS',
	// 									name    : 'Basic Freight',
	// 									unit    : 'per_container',
	// 									price   : 151.69,
	// 									source  : 'system',
	// 									margins : [
	// 										{
	// 											code               : 'BAS',
	// 											type               : 'percentage',
	// 											value              : 3.0,
	// 											currency           : 'USD',
	// 											max_value          : 300.0,
	// 											min_value          : 0.0,
	// 											margin_type        : 'cogoport',
	// 											margin_value       : 3.69,
	// 											total_margin_value : 3.69,
	// 										},
	// 										{
	// 											code               : 'BAS',
	// 											type               : 'percentage',
	// 											value              : 5.0,
	// 											currency           : 'USD',
	// 											max_value          : 150.0,
	// 											min_value          : 25.0,
	// 											margin_type        : 'demand',
	// 											margin_value       : 25.0,
	// 											total_margin_value : 25.0,
	// 										},
	// 									],
	// 									remarks: [
	// 										'test1212',
	// 									],
	// 									currency               : 'USD',
	// 									quantity               : 1,
	// 									buy_price              : 123.0,
	// 									total_price            : 151.69,
	// 									service_name           : 'fcl_freight',
	// 									service_type           : 'export',
	// 									total_buy_price        : 123.0,
	// 									price_discounted       : 151.69,
	// 									total_price_discounted : 151.69,
	// 								},
	// 							],
	// 							service_id   : null,
	// 							vgm_cutoff   : null,
	// 							likes_count  : 0,
	// 							total_price  : 12908.46085991,
	// 							validity_id  : '70500b13-9941-4291-b9bd-c9c3ca62121c',
	// 							origin_local : {
	// 								source              : 'spot_rates',
	// 								margins             : [],
	// 								line_items          : [],
	// 								service_provider_id : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							},
	// 							payment_term : 'prepaid',
	// 							service_type : 'fcl_freight',
	// 							transit_time : 3,
	// 							validity_end : '2023-06-15',
	// 							weight_limit : {
	// 								unit       : 'per_container',
	// 								slabs      : [],
	// 								margins    : [],
	// 								remarks    : [],
	// 								free_limit : 18.0,
	// 							},
	// 							origin_plugin : null,
	// 							schedule_type : 'direct',
	// 							total_margins : {
	// 								demand   : 2127.440975,
	// 								supply   : 0,
	// 								cogoport : 314.01028791,
	// 								currency : 'INR',
	// 							},
	// 							cogo_entity_id   : null,
	// 							container_size   : '20',
	// 							container_type   : 'standard',
	// 							dislikes_count   : 0,
	// 							validity_start   : '2023-06-08',
	// 							number_of_stops  : 0,
	// 							schedule_source  : 'predicted',
	// 							terminal_cutoff  : null,
	// 							containers_count : 1,
	// 							origin_demurrage : {
	// 								unit    : 'per_container',
	// 								slabs   : [],
	// 								margins : [],
	// 							},
	// 							origin_detention: {
	// 								unit    : 'per_container',
	// 								slabs   : [],
	// 								margins : [],
	// 							},
	// 							price_discounted  : 12908.46085991,
	// 							shipping_line_id  : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 							destination_local : {
	// 								margins: [],
	// 							},
	// 							is_rate_available     : true,
	// 							reliability_score     : 61,
	// 							destination_plugin    : null,
	// 							origin_main_port_id   : null,
	// 							service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 							terms_and_conditions  : null,
	// 							total_price_currency  : 'INR',
	// 							destination_demurrage : {
	// 								unit    : 'per_container',
	// 								slabs   : [],
	// 								margins : [],
	// 							},
	// 							destination_detention: {
	// 								id                       : 'b1f22359-4cbe-4535-975e-30609dc33d01',
	// 								unit                     : 'per_container',
	// 								slabs                    : [],
	// 								margins                  : [],
	// 								remarks                  : [],
	// 								free_limit               : 12,
	// 								trade_type               : 'import',
	// 								location_id              : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 								location_type            : 'port',
	// 								free_days_type           : 'detention',
	// 								is_slabs_missing         : true,
	// 								shipping_line_id         : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 								specificity_type         : 'rate_specific',
	// 								service_provider_id      : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 								previous_days_applicable : false,
	// 								rate_not_available_entry : false,
	// 							},
	// 							rate_reference_number          : null,
	// 							total_price_discounted         : 12908.46085991,
	// 							origin_document_charges        : null,
	// 							destination_main_port_id       : null,
	// 							destination_document_charges   : null,
	// 							booking_rate_procurement_proof : null,
	// 							service_provider               : {
	// 								id             : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 								business_name  : 'MAERSK LINE A/S',
	// 								short_name     : 'MAERSK LINE A/S',
	// 								category_types : [
	// 									'shipping_line',
	// 								],
	// 								account_type : 'service_provider',
	// 								kyc_status   : 'verified',
	// 								status       : 'active',
	// 							},
	// 						},
	// 					},
	// 					bookings_count   : 44,
	// 					cogo_entity_id   : null,
	// 					container_size   : '20',
	// 					container_type   : 'standard',
	// 					dislikes_count   : 0,
	// 					validity_start   : '2023-06-08',
	// 					number_of_stops  : 0,
	// 					schedule_source  : 'predicted',
	// 					terminal_cutoff  : null,
	// 					containers_count : 1,
	// 					origin_demurrage : {
	// 						unit    : 'per_container',
	// 						slabs   : [],
	// 						margins : [],
	// 					},
	// 					origin_detention: {
	// 						unit    : 'per_container',
	// 						slabs   : [],
	// 						margins : [],
	// 					},
	// 					price_discounted  : 12908.46085991,
	// 					shipping_line_id  : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 					destination_local : {
	// 						margins: [],
	// 					},
	// 					is_rate_available     : true,
	// 					reliability_score     : 61,
	// 					destination_plugin    : null,
	// 					origin_main_port_id   : null,
	// 					service_provider_id   : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 					terms_and_conditions  : [],
	// 					total_price_currency  : 'INR',
	// 					destination_demurrage : {
	// 						unit    : 'per_container',
	// 						slabs   : [],
	// 						margins : [],
	// 					},
	// 					destination_detention: {
	// 						id                       : 'b1f22359-4cbe-4535-975e-30609dc33d01',
	// 						unit                     : 'per_container',
	// 						slabs                    : [],
	// 						margins                  : [],
	// 						remarks                  : [],
	// 						free_limit               : 12,
	// 						trade_type               : 'import',
	// 						location_id              : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 						location_type            : 'port',
	// 						free_days_type           : 'detention',
	// 						is_slabs_missing         : true,
	// 						shipping_line_id         : 'c3649537-0c4b-4614-b313-98540cffcf40',
	// 						specificity_type         : 'rate_specific',
	// 						service_provider_id      : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 						previous_days_applicable : false,
	// 						rate_not_available_entry : false,
	// 					},
	// 					rate_reference_number          : null,
	// 					freight_price_currency         : 'USD',
	// 					total_price_discounted         : 12908.46085991,
	// 					origin_document_charges        : null,
	// 					destination_main_port_id       : null,
	// 					freight_price_discounted       : 151.69,
	// 					destination_document_charges   : null,
	// 					booking_rate_procurement_proof : null,
	// 				},
	// 				container_size             : '20',
	// 				container_type             : 'standard',
	// 				origin_port_id             : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
	// 				containers_count           : 1,
	// 				destination_port_id        : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 				cargo_weight_per_container : 18,
	// 			},
	// 			cogo_entity_id      : '6fd98605-9d5d-479d-9fac-cf905d292b88',
	// 			closed_by_id        : null,
	// 			closed_by           : null,
	// 			closing_remarks     : [],
	// 			created_at          : '2023-06-06T15:58:38.736561Z',
	// 			fcl_freight_rate_id : '890f5d53-caa6-4e17-9244-71b64fbbb6d7',
	// 			feedback_type       : 'disliked',
	// 			feedbacks           : [
	// 				'unsatisfactory_rate',
	// 			],
	// 			outcome           : null,
	// 			outcome_object_id : null,
	// 			performed_by_id   : '039a0141-e6f3-43b0-9c51-144b22b9fc84',
	// 			performed_by      : {
	// 				id                    : '039a0141-e6f3-43b0-9c51-144b22b9fc84',
	// 				name                  : 'Santram Gurjar',
	// 				email                 : 'santram.gurjar@cogoport.com',
	// 				mobile_number_eformat : '919649665944',
	// 			},
	// 			performed_by_org_id : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
	// 			performed_by_org    : {
	// 				id             : 'e0c1ce39-299a-44c4-b5e8-03c25bde387e',
	// 				status         : 'active',
	// 				kyc_status     : 'verified',
	// 				short_name     : 'VOLTAS LIMITED',
	// 				account_type   : 'importer_exporter',
	// 				business_name  : 'VOLTAS LIMITED',
	// 				category_types : null,
	// 			},
	// 			performed_by_type               : 'agent',
	// 			preferred_detention_free_days   : null,
	// 			preferred_freight_rate          : 345.0,
	// 			preferred_freight_rate_currency : 'USD',
	// 			preferred_shipping_line_ids     : [],
	// 			preferred_shipping_lines        : null,
	// 			remarks                         : [
	// 				'test 111',
	// 			],
	// 			serial_id                : 9589,
	// 			source                   : 'spot_search',
	// 			source_id                : '0abc1df9-4ed2-4430-963e-f4168694b1ff',
	// 			status                   : 'active',
	// 			updated_at               : '2023-06-06T16:00:53.566065Z',
	// 			validity_id              : '70500b13-9941-4291-b9bd-c9c3ca62121c',
	// 			origin_port_id           : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
	// 			origin_continent_id      : 'a5fad8d7-ea33-4dab-82d6-e7097fbffee1',
	// 			origin_trade_id          : 'd1e7b3ca-7518-4706-a644-e99d3aa2e0a9',
	// 			origin_country_id        : '541d1232-58ce-4d64-83d6-556a42209eb7',
	// 			destination_port_id      : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 			destination_continent_id : '4a4c0a00-1cc6-4662-822b-b2655c783ee8',
	// 			destination_trade_id     : '0cd3ac76-ee4e-4178-9511-8cf93caf045b',
	// 			destination_country_id   : '345f3aa9-ae78-40cf-b70a-fc5c3af2af99',
	// 			commodity                : 'general',
	// 			container_size           : '20',
	// 			container_type           : 'standard',
	// 			service_provider_id      : '9f9daa7e-8575-411a-86e9-5f8e2fced580',
	// 			origin_port              : {
	// 				id                  : 'eb187b38-51b2-4a5e-9f3c-978033ca1ddf',
	// 				loc                 : 'POINT (72.948 18.952)',
	// 				name                : 'Jawaharlal Nehru (Nhava Sheva)',
	// 				type                : 'seaport',
	// 				is_icd              : false,
	// 				status              : 'active',
	// 				address             : '',
	// 				city_id             : '4067099b-a672-40e1-b67d-ee58bdb1bbbd',
	// 				zone_id             : null,
	// 				cfs_code            : null,
	// 				latitude            : '18.952',
	// 				trade_id            : 'd1e7b3ca-7518-4706-a644-e99d3aa2e0a9',
	// 				longitude           : '72.948',
	// 				port_code           : 'INNSA',
	// 				region_id           : 'd25f8326-5d9f-416b-bbe8-81a84e466716',
	// 				site_code           : null,
	// 				airport_id          : null,
	// 				cluster_id          : null,
	// 				country_id          : '541d1232-58ce-4d64-83d6-556a42209eb7',
	// 				created_at          : '2019-11-22T05:00:13.528Z',
	// 				pincode_id          : '74a228a7-6fcb-4ebd-bd4e-dbd776359f3b',
	// 				seaport_id          : null,
	// 				updated_at          : '2023-01-10T14:56:17.403Z',
	// 				inttra_code         : 'INNSA',
	// 				postal_code         : '400707',
	// 				continent_id        : 'a5fad8d7-ea33-4dab-82d6-e7097fbffee1',
	// 				country_code        : 'IN',
	// 				display_name        : 'Jawaharlal Nehru (Nhava Sheva) (INNSA), Mumbai, India',
	// 				currency_code       : 'INR',
	// 				flag_icon_url       : '',
	// 				flag_image_url      : '',
	// 				cfs_agency_name     : null,
	// 				local_languages     : [],
	// 				mobile_country_code : null,
	// 			},
	// 			destination_port: {
	// 				id                  : '23630ba9-b478-4000-ba75-05606d72d19f',
	// 				loc                 : 'POINT (55.052065 25.00328)',
	// 				name                : 'Jebel Ali',
	// 				type                : 'seaport',
	// 				is_icd              : false,
	// 				status              : 'active',
	// 				address             : null,
	// 				city_id             : '65199746-5fc9-43a5-87c4-0d37816ef904',
	// 				zone_id             : null,
	// 				cfs_code            : null,
	// 				latitude            : '25.00328',
	// 				trade_id            : '0cd3ac76-ee4e-4178-9511-8cf93caf045b',
	// 				longitude           : '55.052065',
	// 				port_code           : 'AEJEA',
	// 				region_id           : null,
	// 				site_code           : null,
	// 				airport_id          : null,
	// 				cluster_id          : null,
	// 				country_id          : '345f3aa9-ae78-40cf-b70a-fc5c3af2af99',
	// 				created_at          : '2019-11-22T05:00:17.467Z',
	// 				pincode_id          : null,
	// 				seaport_id          : null,
	// 				updated_at          : '2019-11-22T05:00:17.467Z',
	// 				inttra_code         : 'AEJEA',
	// 				postal_code         : null,
	// 				continent_id        : '4a4c0a00-1cc6-4662-822b-b2655c783ee8',
	// 				country_code        : 'AE',
	// 				display_name        : 'Jebel Ali (AEJEA), Dubai, United Arab Emirates',
	// 				currency_code       : 'AED',
	// 				flag_icon_url       : null,
	// 				flag_image_url      : null,
	// 				cfs_agency_name     : null,
	// 				local_languages     : null,
	// 				mobile_country_code : null,
	// 			},
	// 			attachment_file_urls  : [],
	// 			commodity_description : null,
	// 			feedback_line_items   : [],
	// 			containers_count      : 1,
	// 			bls_count             : 1,
	// 			inco_term             : 'cif',
	// 			old_price             : 151.69,
	// 		},
	// 	],
	// 	page        : 1,
	// 	total       : 1,
	// 	total_count : 2,
	// 	page_limit  : 10,
	// 	stats       : {
	// 		total                : 2,
	// 		total_closed_by_user : 0,
	// 		total_opened_by_user : 0,
	// 		total_open           : 1,
	// 		total_closed         : 1,
	// 	},
	// };

	return (
		<>
			<div>
				<p className={styles.main_heading}>Feedback Dashboard</p>
				<Filters filters={filters} setFilters={setFilters} />
			</div>
			<div className={styles.container}>
				<Pagination
					type="table"
					currentPage={page}
					totalItems={data?.total_count}
					pageSize={data?.page_limit}
					onPageChange={(newPage) => {
						setFilters((prev) => ({ ...prev, page: newPage }));
					}}
				/>
				<div className={styles.list_panel}>
					<div>
						{loading ? <Loader /> : null}
					</div>
					{(!loading && !list.length) ? <EmptyState />
						: (
							<>
								{list.map((item) => <FeedbackCard data={item} key={item.id} />)}
							</>
						)}
				</div>
			</div>
		</>
	);
}
export default FeedbackDashboard;
