name: Auto PR and Merge

on:
  schedule:
    - cron: "30 16 * * *"

jobs:
  auto-pr-merge:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        id: create
        run: |
          pr_number=$(curl -Lfs \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.COGOPORT_DEV_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"Merge pre-release into main","body":"Automated PR by GitHub Actions","head":"pre-release","base":"main"}' | jq -r '.number')
          echo "pr_number=$pr_number" >> "$GITHUB_OUTPUT"
      - name: Merge PR
        id: merge
        env:
          pr_number: ${{steps.create.outputs.pr_number}}
        run: |
          curl -Lfs \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.COGOPORT_DEV_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge \
            -d '{"commit_title": "Merge pre-release into main", "commit_message": "Merged by GitHub Actions", "merge_method": "merge"}'
