name: Run Setup

on:
  workflow_call:
    secrets:
      NPM_TOKEN:
        required: true

jobs:
  run-setup:
    name: Run Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Setup Npm Config
        run: npm config set '//registry.npmjs.org/:_authToken' ${{ secrets.NPM_TOKEN }}

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        id: pnpm-install
        with:
          version: 7

      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - name: Setup Cache
        uses: actions/cache@v2
        id: cache
        with:
          path: |
            **/node_modules
            ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: node_modules-${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Installing Dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: pnpm install --frozen-lockfile

