name: Sync Branches

on:
  push:
    branches: ["main"]

jobs:
  sync-prerelease:
    runs-on: ubuntu-latest
    steps:
      - name: Create PR
        id: create
        run: |
          pr_number=$(curl -Lfs \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.COGOPORT_DEV_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls \
            -d '{"title":"Sync pre-release with main","body":"Automated PR by GitHub Actions","head":"main","base":"pre-release"}' | jq -r '.number')
          echo "pr_number=$pr_number" | tee -a "$GITHUB_OUTPUT"
      - name: Merge PR
        id: merge
        env:
          pr_number: ${{steps.create.outputs.pr_number}}
        run: |
          curl -Lfs \
            -X PUT \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.COGOPORT_DEV_ADMIN_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/${{ github.repository }}/pulls/$pr_number/merge \
            -d '{"commit_title": "Sync pre-release with main", "commit_message": "Merged by GitHub Actions", "merge_method": "merge"}'
